/* Real-browser P42 QA: node tests/career-learning-responsive.browser.js [url] */
const assert = require('node:assert/strict');
const childProcess = require('node:child_process');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

const edge = ['C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe', 'C:\\Program Files\\Microsoft\\Edge\\Application\\msedge.exe'].find((candidate) => fs.existsSync(candidate)); if (!edge) throw new Error('Microsoft Edge is required for responsive browser QA.');
const baseUrl = process.argv[2] || 'http://127.0.0.1:4173/'; const port = 10920 + Math.floor(Math.random() * 60); const profile = path.join(os.tmpdir(), `klearn-p42-browser-${process.pid}`);
const browser = childProcess.spawn(edge, ['--headless=new', `--remote-debugging-port=${port}`, `--user-data-dir=${profile}`, '--disable-gpu', '--no-first-run', '--no-default-browser-check', 'about:blank'], { stdio: 'ignore', windowsHide: true });
const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms)); async function json(url, options) { const response = await fetch(url, options); if (!response.ok) throw new Error(`${response.status} ${url}`); return response.json(); }
async function connect(url) { const socket = new WebSocket(url); let id = 0; const pending = new Map(); await new Promise((resolve, reject) => { socket.onopen = resolve; socket.onerror = reject; }); socket.onmessage = (event) => { const message = JSON.parse(event.data); const request = pending.get(message.id); if (!request) return; pending.delete(message.id); message.error ? request.reject(new Error(message.error.message)) : request.resolve(message.result); }; return { send(method, params = {}) { return new Promise((resolve, reject) => { const next = ++id; pending.set(next, { resolve, reject }); socket.send(JSON.stringify({ id: next, method, params })); }); }, close() { socket.close(); } }; }
async function evaluate(cdp, expression) { const output = await cdp.send('Runtime.evaluate', { expression, returnByValue: true, awaitPromise: true }); if (output.exceptionDetails) throw new Error(output.exceptionDetails.exception?.description || output.exceptionDetails.text); return output.result.value; }
async function until(cdp, expression, attempts = 100) { for (let attempt = 0; attempt < attempts; attempt += 1) { if (await evaluate(cdp, expression)) return true; await wait(100); } return false; }

(async () => {
  try {
    let version; for (let attempt = 0; attempt < 50 && !version; attempt += 1) { try { version = await json(`http://127.0.0.1:${port}/json/version`); } catch (_) { await wait(100); } } if (!version) throw new Error('Could not start Edge.');
    const target = await json(`http://127.0.0.1:${port}/json/new?${encodeURIComponent(baseUrl)}`, { method: 'PUT' }); const cdp = await connect(target.webSocketDebuggerUrl); await cdp.send('Page.enable'); await cdp.send('Runtime.enable'); assert.equal(await until(cdp, `location.origin !== 'null' && document.readyState === 'complete'`), true, 'page did not load');
    const timestamp = new Date().toISOString(); const user = { id: 'p42-qa', fullName: 'P42 Learner', email: 'p42@local.test', level: 'TOPIK 2', studyMinutesPerDay: 30, onboardingCompleted: true, createdAt: timestamp };
    await evaluate(cdp, `(() => { localStorage.setItem('klearn_users', ${JSON.stringify(JSON.stringify([user]))}); localStorage.setItem('klearn_session', ${JSON.stringify(JSON.stringify({ userId: user.id, createdAt: timestamp }))}); localStorage.setItem('klearn_progress', ${JSON.stringify(JSON.stringify({ [user.id]: { skills: { reading: 70, vocabulary: 65, grammar: 58, writing: 50 }, stats: { streak: 2 }, lessonProgress: {}, daily: { date: timestamp.slice(0,10), tasks: {} } } }))}); localStorage.setItem('klearn_srs', ${JSON.stringify(JSON.stringify({ [user.id]: [] }))}); localStorage.setItem('klearn_settings', ${JSON.stringify(JSON.stringify({ users: { [user.id]: { theme: 'dark', language: 'vi' } } }))}); location.hash='career-center'; location.reload(); })()`);
    assert.equal(await until(cdp, `Boolean(window.KoreanCareerLearningEcosystem && document.querySelector('.career-tool-grid'))`), true, 'P42 career center did not render'); assert.equal(await until(cdp, `window.CareerContentService.paths().length === 6`), true, 'six career paths did not hydrate'); assert.equal(await evaluate(cdp, `document.querySelector('[data-route="lessons"]').classList.contains('active')`), true, 'career center must map to Learning navigation');
    const results = [];
    for (const width of [360, 768, 1024, 1440, 1920]) {
      await cdp.send('Emulation.setDeviceMetricsOverride', { width, height: 1100, deviceScaleFactor: 1, mobile: false }); await wait(100);
      const metrics = await evaluate(cdp, `(() => { const app=document.getElementById('app'),nav=document.getElementById('bottomNav'),paths=document.querySelector('.career-paths'),tools=document.querySelector('.career-tool-grid');const rect=(node)=>{const r=node?.getBoundingClientRect();return r?{left:r.left,width:r.width,right:r.right}:null};return{dark:document.documentElement.dataset.theme==='dark',overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth,bodyOverflow:document.body.scrollWidth>document.body.clientWidth,app:rect(app),nav:rect(nav),pathColumns:getComputedStyle(paths).gridTemplateColumns.split(' ').length,toolColumns:getComputedStyle(tools).gridTemplateColumns.split(' ').length,minTouch:Math.min(...[...document.querySelectorAll('.career-paths button,.career-tool-grid button')].map((node)=>node.getBoundingClientRect().height))};})()`);
      assert.equal(metrics.dark, true, `dark mode missing at ${width}px`); assert.equal(metrics.overflow, false, `html overflow at ${width}px`); assert.equal(metrics.bodyOverflow, false, `body overflow at ${width}px`); assert.ok(metrics.minTouch >= 44, `touch target too small at ${width}px`);
      if (width >= 1024) { assert.ok(metrics.nav.width >= 240 && metrics.nav.width <= 280, `sidebar invalid at ${width}px`); assert.ok(metrics.app.left >= 240, `content overlaps sidebar at ${width}px`); } else assert.ok(metrics.app.left < 2, `compact content offset at ${width}px`);
      assert.equal(metrics.pathColumns, width <= 600 ? 2 : width <= 1050 ? 3 : 6, `career path grid invalid at ${width}px`); assert.equal(metrics.toolColumns, width <= 600 ? 1 : width <= 1050 ? 2 : 4, `career tools grid invalid at ${width}px`); results.push({ width, paths: metrics.pathColumns, tools: metrics.toolColumns, overflow: metrics.overflow });
    }
    await cdp.send('Emulation.setDeviceMetricsOverride', { width: 360, height: 1200, deviceScaleFactor: 1, mobile: false });
    await evaluate(cdp, `document.querySelector('[data-career-path="manufacturing"]').click()`); assert.equal(await until(cdp, `window.CareerPathService.currentId()==='manufacturing'`), true, 'career selection did not persist');
    await evaluate(cdp, `window.KLEARN_APP.setView('career-vocabulary')`); assert.equal(await until(cdp, `document.querySelectorAll('.career-vocab-grid article').length===6`), true, 'career vocabulary pack missing'); await evaluate(cdp, `document.querySelector('[data-career-add-srs]').click()`); assert.equal(await evaluate(cdp, `window.ProfessionalVocabularyService.words().every(word=>window.KLEARN_APP.state.srsData.some(card=>card.korean===word.korean))`), true, 'career pack not fully represented in SRS');
    await evaluate(cdp, `window.KLEARN_APP.setView('job-interview-trainer')`); assert.equal(await until(cdp, `Boolean(document.getElementById('careerInterviewForm'))`), true, 'interview trainer missing'); assert.equal(await evaluate(cdp, `document.querySelector('.career-practice').innerText.includes('웹 개발 경력')`), false, 'interview model revealed before response');
    await evaluate(cdp, `(() => { const f=document.getElementById('careerInterviewForm');f.elements.answer.value='안녕하세요. 저는 개발자입니다. 프로젝트 경험이 있고 협업이 강점입니다.';f.requestSubmit();})()`); assert.equal(await until(cdp, `Boolean(document.querySelector('.career-feedback.good'))`), true, 'interview feedback missing');
    await evaluate(cdp, `window.KLEARN_APP.setView('korean-resume-builder')`); assert.equal(await until(cdp, `Boolean(document.getElementById('careerResumeForm'))`), true, 'resume builder missing'); await evaluate(cdp, `(() => {const f=document.getElementById('careerResumeForm');f.elements.headline.value='웹 개발자';f.elements.summary.value='3년 경력입니다.';f.elements.experience.value='프로젝트 경험';f.elements.skills.value='JavaScript';f.requestSubmit();})()`); assert.equal(await until(cdp, `window.KoreanResumeService.completeness().percentage===100`), true, 'private resume did not save');
    assert.equal(await evaluate(cdp, `JSON.stringify(window.CareerProgressService.summary()).includes('프로젝트 경험')`), false, 'report leaked resume text'); await evaluate(cdp, `window.KLEARN_APP.setView('career-report')`); assert.equal(await until(cdp, `Boolean(document.querySelector('.career-report-hero'))`), true, 'career report missing');
    for (const route of ['career-center','career-vocabulary','workplace-scenarios','job-interview-trainer','korean-resume-builder','business-email-writing','presentation-coach','workplace-culture','career-report']) { await evaluate(cdp, `window.KLEARN_APP.setView(${JSON.stringify(route)})`); await wait(60); assert.equal(await evaluate(cdp, `document.documentElement.scrollWidth>document.documentElement.clientWidth || document.body.scrollWidth>document.body.clientWidth`), false, `${route} overflows at 360px`); }
    console.log(JSON.stringify(results)); console.log('career learning responsive: six paths, dark mode, 360-1920 layout, SRS import, interview answer gating, private resume and readiness report passed'); cdp.close();
  } finally { browser.kill(); await wait(200); if (path.resolve(profile).startsWith(path.resolve(os.tmpdir()))) fs.rmSync(profile, { recursive: true, force: true, maxRetries: 8, retryDelay: 100 }); }
})().catch((error) => { console.error(error); process.exitCode = 1; });
