/* Real-browser P59 QA: node tests/global-language-platform-responsive.browser.js [url] */
const assert = require('node:assert/strict');
const childProcess = require('node:child_process');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const edge = ['C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe', 'C:\\Program Files\\Microsoft\\Edge\\Application\\msedge.exe'].find((item) => fs.existsSync(item)); if (!edge) throw new Error('Microsoft Edge is required.');
const baseUrl = process.argv[2] || 'http://127.0.0.1:4173/'; const port = 11300 + Math.floor(Math.random() * 70); const profile = path.join(os.tmpdir(), `klearn-p59-browser-${process.pid}`); const browser = childProcess.spawn(edge, ['--headless=new', `--remote-debugging-port=${port}`, `--user-data-dir=${profile}`, '--disable-gpu', '--no-first-run', '--no-default-browser-check', 'about:blank'], { stdio: 'ignore', windowsHide: true });
const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms)); async function json(url, options) { const response = await fetch(url, options); if (!response.ok) throw new Error(`${response.status} ${url}`); return response.json(); }
async function connect(url) { const socket = new WebSocket(url); let id = 0; const pending = new Map(); await new Promise((resolve, reject) => { socket.onopen = resolve; socket.onerror = reject; }); socket.onmessage = (event) => { const message = JSON.parse(event.data); const request = pending.get(message.id); if (!request) return; pending.delete(message.id); message.error ? request.reject(new Error(message.error.message)) : request.resolve(message.result); }; return { send(method, params = {}) { return new Promise((resolve, reject) => { const next = ++id; pending.set(next, { resolve, reject }); socket.send(JSON.stringify({ id: next, method, params })); }); }, close() { socket.close(); } }; }
async function evaluate(cdp, expression) { const value = await cdp.send('Runtime.evaluate', { expression, returnByValue: true, awaitPromise: true }); if (value.exceptionDetails) throw new Error(value.exceptionDetails.exception?.description || value.exceptionDetails.text); return value.result.value; }
async function until(cdp, expression, attempts = 100) { for (let i = 0; i < attempts; i += 1) { if (await evaluate(cdp, expression)) return true; await wait(100); } return false; }
(async () => {
  try {
    let version; for (let i = 0; i < 50 && !version; i += 1) { try { version = await json(`http://127.0.0.1:${port}/json/version`); } catch (_) { await wait(100); } } if (!version) throw new Error('Could not start Edge.');
    const target = await json(`http://127.0.0.1:${port}/json/new?${encodeURIComponent(baseUrl)}`, { method: 'PUT' }); const cdp = await connect(target.webSocketDebuggerUrl); await cdp.send('Page.enable'); await cdp.send('Runtime.enable'); assert.equal(await until(cdp, `location.origin !== 'null' && document.readyState==='complete'`), true);
    const timestamp = new Date().toISOString(); const user = { id: 'p59-qa', fullName: 'Global Learner', email: 'p59@local.test', level: 'TOPIK 1', onboardingCompleted: true, createdAt: timestamp };
    await evaluate(cdp, `(() => { localStorage.setItem('klearn_users', ${JSON.stringify(JSON.stringify([user]))}); localStorage.setItem('klearn_session', ${JSON.stringify(JSON.stringify({ userId: user.id, createdAt: timestamp }))}); localStorage.setItem('klearn_progress', ${JSON.stringify(JSON.stringify({ [user.id]: { skills: {}, stats: { streak: 2 }, lessonProgress: { 'legacy-ko-lesson': { masteryScore: 80 } }, daily: { tasks: {} } } }))}); localStorage.setItem('klearn_srs', ${JSON.stringify(JSON.stringify({ [user.id]: [{ id: '학교', korean: '학교', meaningVi: 'trường học', status: 'review' }] }))}); localStorage.setItem('klearn_settings', ${JSON.stringify(JSON.stringify({ users: { [user.id]: { theme: 'dark', language: 'vi' } } }))}); location.hash='global-language-platform'; location.reload(); })()`);
    assert.equal(await until(cdp, `Boolean(window.LanguagePlatformService?.version==='p59-v2' && document.querySelector('.glp-language-grid'))`), true, 'P59 hub missing');
    assert.equal(await evaluate(cdp, `document.querySelectorAll('.glp-language-grid article').length`), 4); assert.equal(await evaluate(cdp, `window.SharedLearningCoreService.knowledgeId('ko','legacy-ko-lesson')`), 'legacy-ko-lesson'); assert.equal(await evaluate(cdp, `window.SharedLearningCoreService.knowledgeId('ja','lesson-1')`), 'ja:lesson-1'); assert.equal(await evaluate(cdp, `document.querySelectorAll('.glp-ecosystem button').length`), 4);
    const widths = [];
    for (const width of [360, 768, 1024, 1440, 1920]) { await cdp.send('Emulation.setDeviceMetricsOverride', { width, height: 1100, deviceScaleFactor: 1, mobile: false }); await wait(80); const metrics = await evaluate(cdp, `(()=>({dark:document.documentElement.dataset.theme==='dark',overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth||document.body.scrollWidth>document.body.clientWidth,minTouch:Math.min(...[...document.querySelectorAll('.glp-language-grid button,.glp-core-links button,.glp-ecosystem button')].map(x=>x.getBoundingClientRect().height)),columns:getComputedStyle(document.querySelector('.glp-language-grid')).gridTemplateColumns.split(' ').length,nav:document.getElementById('bottomNav')?.getBoundingClientRect().width||0,appLeft:document.getElementById('app')?.getBoundingClientRect().left||0}))()`); assert.equal(metrics.dark, true, `dark ${width}`); assert.equal(metrics.overflow, false, `overflow ${width}`); assert.ok(metrics.minTouch >= 44, `touch ${width}`); assert.equal(metrics.columns, width <= 600 ? 1 : width <= 1023 ? 2 : 4); if (width >= 1024) { assert.ok(metrics.nav >= 240 && metrics.nav <= 280); assert.ok(metrics.appLeft >= 240); } else assert.ok(metrics.appLeft < 2); widths.push({ width, columns: metrics.columns, overflow: metrics.overflow }); }
    await cdp.send('Emulation.setDeviceMetricsOverride', { width: 360, height: 1100, deviceScaleFactor: 1, mobile: false });
    await evaluate(cdp, `window.KLEARN_APP.setView('global-language-profiles')`); assert.equal(await until(cdp, `document.querySelectorAll('.glp-profile-list article').length===4`), true, 'profile view missing'); await evaluate(cdp, `document.querySelector('[data-glp-add="ja"]').click()`); assert.ok(await evaluate(cdp, `Boolean(window.LanguageProfileService.getLanguage('ja'))`)); await evaluate(cdp, `document.querySelector('[data-glp-active="ja"]').click()`); assert.equal(await evaluate(cdp, `window.LanguageProfileService.active()`), 'ja');
    await evaluate(cdp, `window.KLEARN_APP.setView('global-exam-framework')`); assert.equal(await until(cdp, `document.querySelectorAll('.glp-exam-grid article').length===3`), true, 'exam view missing'); assert.match(await evaluate(cdp, `document.querySelector('.glp-exam-grid').innerText`), /TOPIK[\s\S]*JLPT[\s\S]*HSK/);
    await evaluate(cdp, `window.KLEARN_APP.setView('global-language-comparison')`); assert.equal(await until(cdp, `document.querySelectorAll('.glp-comparison article').length===3`), true, 'comparison view missing'); assert.match(await evaluate(cdp, `document.querySelector('.glp-comparison').innerText`), /Tôi là sinh viên[\s\S]*저는 학생이에요[\s\S]*私は学生です/);
    await evaluate(cdp, `window.KLEARN_APP.setView('global-expansion')`); assert.equal(await until(cdp, `document.querySelectorAll('.glp-expansion-table article').length===4`), true, 'expansion view missing'); assert.equal(await evaluate(cdp, `document.documentElement.scrollWidth>document.documentElement.clientWidth||document.body.scrollWidth>document.body.clientWidth`), false, 'expansion body overflow');
    await evaluate(cdp, `location.reload()`); assert.equal(await until(cdp, `Boolean(window.LanguageProfileService)`), true); assert.equal(await evaluate(cdp, `window.LanguageProfileService.active()`), 'ja', 'active language profile not persisted'); assert.equal(await evaluate(cdp, `window.SharedLearningCoreService.srsCards('ko').some(card=>card.id==='학교')`), true, 'legacy Korean SRS lost');
    console.log(JSON.stringify({ status: 'passed', widths, languages: 4, exams: 3, comparisons: 3, profilePersistence: true, legacyKoreanSrsPreserved: true })); cdp.close();
  } finally { browser.kill(); await wait(200); if (path.resolve(profile).startsWith(path.resolve(os.tmpdir()))) fs.rmSync(profile, { recursive: true, force: true, maxRetries: 8, retryDelay: 100 }); }
})().catch((error) => { console.error(error); process.exitCode = 1; });
