/* Real-browser P45 QA: node tests/global-education-marketplace-responsive.browser.js [url] */
const assert = require('node:assert/strict');
const childProcess = require('node:child_process');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const edge = ['C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe', 'C:\\Program Files\\Microsoft\\Edge\\Application\\msedge.exe'].find((item) => fs.existsSync(item)); if (!edge) throw new Error('Microsoft Edge is required.');
const baseUrl = process.argv[2] || 'http://127.0.0.1:4173/'; const port = 11200 + Math.floor(Math.random() * 70); const profile = path.join(os.tmpdir(), `klearn-p45-browser-${process.pid}`); const browser = childProcess.spawn(edge, ['--headless=new', `--remote-debugging-port=${port}`, `--user-data-dir=${profile}`, '--disable-gpu', '--no-first-run', '--no-default-browser-check', 'about:blank'], { stdio: 'ignore', windowsHide: true });
const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms)); async function json(url, options) { const response = await fetch(url, options); if (!response.ok) throw new Error(`${response.status} ${url}`); return response.json(); }
async function connect(url) { const socket = new WebSocket(url); let id = 0; const pending = new Map(); await new Promise((resolve, reject) => { socket.onopen = resolve; socket.onerror = reject; }); socket.onmessage = (event) => { const message = JSON.parse(event.data); const request = pending.get(message.id); if (!request) return; pending.delete(message.id); message.error ? request.reject(new Error(message.error.message)) : request.resolve(message.result); }; return { send(method, params = {}) { return new Promise((resolve, reject) => { const next = ++id; pending.set(next, { resolve, reject }); socket.send(JSON.stringify({ id: next, method, params })); }); }, close() { socket.close(); } }; }
async function evaluate(cdp, expression) { const value = await cdp.send('Runtime.evaluate', { expression, returnByValue: true, awaitPromise: true }); if (value.exceptionDetails) throw new Error(value.exceptionDetails.exception?.description || value.exceptionDetails.text); return value.result.value; }
async function until(cdp, expression, attempts = 100) { for (let i = 0; i < attempts; i += 1) { if (await evaluate(cdp, expression)) return true; await wait(100); } return false; }
(async () => {
  try {
    let version; for (let i = 0; i < 50 && !version; i += 1) { try { version = await json(`http://127.0.0.1:${port}/json/version`); } catch (_) { await wait(100); } } if (!version) throw new Error('Could not start Edge.');
    const target = await json(`http://127.0.0.1:${port}/json/new?${encodeURIComponent(baseUrl)}`, { method: 'PUT' }); const cdp = await connect(target.webSocketDebuggerUrl); await cdp.send('Page.enable'); await cdp.send('Runtime.enable'); assert.equal(await until(cdp, `location.origin !== 'null' && document.readyState==='complete'`), true);
    const timestamp = new Date().toISOString(); const user = { id: 'p45-qa', fullName: 'P45 Learner', email: 'p45@local.test', goals: ['conversation'], level: 'TOPIK 1', studyMinutesPerDay: 20, onboardingCompleted: true, createdAt: timestamp };
    await evaluate(cdp, `(() => { localStorage.setItem('klearn_users', ${JSON.stringify(JSON.stringify([user]))}); localStorage.setItem('klearn_session', ${JSON.stringify(JSON.stringify({ userId: user.id, createdAt: timestamp }))}); localStorage.setItem('klearn_progress', ${JSON.stringify(JSON.stringify({ [user.id]: { skills: { listening: 20 }, stats: { streak: 2 }, daily: { tasks: {} } } }))}); localStorage.setItem('klearn_srs', ${JSON.stringify(JSON.stringify({ [user.id]: [] }))}); localStorage.setItem('klearn_settings', ${JSON.stringify(JSON.stringify({ theme: 'dark', language: 'vi', users: { [user.id]: { theme: 'dark', language: 'vi' } } }))}); location.hash='global-education-marketplace'; location.reload(); })()`);
    assert.equal(await until(cdp, `Boolean(window.GlobalEducationMarketplace && document.querySelector('.gem-course-grid'))`), true, 'P45 marketplace missing');
    assert.equal(await evaluate(cdp, `document.querySelectorAll('.gem-course-card').length`), 5); assert.equal(await evaluate(cdp, `window.GlobalEducationMarketplace.teachers.all().length`), 3);
    assert.equal(await evaluate(cdp, `window.GlobalEducationMarketplace.teachers.publicProfile('teacher-minji').email === undefined`), true, 'private teacher field exposed');
    const results = [];
    for (const width of [360, 768, 1024, 1440, 1920]) {
      await cdp.send('Emulation.setDeviceMetricsOverride', { width, height: 1100, deviceScaleFactor: 1, mobile: false }); await wait(100);
      const metrics = await evaluate(cdp, `(()=>{const app=document.getElementById('app'),nav=document.getElementById('bottomNav'),grid=document.querySelector('.gem-course-grid');const r=n=>{const x=n?.getBoundingClientRect();return x?{left:x.left,width:x.width}:null};return{dark:document.documentElement.dataset.theme==='dark',overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth||document.body.scrollWidth>document.body.clientWidth,app:r(app),nav:r(nav),columns:getComputedStyle(grid).gridTemplateColumns.split(' ').length,minTouch:Math.min(...[...document.querySelectorAll('.gem-filters button,.gem-course-card footer button,.gem-teacher-link')].map(x=>x.getBoundingClientRect().height))};})()`);
      assert.equal(metrics.dark, true, `dark ${width}`); assert.equal(metrics.overflow, false, `overflow ${width}`); assert.ok(metrics.minTouch >= 44, `touch ${width}`);
      if (width >= 1024) { assert.ok(metrics.nav.width >= 240 && metrics.nav.width <= 280, `sidebar ${width}`); assert.ok(metrics.app.left >= 240, `content offset ${width}`); } else assert.ok(metrics.app.left < 2, `mobile/tablet offset ${width}`);
      assert.equal(metrics.columns, width <= 600 ? 1 : width <= 1050 ? 2 : 3, `grid ${width}`); results.push({ width, columns: metrics.columns, overflow: metrics.overflow });
    }
    await cdp.send('Emulation.setDeviceMetricsOverride', { width: 360, height: 1100, deviceScaleFactor: 1, mobile: false });
    await evaluate(cdp, `window.GlobalEducationMarketplace.courses.open('global-hangul-foundation')`); assert.equal(await until(cdp, `Boolean(document.querySelector('[data-gem-acquire="global-hangul-foundation"]'))`), true, 'course detail missing');
    await evaluate(cdp, `document.querySelector('[data-gem-acquire="global-hangul-foundation"]').click()`); assert.equal(await until(cdp, `Boolean(document.getElementById('gemReviewForm'))`), true, 'free enrollment did not unlock review');
    assert.equal(await evaluate(cdp, `window.GlobalEducationMarketplace.courses.progress('global-hangul-foundation')`), 0);
    await evaluate(cdp, `window.GlobalEducationMarketplace.courses.updateProgress('global-hangul-foundation',100); window.KLEARN_APP.setView('marketplace-certificates')`); assert.equal(await until(cdp, `Boolean(document.querySelector('[data-gem-certificate="global-hangul-foundation"]'))`), true, 'certificate eligibility missing');
    await evaluate(cdp, `document.querySelector('[data-gem-certificate="global-hangul-foundation"]').click()`); await wait(80); assert.match(await evaluate(cdp, `document.querySelector('.gem-certificates').innerText`), /local preview/i);
    await evaluate(cdp, `window.GlobalEducationMarketplace.teachers.open('teacher-lan')`); assert.equal(await until(cdp, `Boolean(document.querySelector('.gem-profile'))`), true, 'teacher profile missing'); assert.match(await evaluate(cdp, `document.querySelector('.gem-profile').innerText`), /6 năm kinh nghiệm/);
    await evaluate(cdp, `window.KLEARN_APP.setView('creator-studio')`); await wait(80); assert.match(await evaluate(cdp, `document.querySelector('#app').innerText`), /ROLE-BASED ACCESS|Cần role Teacher/i);
    await evaluate(cdp, `window.KLEARN_APP.setView('course-marketplace')`); assert.equal(await until(cdp, `Boolean(document.querySelector('[data-global-marketplace-entry]'))`), true, 'P22 marketplace entry missing');
    for (const route of ['global-education-marketplace','marketplace-course','marketplace-teacher','creator-studio','marketplace-moderation','creator-revenue','marketplace-certificates']) { await evaluate(cdp, `window.KLEARN_APP.setView('${route}')`); await wait(80); assert.equal(await evaluate(cdp, `document.documentElement.scrollWidth>document.documentElement.clientWidth||document.body.scrollWidth>document.body.clientWidth`), false, `${route} overflow`); }
    console.log(JSON.stringify(results)); console.log('global education marketplace responsive: P45 catalog, 360-1920 dark layout, teacher profile, free enrollment, review access, certificates, creator RBAC and marketplace entry passed'); cdp.close();
  } finally { browser.kill(); await wait(200); if (path.resolve(profile).startsWith(path.resolve(os.tmpdir()))) fs.rmSync(profile, { recursive: true, force: true, maxRetries: 8, retryDelay: 100 }); }
})().catch((error) => { console.error(error); process.exitCode = 1; });
