/* Real-browser P44 QA: node tests/immersive-korean-world-responsive.browser.js [url] */
const assert = require('node:assert/strict');
const childProcess = require('node:child_process');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const edge = ['C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe', 'C:\\Program Files\\Microsoft\\Edge\\Application\\msedge.exe'].find((item) => fs.existsSync(item)); if (!edge) throw new Error('Microsoft Edge is required.');
const baseUrl = process.argv[2] || 'http://127.0.0.1:4173/'; const port = 11100 + Math.floor(Math.random() * 70); const profile = path.join(os.tmpdir(), `klearn-p44-browser-${process.pid}`); const browser = childProcess.spawn(edge, ['--headless=new', `--remote-debugging-port=${port}`, `--user-data-dir=${profile}`, '--disable-gpu', '--no-first-run', '--no-default-browser-check', 'about:blank'], { stdio: 'ignore', windowsHide: true });
const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms)); async function json(url, options) { const response = await fetch(url, options); if (!response.ok) throw new Error(`${response.status} ${url}`); return response.json(); }
async function connect(url) { const socket = new WebSocket(url); let id = 0; const pending = new Map(); await new Promise((resolve, reject) => { socket.onopen = resolve; socket.onerror = reject; }); socket.onmessage = (event) => { const message = JSON.parse(event.data); const request = pending.get(message.id); if (!request) return; pending.delete(message.id); message.error ? request.reject(new Error(message.error.message)) : request.resolve(message.result); }; return { send(method, params = {}) { return new Promise((resolve, reject) => { const next = ++id; pending.set(next, { resolve, reject }); socket.send(JSON.stringify({ id: next, method, params })); }); }, close() { socket.close(); } }; }
async function evaluate(cdp, expression) { const value = await cdp.send('Runtime.evaluate', { expression, returnByValue: true, awaitPromise: true }); if (value.exceptionDetails) throw new Error(value.exceptionDetails.exception?.description || value.exceptionDetails.text); return value.result.value; }
async function until(cdp, expression, attempts = 100) { for (let i = 0; i < attempts; i += 1) { if (await evaluate(cdp, expression)) return true; await wait(100); } return false; }
(async () => {
  try {
    let version; for (let i = 0; i < 50 && !version; i += 1) { try { version = await json(`http://127.0.0.1:${port}/json/version`); } catch (_) { await wait(100); } } if (!version) throw new Error('Could not start Edge.');
    const target = await json(`http://127.0.0.1:${port}/json/new?${encodeURIComponent(baseUrl)}`, { method: 'PUT' }); const cdp = await connect(target.webSocketDebuggerUrl); await cdp.send('Page.enable'); await cdp.send('Runtime.enable'); assert.equal(await until(cdp, `location.origin !== 'null' && document.readyState==='complete'`), true);
    const timestamp = new Date().toISOString(); const user = { id: 'p44-qa', fullName: 'P44 Learner', email: 'p44@local.test', level: 'TOPIK 1', studyMinutesPerDay: 20, onboardingCompleted: true, createdAt: timestamp };
    await evaluate(cdp, `(() => { localStorage.setItem('klearn_users', ${JSON.stringify(JSON.stringify([user]))}); localStorage.setItem('klearn_session', ${JSON.stringify(JSON.stringify({ userId: user.id, createdAt: timestamp }))}); localStorage.setItem('klearn_progress', ${JSON.stringify(JSON.stringify({ [user.id]: { skills: { speaking: 20 }, stats: { streak: 2 }, daily: { tasks: {} } } }))}); localStorage.setItem('klearn_srs', ${JSON.stringify(JSON.stringify({ [user.id]: [] }))}); localStorage.setItem('klearn_settings', ${JSON.stringify(JSON.stringify({ theme: 'dark', language: 'vi', users: { [user.id]: { theme: 'dark', language: 'vi' } } }))}); location.hash='immersive-world'; location.reload(); })()`);
    assert.equal(await until(cdp, `Boolean(window.ImmersiveKoreanWorld && document.querySelector('[data-p44-world-panel]'))`), true, 'P58 hub missing'); assert.equal(await evaluate(cdp, `document.querySelectorAll('[data-p44-place]').length`), 4); assert.equal(await evaluate(cdp, `window.VirtualKoreanCityService.places().map(x=>x.id).join(',')`), 'airport,cafe,university,office'); assert.equal(await evaluate(cdp, `window.ScenarioLibraryService.all().length`), 7);
    const results = [];
    for (const width of [360, 768, 1024, 1440, 1920]) { await cdp.send('Emulation.setDeviceMetricsOverride', { width, height: 1100, deviceScaleFactor: 1, mobile: false }); await wait(100); const m = await evaluate(cdp, `(()=>{const app=document.getElementById('app'),nav=document.getElementById('bottomNav'),city=document.querySelector('.p44-city-grid'),exp=document.querySelector('.p44-experience-grid');const r=n=>{const x=n?.getBoundingClientRect();return x?{left:x.left,width:x.width}:null};return{dark:document.documentElement.dataset.theme==='dark',overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth||document.body.scrollWidth>document.body.clientWidth,app:r(app),nav:r(nav),city:getComputedStyle(city).gridTemplateColumns.split(' ').length,exp:getComputedStyle(exp).gridTemplateColumns.split(' ').length,minTouch:Math.min(...[...document.querySelectorAll('.p44-levels button,.p44-city-grid button,.p44-experience-grid button')].map(x=>x.getBoundingClientRect().height))};})()`); assert.equal(m.dark, true, `dark ${width}`); assert.equal(m.overflow, false, `overflow ${width}`); assert.ok(m.minTouch >= 44, `touch ${width}`); if (width >= 1024) { assert.ok(m.nav.width >= 240 && m.nav.width <= 280); assert.ok(m.app.left >= 240); } else assert.ok(m.app.left < 2); assert.equal(m.city, width <= 600 ? 1 : width <= 1023 ? 2 : 4); assert.equal(m.exp, width <= 600 ? 1 : width <= 1023 ? 2 : 4); results.push({ width, city: m.city, overflow: m.overflow }); }
    await cdp.send('Emulation.setDeviceMetricsOverride', { width: 360, height: 1100, deviceScaleFactor: 1, mobile: false }); await evaluate(cdp, `document.querySelector('[data-p44-level="intermediate"]').click()`); assert.equal(await evaluate(cdp, `window.ImmersiveLevelService.currentId()`), 'intermediate'); await evaluate(cdp, `window.DailyLifeSimulationService.start()`); assert.equal(await until(cdp, `Boolean(document.querySelector('[data-p44-daily-choice]'))`), true, 'daily simulation missing'); assert.equal(await evaluate(cdp, `document.documentElement.scrollWidth>document.documentElement.clientWidth||document.body.scrollWidth>document.body.clientWidth`), false);
    await evaluate(cdp, `window.InteractiveKoreanStoryService.start()`); assert.equal(await until(cdp, `Boolean(document.querySelector('[data-p44-story-choice]'))`), true, 'story choices missing'); await evaluate(cdp, `document.querySelector('[data-p44-story-choice="airport-train"]').click()`); await wait(80); assert.match(await evaluate(cdp, `document.querySelector('.p44-story-stage').innerText`), /친구가 점심/);
    await evaluate(cdp, `window.CultureDecisionGameService.start()`); assert.equal(await until(cdp, `Boolean(document.querySelector('[data-p44-culture-choice]'))`), true, 'culture game missing'); await evaluate(cdp, `window.KLEARN_APP.setView('immersive-readiness')`); assert.equal(await until(cdp, `Boolean(document.querySelector('.p44-readiness-hero'))`), true, 'readiness missing'); assert.match(await evaluate(cdp, `document.querySelector('.p44-readiness-hero').innerText`), /100|chứng nhận/i);
    await evaluate(cdp, `window.KLEARN_APP.setView('immersive-scenarios')`); assert.equal(await until(cdp, `Boolean(document.querySelector('.p58-scenario-grid'))`), true, 'scenario library missing'); assert.ok(await evaluate(cdp, `document.querySelectorAll('[data-p58-scenario]').length`) >= 2); await evaluate(cdp, `document.querySelector('[data-p58-role="student"]').click()`); assert.equal(await evaluate(cdp, `window.ScenarioLibraryService.role()`), 'student');
    await evaluate(cdp, `window.KLEARN_APP.setView('immersive-progress-map')`); assert.equal(await until(cdp, `document.querySelectorAll('.p58-progress-map article').length===3`), true, 'progress map missing'); assert.match(await evaluate(cdp, `document.querySelector('.p58-progress-map').innerText`), /Beginner[\s\S]*Intermediate[\s\S]*Advanced/);
    await evaluate(cdp, `window.LanguageSurvivalModeService.set(true); window.DailyLifeSimulationService.start()`); assert.equal(await until(cdp, `Boolean(document.querySelector('[data-p44-daily-choice]'))`), true); assert.equal(await evaluate(cdp, `document.documentElement.hasAttribute('data-immersive-survival')`), true); assert.equal(await evaluate(cdp, `document.querySelector('.p44-scene').innerText.includes('Bạn')`), false, 'Vietnamese translation visible in survival mode');
    for (const route of ['immersive-world','immersive-daily-life','immersive-story','immersive-culture-game','immersive-readiness','immersive-scenarios','immersive-progress-map']) { await evaluate(cdp, `window.KLEARN_APP.setView('${route}')`); await wait(70); assert.equal(await evaluate(cdp, `document.documentElement.scrollWidth>document.documentElement.clientWidth||document.body.scrollWidth>document.body.clientWidth`), false, `${route} overflow`); }
    console.log(JSON.stringify(results)); console.log('immersive Korean world responsive: P58 hub, 360-1920 dark layout, city, roles, mission library, survival, story, culture, readiness and progress map passed'); cdp.close();
  } finally { browser.kill(); await wait(200); if (path.resolve(profile).startsWith(path.resolve(os.tmpdir()))) fs.rmSync(profile, { recursive: true, force: true, maxRetries: 8, retryDelay: 100 }); }
})().catch((error) => { console.error(error); process.exitCode = 1; });
