/* Real-browser P41 QA: node tests/learning-science-responsive.browser.js [url] */
const assert = require('node:assert/strict');
const childProcess = require('node:child_process');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

const candidates = ['C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe', 'C:\\Program Files\\Microsoft\\Edge\\Application\\msedge.exe'];
const edge = candidates.find((candidate) => fs.existsSync(candidate)); if (!edge) throw new Error('Microsoft Edge is required for responsive browser QA.');
const baseUrl = process.argv[2] || 'http://127.0.0.1:4173/'; const port = 10840 + Math.floor(Math.random() * 60); const profile = path.join(os.tmpdir(), `klearn-p41-browser-${process.pid}`);
const browser = childProcess.spawn(edge, ['--headless=new', `--remote-debugging-port=${port}`, `--user-data-dir=${profile}`, '--disable-gpu', '--no-first-run', '--no-default-browser-check', 'about:blank'], { stdio: 'ignore', windowsHide: true });
const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
async function json(url, options) { const response = await fetch(url, options); if (!response.ok) throw new Error(`${response.status} ${url}`); return response.json(); }
async function connect(url) { const socket = new WebSocket(url); let id = 0; const pending = new Map(); await new Promise((resolve, reject) => { socket.onopen = resolve; socket.onerror = reject; }); socket.onmessage = (event) => { const message = JSON.parse(event.data); const request = pending.get(message.id); if (!request) return; pending.delete(message.id); message.error ? request.reject(new Error(message.error.message)) : request.resolve(message.result); }; return { send(method, params = {}) { return new Promise((resolve, reject) => { const next = ++id; pending.set(next, { resolve, reject }); socket.send(JSON.stringify({ id: next, method, params })); }); }, close() { socket.close(); } }; }
async function evaluate(cdp, expression) { const output = await cdp.send('Runtime.evaluate', { expression, returnByValue: true, awaitPromise: true }); if (output.exceptionDetails) throw new Error(output.exceptionDetails.exception?.description || output.exceptionDetails.text); return output.result.value; }
async function until(cdp, expression, attempts = 100) { for (let attempt = 0; attempt < attempts; attempt += 1) { if (await evaluate(cdp, expression)) return true; await wait(100); } return false; }

(async () => {
  try {
    let version; for (let attempt = 0; attempt < 50 && !version; attempt += 1) { try { version = await json(`http://127.0.0.1:${port}/json/version`); } catch (_) { await wait(100); } } if (!version) throw new Error('Could not start Edge.');
    const target = await json(`http://127.0.0.1:${port}/json/new?${encodeURIComponent(baseUrl)}`, { method: 'PUT' }); const cdp = await connect(target.webSocketDebuggerUrl); await cdp.send('Page.enable'); await cdp.send('Runtime.enable'); assert.equal(await until(cdp, `location.origin !== 'null' && document.readyState === 'complete'`), true, 'page did not load');
    const timestamp = new Date().toISOString(); const old = new Date(Date.now() - 45 * 86400000).toISOString(); const user = { id: 'p41-qa', fullName: 'P41 Learner', email: 'p41@local.test', level: 'TOPIK 1', studyMinutesPerDay: 30, onboardingCompleted: true, createdAt: timestamp };
    const cards = [{ wordId: 'word-school', id: 'word-school', korean: '학교', meaningVi: 'trường học', mastery: 80, correctCount: 5, wrongCount: 2, reviewCount: 7, intervalDays: 5, lastReviewed: old, nextReview: old, difficulty: 'hard' }];
    const history = [{ id: 'p1', percentage: 86, completedAt: timestamp, durationSeconds: 600, skillBreakdown: { grammar: 78 } }, { id: 'p2', percentage: 82, completedAt: old, durationSeconds: 540, skillBreakdown: { grammar: 74 } }, { id: 'p3', percentage: 88, completedAt: old, durationSeconds: 520, skillBreakdown: { grammar: 80 } }];
    await evaluate(cdp, `(() => { localStorage.setItem('klearn_users', ${JSON.stringify(JSON.stringify([user]))}); localStorage.setItem('klearn_session', ${JSON.stringify(JSON.stringify({ userId: user.id, createdAt: timestamp }))}); localStorage.setItem('klearn_progress', ${JSON.stringify(JSON.stringify({ [user.id]: { skills: { reading: 75, vocabulary: 70, grammar: 60, writing: 45 }, stats: { streak: 2 }, lessonProgress: {}, daily: { date: timestamp.slice(0,10), tasks: {} } } }))}); localStorage.setItem('klearn_srs', ${JSON.stringify(JSON.stringify({ [user.id]: cards }))}); localStorage.setItem('klearn_practice_history', ${JSON.stringify(JSON.stringify({ [user.id]: history }))}); localStorage.setItem('klearn_errors', ${JSON.stringify(JSON.stringify({ [user.id]: [{ id:'particle-error', question:'은/는 và 이/가', mistake:'이/가', correction:'은/는', count:3 }] }))}); localStorage.setItem('klearn_settings', ${JSON.stringify(JSON.stringify({ users: { [user.id]: { theme: 'dark', language: 'vi' } } }))}); location.hash='learning-science'; location.reload(); })()`);
    assert.equal(await until(cdp, `Boolean(window.LearningScienceEngine && window.LearningScienceContentService?.hydrate && document.querySelector('.ls-shell'))`), true, 'P41 Learning Science did not render');
    assert.equal(await until(cdp, `window.KLEARN_APP.state.learningScienceRuntime?.content?.modelVersion === 'p41-heuristic-v1'`), true, 'P41 content did not hydrate');
    const results = [];
    for (const width of [360, 768, 1024, 1440, 1920]) {
      await cdp.send('Emulation.setDeviceMetricsOverride', { width, height: 1100, deviceScaleFactor: 1, mobile: false }); await wait(100);
      const metrics = await evaluate(cdp, `(() => { const app=document.getElementById('app'),nav=document.getElementById('bottomNav');const rect=(node)=>{const r=node?.getBoundingClientRect();return r?{left:r.left,width:r.width,right:r.right}:null};return{dark:document.documentElement.dataset.theme==='dark',overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth,bodyOverflow:document.body.scrollWidth>document.body.clientWidth,app:rect(app),nav:rect(nav),scoreColumns:getComputedStyle(document.querySelector('.ls-score-grid')).gridTemplateColumns.split(' ').length,minTouch:Math.min(...[...document.querySelectorAll('.ls-action-grid button,.ls-plan button')].map((node)=>node.getBoundingClientRect().height))};})()`);
      assert.equal(metrics.dark, true, `dark mode missing at ${width}px`); assert.equal(metrics.overflow, false, `html overflow at ${width}px`); assert.equal(metrics.bodyOverflow, false, `body overflow at ${width}px`); assert.ok(metrics.minTouch >= 44, `touch target too small at ${width}px`);
      if (width >= 1024) { assert.ok(metrics.nav.width >= 240 && metrics.nav.width <= 280, `sidebar invalid at ${width}px`); assert.ok(metrics.app.left >= 240, `content overlaps sidebar at ${width}px`); } else assert.ok(metrics.app.left < 2, `compact content offset at ${width}px`);
      assert.equal(metrics.scoreColumns, width <= 390 ? 1 : width <= 900 ? 2 : 4, `score grid invalid at ${width}px`); results.push({ width, columns: metrics.scoreColumns, overflow: metrics.overflow });
    }
    await cdp.send('Emulation.setDeviceMetricsOverride', { width: 360, height: 1100, deviceScaleFactor: 1, mobile: false }); await evaluate(cdp, `window.KLEARN_APP.setView('active-recall')`); assert.equal(await until(cdp, `Boolean(document.getElementById('activeRecallForm'))`), true, 'active recall did not open');
    assert.equal(await evaluate(cdp, `document.querySelector('.ls-recall article').innerText.includes('trường học')`), false, 'answer revealed before submission');
    await evaluate(cdp, `(() => { const form=document.getElementById('activeRecallForm'); form.elements.response.value=window.ActiveRecallService.current().answer; form.requestSubmit(); })()`); assert.equal(await until(cdp, `Boolean(document.querySelector('.ls-reveal.correct'))`), true, 'active recall feedback missing');
    assert.equal(await evaluate(cdp, `JSON.stringify(window.KLEARN_APP.state.srsData[0].lastResult).includes('trường học')`), false, 'raw answer persisted in SRS');
    await evaluate(cdp, `window.KLEARN_APP.setView('interleaved-practice')`); assert.equal(await until(cdp, `document.querySelectorAll('.ls-mix span').length > 0`), true, 'interleaved queue missing'); assert.equal(await evaluate(cdp, `document.documentElement.scrollWidth>document.documentElement.clientWidth`), false, 'P41 views overflow at 360px');
    console.log(JSON.stringify(results)); console.log('learning science responsive: dark mode, 360-1920 layout, active recall answer privacy and interleaved queue passed'); cdp.close();
  } finally { browser.kill(); await wait(200); if (path.resolve(profile).startsWith(path.resolve(os.tmpdir()))) fs.rmSync(profile, { recursive: true, force: true, maxRetries: 8, retryDelay: 100 }); }
})().catch((error) => { console.error(error); process.exitCode = 1; });
