/* Real-browser P69 QA: node tests/p69-education-ecosystem-responsive.browser.js [url] */
const assert = require('node:assert/strict');
const childProcess = require('node:child_process');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

const edge = [path.join(process.env['ProgramFiles(x86)'] || '', 'Microsoft', 'Edge', 'Application', 'msedge.exe'), path.join(process.env.ProgramFiles || '', 'Microsoft', 'Edge', 'Application', 'msedge.exe'), path.join(process.env.LOCALAPPDATA || '', 'Microsoft', 'Edge', 'Application', 'msedge.exe')].find((candidate) => candidate && fs.existsSync(candidate));
if (!edge) throw new Error('Microsoft Edge is required for responsive browser QA.');
const baseUrl = process.argv[2] || 'http://127.0.0.1:4173/'; const port = 10910 + Math.floor(Math.random() * 70); const profile = path.join(os.tmpdir(), `klearn-p69-browser-${process.pid}`);
const browser = childProcess.spawn(edge, ['--headless=new', `--remote-debugging-port=${port}`, `--user-data-dir=${profile}`, '--disable-gpu', '--no-first-run', '--no-default-browser-check', 'about:blank'], { stdio: 'ignore', windowsHide: true });
const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
async function json(url, options) { const response = await fetch(url, options); if (!response.ok) throw new Error(`${response.status} ${url}`); return response.json(); }
async function connect(url) { const socket = new WebSocket(url); let id = 0; const pending = new Map(); await new Promise((resolve, reject) => { socket.onopen = resolve; socket.onerror = reject; }); socket.onmessage = (event) => { const message = JSON.parse(event.data); const request = pending.get(message.id); if (!request) return; pending.delete(message.id); message.error ? request.reject(new Error(message.error.message)) : request.resolve(message.result); }; return { send(method, params = {}) { return new Promise((resolve, reject) => { const next = ++id; pending.set(next, { resolve, reject }); socket.send(JSON.stringify({ id: next, method, params })); }); }, close() { socket.close(); } }; }
async function evaluate(cdp, expression) { const output = await cdp.send('Runtime.evaluate', { expression, returnByValue: true, awaitPromise: true }); if (output.exceptionDetails) throw new Error(output.exceptionDetails.exception?.description || output.exceptionDetails.text); return output.result.value; }
async function until(cdp, expression, attempts = 160) { for (let attempt = 0; attempt < attempts; attempt += 1) { if (await evaluate(cdp, expression)) return true; await wait(100); } return false; }

(async () => {
  try {
    let version; for (let attempt = 0; attempt < 50 && !version; attempt += 1) { try { version = await json(`http://127.0.0.1:${port}/json/version`); } catch (_) { await wait(100); } }
    if (!version) throw new Error('Could not start Edge.');
    const target = await json(`http://127.0.0.1:${port}/json/new?${encodeURIComponent(baseUrl)}`, { method: 'PUT' }); const cdp = await connect(target.webSocketDebuggerUrl); await cdp.send('Page.enable'); await cdp.send('Runtime.enable');
    assert.equal(await until(cdp, `location.origin !== 'null' && document.readyState === 'complete'`), true, 'page did not load');
    const timestamp = new Date().toISOString(); const user = { id: 'teacher-p69', fullName: 'Teacher P69', email: 'teacher@local.test', level: 'TOPIK 2', onboardingCompleted: true, createdAt: timestamp };
    await evaluate(cdp, `(() => { const user=${JSON.stringify(user)}; localStorage.clear(); localStorage.setItem('klearn_users',JSON.stringify([user])); localStorage.setItem('klearn_session',JSON.stringify({userId:user.id,createdAt:${JSON.stringify(timestamp)}})); localStorage.setItem('klearn_progress',JSON.stringify({[user.id]:{p69RegressionMarker:'keep-me',skills:{},stats:{},lessonProgress:{}}})); localStorage.setItem('klearn_settings',JSON.stringify({schemaVersion:13,users:{[user.id]:{theme:'dark',language:'vi'}}})); location.hash='education-ecosystem'; location.reload(); })()`);
    assert.equal(await until(cdp, `Boolean(window.RoleArchitectureService && document.querySelector('.p69-role-grid'))`), true, 'P69 route did not load');
    await evaluate(cdp, `window.KLEARN_APP.AccessControlService.role=()=> 'teacher'; window.KLEARN_APP.render()`); await wait(100);
    assert.equal(await evaluate(cdp, `document.body.textContent.includes('Teacher · phạm vi assigned_classes')`), true, 'teacher role view missing');

    const setup = await evaluate(cdp, `(() => { const org=window.OrganizationAccountService.create({name:'Browser Center',type:'center'}); const classroom=window.ClassroomLifecycleService.create({organizationId:org.id,name:'TOPIK Browser',code:'BROWSER'}); const student=window.ClassroomLifecycleService.inviteStudent({classId:classroom.id,studentId:'student-p69',displayName:'Minh'}); const course=window.ClassroomLifecycleService.assignCourse({classId:classroom.id,courseId:'course-1'}); const assignment=window.ClassroomLifecycleService.createAssignment({classId:classroom.id,studentId:'student-p69',title:'Lesson 10',type:'lesson',contentId:'lesson-10'}); const assessment=window.EducationAssessmentService.create({classId:classroom.id,title:'Checkpoint',type:'vocabulary',questions:[{id:'q1',skill:'vocabulary',prompt:'학교?',options:['trường học','bệnh viện'],answer:'trường học'}]}); return {org:org.id,classId:classroom.id,student:student.studentId,course:Boolean(course),assignmentId:assignment.id,assessmentId:assessment.id,noConsent:window.StudentProgressSharingService.read('student-p69',classroom.id)===null}; })()`);
    assert.equal(setup.course, true); assert.equal(setup.noConsent, true);

    const studentFlow = await evaluate(cdp, `(() => { window.KLEARN_APP.state.currentUser={id:'student-p69',fullName:'Minh',onboardingCompleted:true}; window.KLEARN_APP.AccessControlService.role=()=> 'student'; const consent=window.ProgressConsentService.grant({classId:${JSON.stringify(setup.classId)},scopes:['progress','skills','attendance','weakness','topik_readiness']}); const shared=window.StudentProgressSharingService.publish(${JSON.stringify(setup.classId)},{attendance:90,progress:72,lessonCompletion:75,vocabularyMastery:80,grammarWeakness:['은/는'],topikReadiness:66,sessions7d:1,scoreTrend:-12,password:'hidden',journal:'private'}); const assignment=window.ClassroomLifecycleService.complete(${JSON.stringify(setup.assignmentId)}); const assessment=window.EducationAssessmentService.publicAssessment(${JSON.stringify(setup.assessmentId)}); const attempt=window.EducationAssessmentService.submit(${JSON.stringify(setup.assessmentId)},{q1:'trường học'}); return {consent:Boolean(consent),shared,assignment:Boolean(assignment),answerVisible:'answer' in assessment.questions[0],score:attempt.score}; })()`);
    assert.equal(studentFlow.consent, true); assert.equal(studentFlow.assignment, true); assert.equal(studentFlow.answerVisible, false); assert.equal(studentFlow.score, 100); assert.equal('password' in studentFlow.shared, false); assert.equal('journal' in studentFlow.shared, false);

    const teacherFlow = await evaluate(cdp, `(() => { window.KLEARN_APP.state.currentUser=${JSON.stringify(user)}; window.KLEARN_APP.AccessControlService.role=()=> 'teacher'; const overview=window.TeacherInsightService.classOverview(${JSON.stringify(setup.classId)}); const report=window.SchoolReportService.student('student-p69',${JSON.stringify(setup.classId)}); return {overview,report,results:window.EducationAssessmentService.results(${JSON.stringify(setup.assessmentId)}).length}; })()`);
    assert.equal(teacherFlow.overview.students, 1); assert.equal(teacherFlow.overview.sharedStudents, 1); assert.equal(teacherFlow.overview.riskStudents.length, 1); assert.equal(teacherFlow.report.progress, 72); assert.equal(teacherFlow.results, 1); assert.equal(JSON.stringify(teacherFlow.report).includes('private'), false);

    const results = [];
    for (const width of [360, 768, 1024, 1440, 1920]) {
      await cdp.send('Emulation.setDeviceMetricsOverride', { width, height: 1100, deviceScaleFactor: 1, mobile: false }); await evaluate(cdp, `window.KLEARN_APP.state.currentView='education-ecosystem'; location.hash='education-ecosystem'; window.KLEARN_APP.render()`); await wait(100);
      const metrics = await evaluate(cdp, `(() => { const rect=(node)=>{const value=node?.getBoundingClientRect();return value?{left:value.left,width:value.width}:null}; return {dark:document.documentElement.dataset.theme==='dark',htmlOverflow:document.documentElement.scrollWidth>document.documentElement.clientWidth,bodyOverflow:document.body.scrollWidth>document.body.clientWidth,app:rect(document.getElementById('app')),nav:rect(document.getElementById('bottomNav')),grid:rect(document.querySelector('.p69-role-grid'))}; })()`);
      assert.equal(metrics.dark, true, `dark mode missing at ${width}px`); assert.equal(metrics.htmlOverflow, false, `html overflow at ${width}px`); assert.equal(metrics.bodyOverflow, false, `body overflow at ${width}px`); assert.ok(metrics.grid.width <= width, `role grid exceeds ${width}px`);
      if (width >= 1024) { assert.ok(metrics.nav.width >= 240 && metrics.nav.width <= 280, `sidebar invalid at ${width}px: ${JSON.stringify(metrics)}`); assert.ok(metrics.app.left >= 240, `content overlaps sidebar at ${width}px: ${JSON.stringify(metrics)}`); } else assert.ok(metrics.app.left < 2, `compact offset at ${width}px: ${JSON.stringify(metrics)}`);
      results.push({ width, overflow: metrics.htmlOverflow, sidebar: Math.round(metrics.nav.width) });
    }

    const revoked = await evaluate(cdp, `(() => { window.KLEARN_APP.state.currentUser={id:'student-p69',fullName:'Minh',onboardingCompleted:true}; window.KLEARN_APP.AccessControlService.role=()=> 'student'; window.ProgressConsentService.revoke(${JSON.stringify(setup.classId)}); window.KLEARN_APP.state.currentUser=${JSON.stringify(user)}; window.KLEARN_APP.AccessControlService.role=()=> 'teacher'; return window.StudentProgressSharingService.read('student-p69',${JSON.stringify(setup.classId)})===null; })()`);
    assert.equal(revoked, true, 'consent revocation did not remove teacher access');
    assert.equal(await evaluate(cdp, `localStorage.getItem('klearn_progress').includes('keep-me')`), true, 'learning progress changed');
    console.log(JSON.stringify(results)); console.log('P69 browser: class/invite/course/assignment/assessment/student completion/teacher report/consent revoke, 360-1920 responsive, dark, no overflow and progress isolation passed'); cdp.close();
  } finally { browser.kill(); await wait(200); fs.rmSync(profile, { recursive: true, force: true, maxRetries: 8, retryDelay: 100 }); }
})().catch((error) => { console.error(error); process.exitCode = 1; });
