/* Real-browser P70 QA: node tests/p70-global-language-responsive.browser.js [url] */
const assert = require('node:assert/strict');
const childProcess = require('node:child_process');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const edge = [path.join(process.env['ProgramFiles(x86)'] || '', 'Microsoft', 'Edge', 'Application', 'msedge.exe'), path.join(process.env.ProgramFiles || '', 'Microsoft', 'Edge', 'Application', 'msedge.exe'), path.join(process.env.LOCALAPPDATA || '', 'Microsoft', 'Edge', 'Application', 'msedge.exe')].find((candidate) => candidate && fs.existsSync(candidate));
if (!edge) throw new Error('Microsoft Edge is required for P70 responsive QA.');
const baseUrl = process.argv[2] || 'http://127.0.0.1:4173/'; const port = 11020 + Math.floor(Math.random() * 70); const profile = path.join(os.tmpdir(), `klearn-p70-browser-${process.pid}`);
const browser = childProcess.spawn(edge, ['--headless=new', `--remote-debugging-port=${port}`, `--user-data-dir=${profile}`, '--disable-gpu', '--no-first-run', '--no-default-browser-check', 'about:blank'], { stdio: 'ignore', windowsHide: true });
const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
async function json(url, options) { const response = await fetch(url, options); if (!response.ok) throw new Error(`${response.status} ${url}`); return response.json(); }
async function connect(url) { const socket = new WebSocket(url); let id = 0; const pending = new Map(); await new Promise((resolve, reject) => { socket.onopen = resolve; socket.onerror = reject; }); socket.onmessage = (event) => { const message = JSON.parse(event.data); const request = pending.get(message.id); if (!request) return; pending.delete(message.id); message.error ? request.reject(new Error(message.error.message)) : request.resolve(message.result); }; return { send(method, params = {}) { return new Promise((resolve, reject) => { const next = ++id; pending.set(next, { resolve, reject }); socket.send(JSON.stringify({ id: next, method, params })); }); }, close() { socket.close(); } }; }
async function evaluate(cdp, expression) { const output = await cdp.send('Runtime.evaluate', { expression, returnByValue: true, awaitPromise: true }); if (output.exceptionDetails) throw new Error(output.exceptionDetails.exception?.description || output.exceptionDetails.text); return output.result.value; }
async function until(cdp, expression, attempts = 160) { for (let attempt = 0; attempt < attempts; attempt += 1) { if (await evaluate(cdp, expression)) return true; await wait(100); } return false; }

(async () => {
  try {
    let version; for (let attempt = 0; attempt < 50 && !version; attempt += 1) { try { version = await json(`http://127.0.0.1:${port}/json/version`); } catch (_) { await wait(100); } }
    if (!version) throw new Error('Could not start Edge.');
    const target = await json(`http://127.0.0.1:${port}/json/new?${encodeURIComponent(baseUrl)}`, { method: 'PUT' }); const cdp = await connect(target.webSocketDebuggerUrl); await cdp.send('Page.enable'); await cdp.send('Runtime.enable');
    assert.equal(await until(cdp, `document.readyState === 'complete'`), true);
    const timestamp = new Date().toISOString(); const user = { id: 'p70-browser', fullName: 'Global Learner', email: 'global@local.test', level: 'TOPIK 1', onboardingCompleted: true, createdAt: timestamp };
    await evaluate(cdp, `(() => { const user=${JSON.stringify(user)}; localStorage.clear(); localStorage.setItem('klearn_users',JSON.stringify([user])); localStorage.setItem('klearn_session',JSON.stringify({userId:user.id,createdAt:${JSON.stringify(timestamp)}})); localStorage.setItem('klearn_progress',JSON.stringify({[user.id]:{p70RegressionMarker:'keep-me',skills:{},stats:{},lessonProgress:{}}})); localStorage.setItem('klearn_settings',JSON.stringify({schemaVersion:13,users:{[user.id]:{theme:'dark',language:'vi'}}})); location.hash='global-language-platform'; location.reload(); })()`);
    assert.equal(await until(cdp, `Boolean(window.MultiLanguageProfileService && document.querySelector('.glc-gateway'))`), true, 'P70 route did not load');
    assert.equal(await until(cdp, `window.GlobalLanguageCoreV2Config?.get?.().searchEntries?.length === 3`), true, 'P70 reviewed configuration did not load');
    const flow = await evaluate(cdp, `(() => { window.MultiLanguageOnboardingService.complete({nativeLanguage:'vi',targetLanguage:'ko',goal:'TOPIK 2',level:'TOPIK 1'}); window.MultiLanguageOnboardingService.complete({nativeLanguage:'vi',targetLanguage:'ja',goal:'JLPT N3',level:'N5'}); window.MultiLanguageProfileService.setProgress('ko',{overall:75,skills:{grammar:62},weakSkills:['grammar']}); window.MultiLanguageProfileService.setProgress('ja',{overall:25,skills:{writing:20},weakSkills:['writing']}); const ko=window.UniversalSRSService.add('ko',{id:'topic-particle',itemType:'grammar',prompt:'은/는',answer:'topic'}); const ja=window.UniversalSRSService.add('ja',{id:'日',itemType:'kanji',prompt:'日',answer:'day'}); window.UniversalMasteryService.record('ko','lesson-shared',88); window.UniversalMasteryService.record('ja','lesson-shared',31); window.MultiLanguageProfileService.switch('ja'); return {active:window.MultiLanguageProfileService.active(),koProgress:window.MultiLanguageProfileService.language('ko').progress.overall,jaProgress:window.MultiLanguageProfileService.language('ja').progress.overall,koCards:window.UniversalSRSService.cards('ko').length,jaCards:window.UniversalSRSService.cards('ja').length,koMastery:window.UniversalMasteryService.get('ko','lesson-shared').score,jaMastery:window.UniversalMasteryService.get('ja','lesson-shared').score,ai:window.AILanguageContextService.build('ja'),search:window.MultiLanguageSearchService.search('xin chào').length,loaded:window.LanguagePackRegistry.loaded().length,ko:Boolean(ko),ja:Boolean(ja)}; })()`);
    assert.equal(flow.active, 'ja'); assert.equal(flow.koProgress, 75); assert.equal(flow.jaProgress, 25); assert.ok(flow.koCards >= 2); assert.equal(flow.jaCards, 1); assert.equal(flow.koMastery, 88); assert.equal(flow.jaMastery, 31); assert.equal(flow.ai.nativeLanguage, 'vi'); assert.equal(flow.ai.targetLanguage, 'ja'); assert.equal(flow.search, 3); assert.equal(flow.loaded, 0); assert.equal(flow.ko && flow.ja, true);
    const merge = await evaluate(cdp, `(() => { const local={updatedAt:'2026-09-12T10:00:00Z',languages:{ko:{languageId:'ko',updatedAt:'2026-09-12T10:00:00Z',progress:{overall:80},srs:[{id:'ko:vocabulary:a',updatedAt:'2026-09-12T10:00:00Z'}]},ja:{languageId:'ja',updatedAt:'2026-09-12T09:00:00Z',progress:{overall:20},srs:[]}}}; const remote={updatedAt:'2026-09-12T09:30:00Z',languages:{ko:{languageId:'ko',updatedAt:'2026-09-12T09:00:00Z',progress:{overall:40},srs:[]},ja:{languageId:'ja',updatedAt:'2026-09-12T09:30:00Z',progress:{overall:35},srs:[{id:'ja:kanji:b',updatedAt:'2026-09-12T09:30:00Z'}]}}}; return window.KLEARN_APP.CloudSyncService.mergeLanguageLearningState(local,remote); })()`);
    assert.equal(merge.languages.ko.progress.overall, 80); assert.equal(merge.languages.ja.progress.overall, 35); assert.equal(merge.languages.ko.srs.length, 1); assert.equal(merge.languages.ja.srs.length, 1);
    await evaluate(cdp, `window.KLEARN_APP.state.globalQuery='xin chào'; window.KLEARN_APP.setView('search')`); await wait(150);
    assert.equal(await evaluate(cdp, `document.body.textContent.includes('こんにちは') && document.body.textContent.includes('你好') && document.body.textContent.includes('안녕하세요')`), true, 'header Global Search did not include multiple languages');
    const results = [];
    for (const width of [360, 768, 1024, 1440, 1920]) {
      await cdp.send('Emulation.setDeviceMetricsOverride', { width, height: 1100, deviceScaleFactor: 1, mobile: false }); await evaluate(cdp, `window.KLEARN_APP.setView('global-language-platform')`); await wait(100);
      const metrics = await evaluate(cdp, `(() => { const rect=(node)=>{const value=node?.getBoundingClientRect();return value?{left:value.left,width:value.width}:null}; return {dark:document.documentElement.dataset.theme==='dark',htmlOverflow:document.documentElement.scrollWidth>document.documentElement.clientWidth,bodyOverflow:document.body.scrollWidth>document.body.clientWidth,app:rect(document.getElementById('app')),nav:rect(document.getElementById('bottomNav')),gateway:rect(document.querySelector('.glc-gateway'))}; })()`);
      assert.equal(metrics.dark, true, `dark mode missing at ${width}px`); assert.equal(metrics.htmlOverflow, false, `html overflow at ${width}px`); assert.equal(metrics.bodyOverflow, false, `body overflow at ${width}px`); assert.ok(metrics.gateway?.width <= width, `gateway exceeds ${width}px`);
      if (width >= 1024) { assert.ok(metrics.nav.width >= 240 && metrics.nav.width <= 280, `sidebar invalid at ${width}px`); assert.ok(metrics.app.left >= 240, `content overlaps sidebar at ${width}px`); } else assert.ok(metrics.app.left < 2, `compact offset at ${width}px`);
      results.push({ width, sidebar: Math.round(metrics.nav.width), overflow: metrics.htmlOverflow });
    }
    assert.equal(await evaluate(cdp, `localStorage.getItem('klearn_progress').includes('keep-me')`), true, 'Korean learning progress changed');
    console.log(JSON.stringify(results)); console.log('P70 browser: Korean/Japanese profiles, isolated progress/SRS/mastery, correct AI context, lazy packs, search, dark mode and 360-1920 responsive passed'); cdp.close();
  } finally { browser.kill(); await wait(200); fs.rmSync(profile, { recursive: true, force: true, maxRetries: 8, retryDelay: 100 }); }
})().catch((error) => { console.error(error); process.exitCode = 1; });
