/* Real-browser P71C QA: node tests/p71c-content-science-responsive.browser.js [url] */
const assert = require('node:assert/strict');
const childProcess = require('node:child_process');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

const edge = [path.join(process.env['ProgramFiles(x86)'] || '', 'Microsoft', 'Edge', 'Application', 'msedge.exe'), path.join(process.env.ProgramFiles || '', 'Microsoft', 'Edge', 'Application', 'msedge.exe'), path.join(process.env.LOCALAPPDATA || '', 'Microsoft', 'Edge', 'Application', 'msedge.exe')].find((candidate) => candidate && fs.existsSync(candidate));
if (!edge) throw new Error('Microsoft Edge is required for P71C responsive QA.');
const baseUrl = process.argv[2] || 'http://127.0.0.1:4173/'; const port = 11300 + Math.floor(Math.random() * 70); const profile = path.join(os.tmpdir(), `klearn-p71c-browser-${process.pid}`);
const browser = childProcess.spawn(edge, ['--headless=new', `--remote-debugging-port=${port}`, `--user-data-dir=${profile}`, '--disable-gpu', '--no-first-run', '--no-default-browser-check', 'about:blank'], { stdio: 'ignore', windowsHide: true });
const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
async function json(url, options) { const response = await fetch(url, options); if (!response.ok) throw new Error(`${response.status} ${url}`); return response.json(); }
async function connect(url) { const socket = new WebSocket(url); let id = 0; const pending = new Map(); await new Promise((resolve, reject) => { socket.onopen = resolve; socket.onerror = reject; }); socket.onmessage = (event) => { const message = JSON.parse(event.data); const request = pending.get(message.id); if (!request) return; pending.delete(message.id); message.error ? request.reject(new Error(message.error.message)) : request.resolve(message.result); }; return { send(method, params = {}) { return new Promise((resolve, reject) => { const next = ++id; pending.set(next, { resolve, reject }); socket.send(JSON.stringify({ id: next, method, params })); }); }, close() { socket.close(); } }; }
async function evaluate(cdp, expression) { const output = await cdp.send('Runtime.evaluate', { expression, returnByValue: true, awaitPromise: true }); if (output.exceptionDetails) throw new Error(output.exceptionDetails.exception?.description || output.exceptionDetails.text); return output.result.value; }
async function until(cdp, expression, attempts = 180) { for (let attempt = 0; attempt < attempts; attempt += 1) { if (await evaluate(cdp, expression)) return true; await wait(100); } return false; }

(async () => {
  try {
    let version; for (let attempt = 0; attempt < 50 && !version; attempt += 1) { try { version = await json(`http://127.0.0.1:${port}/json/version`); } catch (_) { await wait(100); } }
    if (!version) throw new Error('Could not start Edge.');
    const target = await json(`http://127.0.0.1:${port}/json/new?${encodeURIComponent(baseUrl)}`, { method: 'PUT' }); const cdp = await connect(target.webSocketDebuggerUrl); await cdp.send('Page.enable'); await cdp.send('Runtime.enable');
    assert.equal(await until(cdp, `document.readyState === 'complete'`), true);
    const oldDate = new Date(Date.now() - 35 * 86400000).toISOString(); const timestamp = new Date().toISOString();
    const user = { id: 'p71c-browser', fullName: 'Content Science Learner', email: 'private@local.test', currentTopikLevel: 1, targetTopikLevel: 2, studyMinutesPerDay: 20, onboardingCompleted: true, createdAt: oldDate };
    const progress = { p71cRegressionMarker: 'keep-me', lessonProgress: { 'lesson-first-introduction': { completed: true, score: 78, masteryScore: 82, completedAt: oldDate, updatedAt: oldDate } }, skills: { speaking: 55, listening: 48 }, stats: { streak: 2 } };
    const srs = [{ wordId: 'freq-학교', korean: '학교', mastery: 80, reviewCount: 5, correctCount: 4, wrongCount: 1, activatedAt: oldDate, lastReviewed: timestamp }];
    await evaluate(cdp, `(() => { const user=${JSON.stringify(user)}; localStorage.clear(); localStorage.setItem('klearn_users',JSON.stringify([user])); localStorage.setItem('klearn_session',JSON.stringify({userId:user.id,createdAt:${JSON.stringify(timestamp)}})); localStorage.setItem('klearn_progress',JSON.stringify({[user.id]:${JSON.stringify(progress)}})); localStorage.setItem('klearn_srs',JSON.stringify({[user.id]:${JSON.stringify(srs)}})); localStorage.setItem('klearn_settings',JSON.stringify({schemaVersion:13,users:{[user.id]:{theme:'dark',language:'vi',privacy:{telemetry:true}}}})); location.hash='content-science'; location.reload(); })()`);
    assert.equal(await until(cdp, `Boolean(window.ContentScienceSystem && document.querySelector('.p71c-metrics'))`), true, 'P71C route did not load');
    const flow = await evaluate(cdp, `(()=>{ const verified=window.VerifiedContentService.metadata('lesson-cafe-order'); const unknown=window.VerifiedContentService.metadata('missing'); window.ContentEffectivenessService.record('grammar-topic-particle','remembered',{score:68,outcome:'remembered',signature:'browser-recall'}); window.ContentEffectivenessService.record('grammar-topic-particle','used',{score:88,outcome:'completed',signature:'browser-use'}); const summary=window.ContentEffectivenessService.summary('grammar-topic-particle'); const retention=window.ContentRetentionAnalyticsService.report(); const curve=window.LearningCurveService.points(); const report=window.ContentScienceFeedbackService.submit({contentId:'lesson-cafe-order',reportType:'broken_audio',message:'Audio không phát trong bài kiểm tra.'}); const disabled=window.AnonymousLearningStatisticsService.payload('grammar-topic-particle'); window.UserResearchService.consent.set('granted'); const aggregate=window.AnonymousLearningStatisticsService.payload('grammar-topic-particle'); const beforeA={events:window.ContentEffectivenessService.events().length,reports:window.ContentScienceFeedbackService.all().length}; const original=window.KLEARN_APP.state.currentUser; window.KLEARN_APP.state.currentUser={id:'p71c-other',currentTopikLevel:0}; const isolated={events:window.ContentEffectivenessService.events().length,reports:window.ContentScienceFeedbackService.all().length}; window.KLEARN_APP.state.currentUser=original; return {verified:verified.verified,quality:verified.quality.score,dimensions:Object.keys(verified.quality.dimensions).length,unknown:unknown.verified,summary,retention,curve:curve.length,reportType:report.reportType,disabled:disabled.status,aggregate:aggregate.payload,isolated,beforeA}; })()`);
    assert.equal(flow.verified, true); assert.equal(flow.quality, 95); assert.equal(flow.dimensions, 4); assert.equal(flow.unknown, false); assert.equal(flow.summary.remembered, 1); assert.equal(flow.summary.used, 1); assert.ok(flow.retention.vocabulary.score >= 1); assert.ok(flow.curve >= 2); assert.equal(flow.reportType, 'broken_audio'); assert.equal(flow.disabled, 'disabled'); assert.deepEqual(flow.isolated, { events: 0, reports: 0 }); assert.ok(flow.beforeA.events > 0 && flow.beforeA.reports === 1);
    const aggregateText = JSON.stringify(flow.aggregate); for (const forbidden of ['p71c-browser', 'private@local.test', 'password', 'token', 'audio', 'transcript', 'journal', 'deviceId']) assert.equal(aggregateText.includes(forbidden), false, `anonymous payload leaked ${forbidden}`);

    const results = [];
    for (const width of [360, 768, 1024, 1440, 1920]) {
      await cdp.send('Emulation.setDeviceMetricsOverride', { width, height: 1200, deviceScaleFactor: 1, mobile: false }); await evaluate(cdp, `window.KLEARN_APP.setView('content-science')`); await wait(100);
      const metrics = await evaluate(cdp, `(()=>{const rect=(node)=>{const value=node?.getBoundingClientRect();return value?{left:value.left,width:value.width,right:value.right}:null};return{dark:document.documentElement.dataset.theme==='dark',htmlOverflow:document.documentElement.scrollWidth>document.documentElement.clientWidth,bodyOverflow:document.body.scrollWidth>document.body.clientWidth,scrollWidth:document.body.scrollWidth,offenders:[...document.querySelectorAll('*')].map((node)=>({tag:node.tagName,className:String(node.className||''),right:node.getBoundingClientRect().right,width:node.getBoundingClientRect().width})).filter((item)=>item.right>${width}+1).slice(0,8),app:rect(document.getElementById('app')),nav:rect(document.getElementById('bottomNav')),panel:rect(document.querySelector('.p71c-panel')),metrics:rect(document.querySelector('.p71c-metrics'))}})()`);
      if (metrics.bodyOverflow || metrics.htmlOverflow) console.error(JSON.stringify({ width, scrollWidth: metrics.scrollWidth, offenders: metrics.offenders }));
      assert.equal(metrics.dark, true, `dark mode missing at ${width}px`); assert.equal(metrics.htmlOverflow, false, `html overflow at ${width}px`); assert.equal(metrics.bodyOverflow, false, `body overflow at ${width}px`); assert.ok(metrics.panel?.width <= width && metrics.metrics?.width <= width, `P71C content exceeds ${width}px`);
      if (width >= 1024) { assert.ok(metrics.nav.width >= 240 && metrics.nav.width <= 280, `sidebar invalid at ${width}px`); assert.ok(metrics.app.left >= 240, `content overlaps sidebar at ${width}px`); } else assert.ok(metrics.app.left < 2, `compact content offset at ${width}px`);
      results.push({ width, sidebar: Math.round(metrics.nav.width), overflow: metrics.htmlOverflow });
    }
    assert.equal(await evaluate(cdp, `localStorage.getItem('klearn_progress').includes('keep-me') && localStorage.getItem('klearn_srs').includes('freq-학교')`), true, 'existing SRS or progress changed');
    await evaluate(cdp, `location.reload()`); assert.equal(await until(cdp, `Boolean(window.ContentScienceSystem && window.ContentScienceFeedbackService.all().length)`), true, 'P71C evidence did not survive reload');
    assert.equal(await evaluate(cdp, `window.KLEARN_APP.getUserProgress().p71cRegressionMarker==='keep-me' && window.KLEARN_APP.getUserSrs()[0].wordId==='freq-학교'`), true, 'SRS/progress regression after reload');
    console.log(JSON.stringify(results)); console.log('P71C browser: verified metadata, evidence, retention, privacy consent, user isolation, persistence, dark mode and 360-1920 responsive passed'); cdp.close();
  } finally { browser.kill(); await wait(200); fs.rmSync(profile, { recursive: true, force: true, maxRetries: 8, retryDelay: 100 }); }
})().catch((error) => { console.error(error); process.exitCode = 1; });
