/* Real-browser P72A QA: node tests/p72a-engagement-core-responsive.browser.js [url] */
const assert = require('node:assert/strict');
const childProcess = require('node:child_process');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

const edge = [path.join(process.env['ProgramFiles(x86)'] || '', 'Microsoft', 'Edge', 'Application', 'msedge.exe'), path.join(process.env.ProgramFiles || '', 'Microsoft', 'Edge', 'Application', 'msedge.exe'), path.join(process.env.LOCALAPPDATA || '', 'Microsoft', 'Edge', 'Application', 'msedge.exe')].find((candidate) => candidate && fs.existsSync(candidate));
if (!edge) throw new Error('Microsoft Edge is required for P72A responsive QA.');
const baseUrl = process.argv[2] || 'http://127.0.0.1:4173/'; const port = 11400 + Math.floor(Math.random() * 70); const profile = path.join(os.tmpdir(), `klearn-p72a-browser-${process.pid}`);
const browser = childProcess.spawn(edge, ['--headless=new', `--remote-debugging-port=${port}`, `--user-data-dir=${profile}`, '--disable-gpu', '--no-first-run', '--no-default-browser-check', 'about:blank'], { stdio: 'ignore', windowsHide: true });
const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
async function json(url, options) { const response = await fetch(url, options); if (!response.ok) throw new Error(`${response.status} ${url}`); return response.json(); }
async function connect(url) { const socket = new WebSocket(url); let id = 0; const pending = new Map(); await new Promise((resolve, reject) => { socket.onopen = resolve; socket.onerror = reject; }); socket.onmessage = (event) => { const message = JSON.parse(event.data); const request = pending.get(message.id); if (!request) return; pending.delete(message.id); message.error ? request.reject(new Error(message.error.message)) : request.resolve(message.result); }; return { send(method, params = {}) { return new Promise((resolve, reject) => { const next = ++id; pending.set(next, { resolve, reject }); socket.send(JSON.stringify({ id: next, method, params })); }); }, close() { socket.close(); } }; }
async function evaluate(cdp, expression) { const output = await cdp.send('Runtime.evaluate', { expression, returnByValue: true, awaitPromise: true }); if (output.exceptionDetails) throw new Error(output.exceptionDetails.exception?.description || output.exceptionDetails.text); return output.result.value; }
async function until(cdp, expression, attempts = 180) { for (let attempt = 0; attempt < attempts; attempt += 1) { if (await evaluate(cdp, expression)) return true; await wait(100); } return false; }

(async () => {
  try {
    let version; for (let attempt = 0; attempt < 50 && !version; attempt += 1) { try { version = await json(`http://127.0.0.1:${port}/json/version`); } catch (_) { await wait(100); } }
    if (!version) throw new Error('Could not start Edge.');
    const target = await json(`http://127.0.0.1:${port}/json/new?${encodeURIComponent(baseUrl)}`, { method: 'PUT' }); const cdp = await connect(target.webSocketDebuggerUrl); await cdp.send('Page.enable'); await cdp.send('Runtime.enable'); assert.equal(await until(cdp, `location.origin === 'http://127.0.0.1:4173' && document.readyState === 'complete'`), true);
    const now = new Date(); const timestamp = now.toISOString(); const expires = new Date(now.getTime() + 7 * 86400000).toISOString();
    const user = { id: 'p72a-browser', fullName: 'Engagement Learner', email: 'engagement@local.test', level: 'Beginner', currentTopikLevel: 1, targetTopikLevel: 2, studyMinutesPerDay: 20, onboardingCompleted: true, createdAt: timestamp };
    const progress = { p72aRegressionMarker: 'keep-me', lessonProgress: { 'lesson-first-introduction': { completed: true, score: 80, masteryScore: 75, completedAt: timestamp, updatedAt: timestamp } }, pronunciationAttempts: [{ id: 'voice-1', score: 78, createdAt: timestamp }], writingSubmissions: [{ id: 'write-1', preliminaryScore: 68, submittedAt: timestamp }], skills: { vocabulary: 65, grammar: 55, listening: 45, reading: 60, speaking: 62, writing: 54 }, stats: { streak: 4, lessonsCompleted: 1 }, daily: { date: timestamp.slice(0,10), tasks: {} } };
    const srs = [{ wordId: 'freq-학교', korean: '학교', mastery: 80, reviewCount: 5, correctCount: 4, wrongCount: 1, lastReviewed: timestamp }];
    const history = [{ id: 'attempt-1', setId: 't1-basics', setTitle: 'TOPIK 1', percentage: 70, completedAt: timestamp, skillBreakdown: { vocabulary: 70, grammar: 60, listening: 50, reading: 70 }, wrongQuestionIds: [] }];
    await evaluate(cdp, `(() => { const user=${JSON.stringify(user)}; localStorage.clear(); localStorage.setItem('klearn_users',JSON.stringify([user])); localStorage.setItem('klearn_session',JSON.stringify({userId:user.id,createdAt:${JSON.stringify(timestamp)},sessionCreatedAt:${JSON.stringify(timestamp)},sessionExpiresAt:${JSON.stringify(expires)}})); localStorage.setItem('klearn_progress',JSON.stringify({[user.id]:${JSON.stringify(progress)}})); localStorage.setItem('klearn_srs',JSON.stringify({[user.id]:${JSON.stringify(srs)}})); localStorage.setItem('klearn_practice_history',JSON.stringify({[user.id]:${JSON.stringify(history)}})); localStorage.setItem('klearn_settings',JSON.stringify({schemaVersion:13,users:{[user.id]:{theme:'dark',language:'vi',privacy:{cloudSync:true}}}})); location.hash='engagement-center'; location.reload(); })()`);
    assert.equal(await until(cdp, `Boolean(window.EngagementCoreSystem && document.querySelector('.p72-summary'))`), true, 'P72A engagement route did not load');
    const core = await evaluate(cdp, `(() => { const first=window.LearningXPService.record({activityType:'lesson_completed',eventId:'completed_lesson:p72a-browser:lesson-first-introduction:first',referenceId:'lesson-first-introduction'}); const duplicate=window.LearningXPService.record({activityType:'lesson_completed',eventId:first.event.event_id,referenceId:'lesson-first-introduction'}); const fake=window.LearningXPService.record({activityType:'listening_practice',eventId:'listening_completed:p72a-browser:fake',referenceId:'missing'}); const score=window.TamHoanqScoreService.calculate(); const quests=window.QuestEngine.current(); const plan=window.EngagementQuickPracticeService.plan(10); return {first:first.awarded,duplicate:duplicate.status,fake:fake.reason,total:window.LearningXPService.total(),eventKeys:Object.keys(first.event),score,questTypes:quests.map(q=>q.type),plan:{minutes:plan.minutes,count:plan.questions.length,engine:plan.engine}}; })()`);
    assert.equal(core.first, 10); assert.equal(core.duplicate, 'duplicate'); assert.equal(core.fake, 'learning-evidence-required'); assert.equal(core.total, 10); for (const key of ['event_id','user_id','activity_type','xp','created_at']) assert.ok(core.eventKeys.includes(key)); assert.notEqual(core.score.score, 0); assert.equal(core.score.xpIncluded, false); assert.deepEqual(core.questTypes, ['daily','weekly','monthly','special']); assert.equal(core.plan.minutes, 10); assert.equal(core.plan.engine, 'existing-practice-service');
    await evaluate(cdp, `window.KLEARN_APP.setView('practice-center')`); assert.equal(await until(cdp, `document.querySelectorAll('.p72-practice-grid > button').length === 8`), true, 'Practice Center routes missing');
    assert.equal(await evaluate(cdp, `[...document.querySelectorAll('.p72-practice-grid > button')].every(button => Boolean(button.dataset.view))`), true);

    const results = [];
    for (const width of [360, 768, 1024, 1440, 1920]) {
      await cdp.send('Emulation.setDeviceMetricsOverride', { width, height: 1200, deviceScaleFactor: 1, mobile: false }); await evaluate(cdp, `window.KLEARN_APP.setView('engagement-center')`); await wait(100);
      const metrics = await evaluate(cdp, `(()=>{const rect=(node)=>{const value=node?.getBoundingClientRect();return value?{left:value.left,width:value.width,right:value.right}:null};return{dark:document.documentElement.dataset.theme==='dark',htmlOverflow:document.documentElement.scrollWidth>document.documentElement.clientWidth,bodyOverflow:document.body.scrollWidth>document.body.clientWidth,scrollWidth:document.body.scrollWidth,app:rect(document.getElementById('app')),nav:rect(document.getElementById('bottomNav')),summary:rect(document.querySelector('.p72-summary')),quests:rect(document.querySelector('.p72-quests')),offenders:[...document.querySelectorAll('*')].map(node=>({tag:node.tagName,className:String(node.className||''),right:node.getBoundingClientRect().right})).filter(item=>item.right>${width}+1).slice(0,8)}})()`);
      if (metrics.bodyOverflow || metrics.htmlOverflow) console.error(JSON.stringify({ width, metrics }));
      assert.equal(metrics.dark, true, `dark mode missing at ${width}px`); assert.equal(metrics.htmlOverflow, false, `html overflow at ${width}px`); assert.equal(metrics.bodyOverflow, false, `body overflow at ${width}px`); assert.ok(metrics.summary?.width <= width && metrics.quests?.width <= width, `P72A content exceeds ${width}px`);
      if (width >= 1024) { assert.ok(metrics.nav.width >= 240 && metrics.nav.width <= 280, `sidebar invalid at ${width}px`); assert.ok(metrics.app.left >= 240, `content overlaps sidebar at ${width}px`); } else assert.ok(metrics.app.left < 2, `compact content offset at ${width}px`);
      results.push({ width, sidebar: Math.round(metrics.nav.width), overflow: metrics.htmlOverflow });
    }
    await evaluate(cdp, `window.KLEARN_APP.setView('home')`); assert.equal(await until(cdp, `Boolean(document.querySelector('.p72-home-strip'))`), true, 'Home engagement summary missing');
    assert.equal(await evaluate(cdp, `localStorage.getItem('klearn_progress').includes('keep-me') && localStorage.getItem('klearn_srs').includes('freq-학교')`), true, 'existing progress or SRS changed');
    await evaluate(cdp, `location.reload()`); assert.equal(await until(cdp, `Boolean(window.EngagementCoreSystem && window.LearningXPService.total()===10)`), true, 'XP did not survive reload'); assert.equal(await evaluate(cdp, `window.KLEARN_APP.getUserProgress().p72aRegressionMarker==='keep-me' && window.KLEARN_APP.getUserSrs()[0].wordId==='freq-학교'`), true, 'user data regression after reload');
    console.log(JSON.stringify(results)); console.log('P72A browser: XP, score, quests, Practice Center, persistence, dark mode and 360-1920 responsive passed'); cdp.close();
  } finally { browser.kill(); await wait(200); fs.rmSync(profile, { recursive: true, force: true, maxRetries: 8, retryDelay: 100 }); }
})().catch((error) => { console.error(error); process.exitCode = 1; });
