/* Real-browser P72B QA: node tests/p72b-micro-learning-experience-responsive.browser.js [url] */
const assert = require('node:assert/strict');
const childProcess = require('node:child_process');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

const edge = [path.join(process.env['ProgramFiles(x86)'] || '', 'Microsoft', 'Edge', 'Application', 'msedge.exe'), path.join(process.env.ProgramFiles || '', 'Microsoft', 'Edge', 'Application', 'msedge.exe'), path.join(process.env.LOCALAPPDATA || '', 'Microsoft', 'Edge', 'Application', 'msedge.exe')].find((candidate) => candidate && fs.existsSync(candidate));
if (!edge) throw new Error('Microsoft Edge is required for P72B responsive QA.');
const baseUrl = process.argv[2] || 'http://127.0.0.1:4173/'; const port = 11500 + Math.floor(Math.random() * 70); const profile = path.join(os.tmpdir(), `klearn-p72b-browser-${process.pid}`);
const browser = childProcess.spawn(edge, ['--headless=new', `--remote-debugging-port=${port}`, `--user-data-dir=${profile}`, '--disable-gpu', '--no-first-run', '--no-default-browser-check', 'about:blank'], { stdio: 'ignore', windowsHide: true });
const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
async function json(url, options) { const response = await fetch(url, options); if (!response.ok) throw new Error(`${response.status} ${url}`); return response.json(); }
async function connect(url) { const socket = new WebSocket(url); let id = 0; const pending = new Map(); await new Promise((resolve, reject) => { socket.onopen = resolve; socket.onerror = reject; }); socket.onmessage = (event) => { const message = JSON.parse(event.data); const request = pending.get(message.id); if (!request) return; pending.delete(message.id); message.error ? request.reject(new Error(message.error.message)) : request.resolve(message.result); }; return { send(method, params = {}) { return new Promise((resolve, reject) => { const next = ++id; pending.set(next, { resolve, reject }); socket.send(JSON.stringify({ id: next, method, params })); }); }, close() { socket.close(); } }; }
async function evaluate(cdp, expression) { const output = await cdp.send('Runtime.evaluate', { expression, returnByValue: true, awaitPromise: true }); if (output.exceptionDetails) throw new Error(output.exceptionDetails.exception?.description || output.exceptionDetails.text); return output.result.value; }
async function until(cdp, expression, attempts = 200) { for (let attempt = 0; attempt < attempts; attempt += 1) { if (await evaluate(cdp, expression)) return true; await wait(100); } return false; }

(async () => {
  let cdp;
  try {
    let version; for (let attempt = 0; attempt < 50 && !version; attempt += 1) { try { version = await json(`http://127.0.0.1:${port}/json/version`); } catch (_) { await wait(100); } }
    if (!version) throw new Error('Could not start Edge.');
    const target = await json(`http://127.0.0.1:${port}/json/new?${encodeURIComponent(baseUrl)}`, { method: 'PUT' }); cdp = await connect(target.webSocketDebuggerUrl); await cdp.send('Page.enable'); await cdp.send('Runtime.enable'); await cdp.send('Network.enable'); assert.equal(await until(cdp, `location.origin === 'http://127.0.0.1:4173' && document.readyState === 'complete'`), true);
    const now = new Date(); const timestamp = now.toISOString(); const expires = new Date(now.getTime() + 7 * 86400000).toISOString();
    const user = { id: 'p72b-browser', fullName: 'Micro Learner', email: 'micro@local.test', level: 'Beginner', currentTopikLevel: 1, targetTopikLevel: 2, studyMinutesPerDay: 15, onboardingCompleted: true, createdAt: timestamp };
    const progress = { p72bRegressionMarker: 'keep-me', lessonProgress: {}, skills: { vocabulary: 55, grammar: 30, listening: 25, reading: 45, speaking: 35, writing: 30 }, stats: { streak: 2, lessonsCompleted: 0 }, daily: { date: timestamp.slice(0, 10), tasks: {} }, pronunciationAttempts: [], writingSubmissions: [] };
    const srs = [{ wordId: 'coffee', korean: '아메리카노', status: 'review', mastery: 70, reviewCount: 3, correctCount: 3, wrongCount: 1, lastReviewed: timestamp }];
    await evaluate(cdp, `(() => { const user=${JSON.stringify(user)}; localStorage.clear(); localStorage.setItem('klearn_users',JSON.stringify([user])); localStorage.setItem('klearn_session',JSON.stringify({userId:user.id,createdAt:${JSON.stringify(timestamp)},sessionCreatedAt:${JSON.stringify(timestamp)},sessionExpiresAt:${JSON.stringify(expires)}})); localStorage.setItem('klearn_progress',JSON.stringify({[user.id]:${JSON.stringify(progress)}})); localStorage.setItem('klearn_srs',JSON.stringify({[user.id]:${JSON.stringify(srs)}})); localStorage.setItem('klearn_settings',JSON.stringify({schemaVersion:13,users:{[user.id]:{theme:'dark',language:'vi',privacy:{cloudSync:true}}}})); location.hash='micro-path'; location.reload(); })()`);
    assert.equal(await until(cdp, `Boolean(window.MicroLearningExperience && document.querySelector('.p72b-units'))`), true, 'P72B micro path did not load');
    const initial = await evaluate(cdp, `(()=>{const nodes=window.MicroPathService.nodes(); const first=nodes[0]; const second=nodes[1]; const before=window.MicroPathService.summary(); window.MicroPathService.open(first.id); return{count:nodes.length,types:[...new Set(nodes.map(n=>n.type))],minutes:nodes.map(n=>n.minutes),before,opened:window.MicroPathService.status(first),second:window.MicroPathService.status(second),route:window.KLEARN_APP.state.currentView,stored:JSON.parse(localStorage.getItem('klearn_micro_learning'))['p72b-browser'][0].activeNodeId};})()`);
    assert.equal(initial.count, 24); assert.equal(initial.types.length, 8); assert.ok(initial.minutes.every((value) => value >= 3 && value <= 10)); assert.equal(initial.before.completed, 0); assert.equal(initial.opened, 'in_progress'); assert.equal(initial.second, 'locked'); assert.equal(initial.route, 'lesson-preview'); assert.ok(initial.stored);

    await evaluate(cdp, `location.reload()`); assert.equal(await until(cdp, `Boolean(window.MicroLearningExperience && window.MicroPathService.nodes().length===24)`), true, 'module did not restore after reload');
    const progression = await evaluate(cdp, `(()=>{const nodes=window.MicroPathService.nodes(); const complete=window.MicroPathService.completeFromEvidence({type:'completed_lesson',entityId:'topik-1-01',mutationId:'browser-lesson-proof',score:85}); const first=window.MicroPathService.status(nodes[0]); const second=window.MicroPathService.status(nodes[1]); window.MicroPathService.open(nodes[1].id); window.KLEARN_APP.state.microLearningActiveNodeId=''; window.dispatchEvent(new CustomEvent('klearn-sync-action',{detail:{type:'srs_updated',entityId:'coffee',mutationId:'browser-srs-proof'}})); window.CharacterProgressService.refresh(); return{complete,first,second,srsDone:window.MicroPathService.status(nodes[1])==='completed',summary:window.MicroPathService.summary(),yuna:window.CharacterProgressService.get('yuna')};})()`);
    assert.equal(progression.complete, true); assert.equal(progression.first, 'completed'); assert.equal(progression.second, 'available'); assert.equal(progression.srsDone, true); assert.equal(progression.summary.completed, 2); assert.equal(progression.yuna.unlocked, true);

    const partialAdventure = await evaluate(cdp, `(()=>{const start=window.AdventureLearningService.start('seoul-cafe-order'); const hint=window.AdventureLearningService.submit('order-eat'); const alternative=window.AdventureLearningService.submit('order-exists'); return{start:start.adventureId,hint:hint.consequence,alternative:alternative.consequence,index:window.AdventureLearningService.active().stepIndex};})()`);
    assert.equal(partialAdventure.start, 'seoul-cafe-order'); assert.equal(partialAdventure.hint, 'hint'); assert.equal(partialAdventure.alternative, 'alternative'); assert.equal(partialAdventure.index, 1);
    await evaluate(cdp, `location.reload()`); assert.equal(await until(cdp, `Boolean(window.AdventureLearningService && window.AdventureLearningService.active()?.stepIndex===1)`), true, 'adventure state did not resume');
    const finished = await evaluate(cdp, `(()=>{const run=window.AdventureLearningService.submit('take'); const store=JSON.parse(localStorage.getItem('klearn_micro_learning'))['p72b-browser'][0]; return{percentage:run.percentage,rawAudio:run.rawAudioStored,freeText:run.freeResponseStored,runs:store.adventureRuns.length,reward:store.rewards[0]?.id,mastery:window.KLEARN_APP.getUserProgress().p72bRegressionMarker};})()`);
    assert.equal(finished.percentage, 75); assert.equal(finished.rawAudio, false); assert.equal(finished.freeText, false); assert.equal(finished.runs, 1); assert.equal(finished.reward, 'cafe-stamp'); assert.equal(finished.mastery, 'keep-me');

    const results = [];
    for (const width of [360, 768, 1024, 1440, 1920]) {
      await cdp.send('Emulation.setDeviceMetricsOverride', { width, height: 1200, deviceScaleFactor: 1, mobile: false }); await evaluate(cdp, `window.KLEARN_APP.setView('micro-path')`); await wait(100);
      const metrics = await evaluate(cdp, `(()=>{const rect=(node)=>{const value=node?.getBoundingClientRect();return value?{left:value.left,width:value.width,right:value.right}:null};return{dark:document.documentElement.dataset.theme==='dark',htmlOverflow:document.documentElement.scrollWidth>document.documentElement.clientWidth,bodyOverflow:document.body.scrollWidth>document.body.clientWidth,app:rect(document.getElementById('app')),nav:rect(document.getElementById('bottomNav')),summary:rect(document.querySelector('.p72b-path-summary')),units:rect(document.querySelector('.p72b-units')),nodeScroller:document.querySelector('.p72b-node-line')?.scrollWidth>document.querySelector('.p72b-node-line')?.clientWidth};})()`);
      assert.equal(metrics.dark, true, `dark mode missing at ${width}px`); assert.equal(metrics.htmlOverflow, false, `html overflow at ${width}px`); assert.equal(metrics.bodyOverflow, false, `body overflow at ${width}px`); assert.ok(metrics.summary?.width <= width && metrics.units?.width <= width, `P72B content exceeds ${width}px`);
      if (width >= 1024) { assert.ok(metrics.nav.width >= 240 && metrics.nav.width <= 280, `sidebar invalid at ${width}px`); assert.ok(metrics.app.left >= 240, `content overlaps sidebar at ${width}px`); } else assert.ok(metrics.app.left < 2, `compact content offset at ${width}px`);
      results.push({ width, sidebar: Math.round(metrics.nav.width), overflow: metrics.htmlOverflow, nodeScroller: metrics.nodeScroller });
    }
    await evaluate(cdp, `window.KLEARN_APP.setView('character-room')`); assert.equal(await until(cdp, `document.querySelectorAll('.p72b-character-grid > button').length===4`), true); await evaluate(cdp, `window.KLEARN_APP.setView('korean-adventure')`); assert.equal(await until(cdp, `document.querySelectorAll('.p72b-adventure-grid > article').length===3`), true);
    assert.equal(await evaluate(cdp, `localStorage.getItem('klearn_progress').includes('keep-me') && localStorage.getItem('klearn_srs').includes('coffee')`), true, 'existing progress or SRS changed');

    assert.equal(await until(cdp, `navigator.serviceWorker?.controller || false`), true, 'service worker not controlling P72B page');
    await cdp.send('Network.emulateNetworkConditions', { offline: true, latency: 0, downloadThroughput: 0, uploadThroughput: 0 }); await evaluate(cdp, `location.hash='micro-path'; location.reload()`);
    assert.equal(await until(cdp, `Boolean(window.MicroLearningExperience && document.querySelector('.p72b-units'))`, 120), true, 'P72B offline fallback failed');
    assert.equal(await evaluate(cdp, `window.MicroPathService.summary().completed===2 && window.AdventureLearningService.catalog().find(item=>item.id==='seoul-cafe-order').completed===true`), true, 'offline progress restore failed');
    await cdp.send('Network.emulateNetworkConditions', { offline: false, latency: 0, downloadThroughput: -1, uploadThroughput: -1 });
    console.log(JSON.stringify(results)); console.log('P72B browser: progression, evidence completion, character persistence, adventure resume, offline fallback, dark mode and 360-1920 responsive passed'); cdp.close(); cdp = null;
  } finally { try { if (cdp) await cdp.send('Network.emulateNetworkConditions', { offline: false, latency: 0, downloadThroughput: -1, uploadThroughput: -1 }); } catch (_) {} cdp?.close(); browser.kill(); await wait(200); if (path.resolve(profile).startsWith(path.resolve(os.tmpdir()))) fs.rmSync(profile, { recursive: true, force: true, maxRetries: 8, retryDelay: 100 }); }
})().catch((error) => { console.error(error); process.exitCode = 1; });
