/* Real-browser P82 QA: node tests/p82-personal-vocabulary-responsive.browser.js [url] */
const assert = require('node:assert/strict');
const childProcess = require('node:child_process');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

const edge = [path.join(process.env['ProgramFiles(x86)'] || '', 'Microsoft', 'Edge', 'Application', 'msedge.exe'), path.join(process.env.ProgramFiles || '', 'Microsoft', 'Edge', 'Application', 'msedge.exe'), path.join(process.env.LOCALAPPDATA || '', 'Microsoft', 'Edge', 'Application', 'msedge.exe')].find((candidate) => candidate && fs.existsSync(candidate));
if (!edge) throw new Error('Microsoft Edge is required for P82 responsive QA.');
const baseUrl = process.argv[2] || 'http://127.0.0.1:4173/';
const port = 11700 + Math.floor(Math.random() * 80); const profile = path.join(os.tmpdir(), `klearn-p82-browser-${process.pid}`);
const browser = childProcess.spawn(edge, ['--headless=new', `--remote-debugging-port=${port}`, `--user-data-dir=${profile}`, '--disable-gpu', '--no-first-run', '--no-default-browser-check', 'about:blank'], { stdio:'ignore', windowsHide:true });
const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
async function json(url, options) { const response = await fetch(url, options); if (!response.ok) throw new Error(`${response.status} ${url}`); return response.json(); }
async function connect(url) { const socket = new WebSocket(url); let id = 0; const pending = new Map(); await new Promise((resolve, reject) => { socket.onopen = resolve; socket.onerror = reject; }); socket.onmessage = (event) => { const message = JSON.parse(event.data); const request = pending.get(message.id); if (!request) return; pending.delete(message.id); message.error ? request.reject(new Error(message.error.message)) : request.resolve(message.result); }; return { send(method, params = {}) { return new Promise((resolve, reject) => { const next = ++id; pending.set(next, { resolve, reject }); socket.send(JSON.stringify({ id:next, method, params })); }); }, close() { socket.close(); } }; }
async function evaluate(cdp, expression) { const output = await cdp.send('Runtime.evaluate', { expression, returnByValue:true, awaitPromise:true }); if (output.exceptionDetails) throw new Error(output.exceptionDetails.exception?.description || output.exceptionDetails.text); return output.result.value; }
async function until(cdp, expression, attempts = 300) { for (let index = 0; index < attempts; index += 1) { if (await evaluate(cdp, expression)) return true; await wait(100); } return false; }

(async () => {
  let cdp;
  try {
    let version; for (let attempt = 0; attempt < 60 && !version; attempt += 1) { try { version = await json(`http://127.0.0.1:${port}/json/version`); } catch (_) { await wait(100); } } if (!version) throw new Error('Could not start Edge.');
    const target = await json(`http://127.0.0.1:${port}/json/new?${encodeURIComponent(`${baseUrl}?p82=1`)}`, { method:'PUT' }); cdp = await connect(target.webSocketDebuggerUrl); await cdp.send('Page.enable'); await cdp.send('Runtime.enable'); await cdp.send('Network.enable');
    assert.equal(await until(cdp, `document.readyState==='complete'&&Boolean(window.KLEARN_APP)`), true, 'app did not load');
    const timestamp = new Date().toISOString(); const user = { id:'p82-browser-user', fullName:'P82 Browser', email:'p82@local.test', onboardingCompleted:true, currentTopikLevel:2, createdAt:timestamp };
    await evaluate(cdp, `(() => { const u=${JSON.stringify(user)},n=${JSON.stringify(timestamp)}; localStorage.clear(); localStorage.setItem('klearn_users',JSON.stringify([u])); localStorage.setItem('klearn_session',JSON.stringify({userId:u.id,createdAt:n})); localStorage.setItem('klearn_progress',JSON.stringify({[u.id]:{p82Marker:'keep-progress',lessonProgress:{},skills:{vocabulary:22},stats:{},daily:{tasks:{}}}})); localStorage.setItem('klearn_srs',JSON.stringify({[u.id]:[{id:'existing',wordId:'existing',korean:'사람',meaningVi:'người',status:'learning',mastery:20,reviewCount:1,correctCount:1,wrongCount:0,nextReview:n,activatedAt:n}]})); localStorage.setItem('klearn_settings',JSON.stringify({schemaVersion:13,users:{[u.id]:{theme:'dark',language:'vi'}}})); localStorage.setItem('klearn_privacy_preferences',JSON.stringify({[u.id]:{aiUsage:false,cloudSync:false,telemetry:false,preciseLocation:false,updatedAt:n}})); location.hash='my-vocabulary-p82'; location.reload(); })()`);
    assert.equal(await until(cdp, `Boolean(window.P82DeckService&&KLEARN_APP.state.currentView==='my-vocabulary-p82'&&document.querySelector('.p82-shell'))`), true, 'P82 did not lazy load');
    assert.equal(await evaluate(cdp, `P82AIClassificationService.available()`), false, 'AI privacy gate ignored');

    const importAudit = await evaluate(cdp, `(() => { const rows=['Korean,Meaning,WordType']; for(let i=0;i<500;i+=1) rows.push('단어'+i+',Nghĩa '+i+',Danh từ'); const text=rows.join('\\n'); const started=performance.now(); const out=P82ImportService.createDeckFromFile({title:'TOPIK II — 500 từ',fileName:'topik-500.csv',text}); KLEARN_APP.state.p82Vocabulary.deckId=out.deck.id; return {deckId:out.deck.id,total:out.result.totalWords,ms:Math.round((performance.now()-started)*100)/100,page:P82DeckService.browse(out.deck.id,{page:1}).items.length}; })()`);
    console.log('P82_BROWSER_STAGE import');
    assert.equal(importAudit.total, 500); assert.equal(importAudit.page, 50); assert.ok(importAudit.ms < 1000, `500-word import too slow: ${importAudit.ms}ms`);
    await evaluate(cdp, `(() => { KLEARN_APP.PrivacyPreferenceService.update({aiUsage:true}); window.AICoachService.request=async(prompt)=>JSON.stringify(prompt.split('\\n').filter(x=>/^\\d+\\|/.test(x)).map((_,i)=>({index:i+1,topic:'Chủ đề '+((i%12)+1),subtopic:i%2?'Nhóm B':'Nhóm A',confidence:.9}))); })()`);
    const classification = await evaluate(cdp, `(async()=>{const result=await P82AIClassificationService.suggest(${JSON.stringify(importAudit.deckId)});const before=P82DeckService.words(${JSON.stringify(importAudit.deckId)})[0].topic;const confirmed=P82AIClassificationService.confirm(${JSON.stringify(importAudit.deckId)});return{...result,before,confirmed,topics:P82DeckService.topics(${JSON.stringify(importAudit.deckId)}).length};})()`);
    console.log('P82_BROWSER_STAGE classification');
    assert.equal(classification.processed, 500); assert.equal(classification.before, 'Chưa phân loại'); assert.equal(classification.confirmed, 500); assert.ok(classification.topics >= 12);
    await evaluate(cdp, `(() => { const id=${JSON.stringify(importAudit.deckId)},words=P82DeckService.words(id); P82DeckService.assignTopic(id,words.slice(0,20).map(w=>w.id),'Công việc','Công ty'); P82DeckService.assignTopic(id,words.slice(20,21).map(w=>w.id),'Công việc','Nhân sự'); P82DeckService.assignTopic(id,words.slice(21,22).map(w=>w.id),'Công việc','Thương mại'); })()`);

    const sessionStart = await evaluate(cdp, `(() => { const id=${JSON.stringify(importAudit.deckId)},before=P82DeckService.words(id).filter(w=>w.topic==='Công việc').slice(0,10).map(w=>w.id),s=P82LearningSessionService.start(id,{topic:'Công việc',scope:'random',count:10}); return {selected:s.selectedWordIds,before}; })()`);
    assert.equal(sessionStart.selected.length, 10); assert.notDeepEqual(sessionStart.selected, sessionStart.before, 'session did not shuffle');
    const sessionResult = await evaluate(cdp, `(() => { const id=${JSON.stringify(importAudit.deckId)}; for(let i=0;i<3;i+=1) P82LearningSessionService.answer(id,'학꾜'); let guard=0; while(P82LearningSessionService.current(id)&&guard<30){const w=P82LearningSessionService.currentWord(id); P82LearningSessionService.answer(id,w.korean); guard+=1;} const d=P82DeckService.get(id),h=d.sessionHistory[0]; return {guard,mastered:h.masteredWords,selected:h.selectedWords,wrong:h.wrongAttempts,rounds:h.rounds,srs:KLEARN_APP.getUserSrs().filter(c=>c.deckId===id).length,errors:ErrorNotebookService.all().filter(e=>e.deckId===id).length}; })()`);
    console.log('P82_BROWSER_STAGE session');
    assert.equal(sessionResult.mastered, 10); assert.equal(sessionResult.selected, 10); assert.equal(sessionResult.wrong, 3); assert.ok(sessionResult.rounds >= 2); assert.equal(sessionResult.srs, 10); assert.equal(sessionResult.errors, 3);

    await evaluate(cdp, `KLEARN_APP.setView('my-vocabulary-p82')`); assert.equal(await until(cdp, `document.querySelector('.p82-deck-grid')`), true);
    const widths = []; const routes = ['my-vocabulary-p82','vocabulary-deck-p82','vocabulary-import-p82','vocabulary-classify-p82']; await cdp.send('Emulation.setTouchEmulationEnabled', { enabled:true, maxTouchPoints:5 });
    for (const width of [360,390,430,768,1024,1440,1920]) { await cdp.send('Emulation.setDeviceMetricsOverride', { width, height:1100, deviceScaleFactor:1, mobile:width<=430 }); for (const route of routes) { await evaluate(cdp, `KLEARN_APP.setView(${JSON.stringify(route)})`); assert.equal(await until(cdp, `KLEARN_APP.state.currentView===${JSON.stringify(route)}&&Boolean(document.querySelector('.p82-shell'))`,80), true, `${route} missing at ${width}`); await wait(30); const layout = await evaluate(cdp, `(() => { const root=document.documentElement,viewport=Math.max(root.clientWidth,innerWidth),controls=[...document.querySelectorAll('.p82-shell button:not([disabled]),.p82-shell input,.p82-shell select,.p82-shell textarea')].filter(n=>getComputedStyle(n).display!=='none'&&n.getBoundingClientRect().width>0); return {overflow:root.scrollWidth>viewport+1||document.body.scrollWidth>viewport+1,appRight:Math.round(document.getElementById('app').getBoundingClientRect().right),minTouch:controls.length?Math.min(...controls.map(n=>n.getBoundingClientRect().height)):44,dark:root.dataset.theme==='dark'}; })()`); assert.equal(layout.overflow,false,`overflow ${route} ${width}`); assert.ok(layout.appRight<=width+1,`right overflow ${route} ${width}`); assert.ok(layout.minTouch>=44,`touch ${layout.minTouch}px ${route} ${width}`); assert.equal(layout.dark,true); } widths.push(width); console.log(`P82_BROWSER_STAGE width-${width}`); }

    const conflict = await evaluate(cdp, `(() => { const older=new Date().toISOString(),later=new Date(Date.now()+1000).toISOString(),id='conflict-deck'; const local=[{id,owner:'p82-browser-user',title:'Local',updatedAt:older,activeSession:{id:'old-session',updatedAt:older},customWords:[{id:'a',korean:'가',updatedAt:older}]}],remote=[{id,owner:'p82-browser-user',title:'Remote',updatedAt:later,activeSession:null,customWords:[{id:'b',korean:'나',updatedAt:later}]}]; const merged=KLEARN_APP.CloudSyncService.mergeVocabularyCollections(local,remote)[0]; const deleted=KLEARN_APP.CloudSyncService.mergeVocabularyCollections([{id:'deleted-deck',owner:'p82-browser-user',title:'Deleted',updatedAt:later,deletedAt:later,activeSession:null,wordIds:[],customWords:[]}],[{id:'deleted-deck',owner:'p82-browser-user',title:'Old',updatedAt:older,activeSession:{id:'stale'},wordIds:['stale-word'],customWords:[{id:'stale-word',korean:'다',updatedAt:older}]}])[0]; return {title:merged.title,ids:merged.customWords.map(w=>w.id).sort(),activeSession:merged.activeSession,deletedWords:deleted.customWords.length,deletedWordIds:deleted.wordIds.length,deletedSession:deleted.activeSession}; })()`); assert.equal(conflict.title,'Remote'); assert.deepEqual(conflict.ids,['a','b']); assert.equal(conflict.activeSession,null,'completed session resurrected'); assert.equal(conflict.deletedWords,0,'deleted words resurrected'); assert.equal(conflict.deletedWordIds,0,'deleted word ids resurrected'); assert.equal(conflict.deletedSession,null,'deleted session resurrected');
    assert.equal(await evaluate(cdp, `JSON.parse(localStorage.getItem('klearn_progress'))['p82-browser-user'].p82Marker==='keep-progress'`), true, 'existing progress changed'); assert.equal(await evaluate(cdp, `JSON.parse(localStorage.getItem('klearn_srs'))['p82-browser-user'].some(c=>c.wordId==='existing')`), true, 'existing SRS changed');
    await evaluate(cdp, `location.reload()`); assert.equal(await until(cdp, `Boolean(window.P82DeckService&&P82DeckService.get(${JSON.stringify(importAudit.deckId)})?.sessionHistory?.length)`), true, 'deck/session did not survive reload');
    const due = await evaluate(cdp, `(() => { const card=KLEARN_APP.getUserSrs().find(c=>c.deckId===${JSON.stringify(importAudit.deckId)}); KLEARN_APP.VocabularyService.updateCard(card.wordId,{status:'review',nextReview:new Date(Date.now()-1000).toISOString()}); return KLEARN_APP.VocabularyService.dueCards().some(c=>c.wordId===card.wordId); })()`); assert.equal(due,true,'SRS review did not appear');
    await cdp.send('Network.emulateNetworkConditions', { offline:true, latency:0, downloadThroughput:0, uploadThroughput:0 }); await evaluate(cdp, `KLEARN_APP.setView('vocabulary-deck-p82')`); await wait(120); assert.equal(await evaluate(cdp, `Boolean(document.querySelector('.p82-word-table'))`), true, 'offline deck failed');
    console.log(JSON.stringify({ status:'passed', widths, routes, checks:widths.length*routes.length+18, imported:500, aiTopics:classification.topics, userTopicCorrections:3, session:sessionResult, pagination:50, reloadPersistence:true, srsReview:true, offline:true, cloudConflictMerge:true, aiPrivacyGate:true, performanceMs:importAudit.ms, functionImpact:0 }, null, 2));
  } finally { try { cdp?.close(); } catch (_) {} browser.kill(); await wait(300); try { fs.rmSync(profile,{recursive:true,force:true,maxRetries:5,retryDelay:120}); } catch (_) {} }
})().catch((error) => { console.error(error); process.exitCode = 1; });
