/* Real-browser P83 QA: node tests/p83-smart-document-vocabulary-responsive.browser.js [url] */
'use strict';
const assert = require('node:assert/strict');
const childProcess = require('node:child_process');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

const edge = [path.join(process.env['ProgramFiles(x86)'] || '', 'Microsoft', 'Edge', 'Application', 'msedge.exe'), path.join(process.env.ProgramFiles || '', 'Microsoft', 'Edge', 'Application', 'msedge.exe'), path.join(process.env.LOCALAPPDATA || '', 'Microsoft', 'Edge', 'Application', 'msedge.exe')].find((candidate) => candidate && fs.existsSync(candidate));
if (!edge) throw new Error('Microsoft Edge is required for P83 responsive QA.');
const baseUrl = process.argv[2] || 'http://127.0.0.1:4173/';
const port = 11800 + Math.floor(Math.random() * 80); const profile = path.join(os.tmpdir(), `klearn-p83-browser-${process.pid}`);
const browser = childProcess.spawn(edge, ['--headless=new', `--remote-debugging-port=${port}`, `--user-data-dir=${profile}`, '--disable-gpu', '--no-first-run', '--no-default-browser-check', 'about:blank'], { stdio:'ignore', windowsHide:true });
const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
async function json(url, options) { const response = await fetch(url, options); if (!response.ok) throw new Error(`${response.status} ${url}`); return response.json(); }
async function connect(url) { const socket = new WebSocket(url); let id = 0; const pending = new Map(); await new Promise((resolve, reject) => { socket.onopen = resolve; socket.onerror = reject; }); socket.onmessage = (event) => { const message = JSON.parse(event.data); const request = pending.get(message.id); if (!request) return; pending.delete(message.id); message.error ? request.reject(new Error(message.error.message)) : request.resolve(message.result); }; return { send(method, params = {}) { return new Promise((resolve, reject) => { const next = ++id; pending.set(next, { resolve, reject }); socket.send(JSON.stringify({ id:next, method, params })); }); }, close() { socket.close(); } }; }
async function evaluate(cdp, expression) { const output = await cdp.send('Runtime.evaluate', { expression, returnByValue:true, awaitPromise:true }); if (output.exceptionDetails) throw new Error(output.exceptionDetails.exception?.description || output.exceptionDetails.text); return output.result.value; }
async function until(cdp, expression, attempts = 300) { for (let index = 0; index < attempts; index += 1) { if (await evaluate(cdp, expression)) return true; await wait(100); } return false; }

(async () => {
  let cdp;
  try {
    let version; for (let attempt = 0; attempt < 60 && !version; attempt += 1) { try { version = await json(`http://127.0.0.1:${port}/json/version`); } catch (_) { await wait(100); } } if (!version) throw new Error('Could not start Edge.');
    const target = await json(`http://127.0.0.1:${port}/json/new?${encodeURIComponent(`${baseUrl}?p83=1`)}`, { method:'PUT' }); cdp = await connect(target.webSocketDebuggerUrl); await cdp.send('Page.enable'); await cdp.send('Runtime.enable'); await cdp.send('Network.enable');
    assert.equal(await until(cdp, `document.readyState==='complete'&&Boolean(window.KLEARN_APP)`), true, 'app did not load');
    const timestamp = new Date().toISOString(); const user = { id:'p83-browser-user', fullName:'P83 Browser', email:'p83@local.test', onboardingCompleted:true, currentTopikLevel:2, createdAt:timestamp };
    await evaluate(cdp, `(() => { const u=${JSON.stringify(user)},n=${JSON.stringify(timestamp)}; localStorage.clear(); localStorage.setItem('klearn_users',JSON.stringify([u])); localStorage.setItem('klearn_session',JSON.stringify({userId:u.id,createdAt:n})); localStorage.setItem('klearn_progress',JSON.stringify({[u.id]:{p83Marker:'keep-progress',lessonProgress:{},skills:{vocabulary:31},stats:{},daily:{tasks:{}}}})); localStorage.setItem('klearn_srs',JSON.stringify({[u.id]:[{id:'existing',wordId:'existing',korean:'사람',meaningVi:'người',status:'learning',mastery:20,reviewCount:1,correctCount:1,wrongCount:0,nextReview:n,activatedAt:n}]})); localStorage.setItem('klearn_privacy_preferences',JSON.stringify({[u.id]:{aiUsage:false,cloudSync:false,telemetry:false,preciseLocation:false,updatedAt:n}})); location.hash='smart-vocabulary-import-p83'; location.reload(); })()`);
    const loaded = await until(cdp, `Boolean(window.SmartDocumentVocabularyImport&&KLEARN_APP.state.currentView==='smart-vocabulary-import-p83'&&document.querySelector('.p83-shell'))`); if (!loaded) console.error(await evaluate(cdp, `(()=>{let direct;try{direct={length:window.KLEARN_EXTRA_VIEWS['smart-vocabulary-import-p83']().length}}catch(e){direct={error:e.stack}}return{view:KLEARN_APP?.state?.currentView,hash:location.hash,user:KLEARN_APP?.state?.currentUser?.id,hasP83:Boolean(window.SmartDocumentVocabularyImport),extraType:typeof window.KLEARN_EXTRA_VIEWS?.['smart-vocabulary-import-p83'],direct,extraKeys:Object.keys(window.KLEARN_EXTRA_VIEWS||{}).slice(-8),html:document.getElementById('app')?.innerText?.slice(0,500),scripts:[...document.scripts].map(s=>s.src).filter(Boolean).slice(-8)}})()`)); assert.equal(loaded, true, 'P83 did not lazy load');

    const audit = await evaluate(cdp, `(async()=>{
      const enc=new TextEncoder();
      const xlsx=fflate.zipSync({
        '[Content_Types].xml':enc.encode('<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"></Types>'),
        'xl/workbook.xml':enc.encode('<?xml version="1.0"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Vocabulary" sheetId="1" r:id="rId1"/><sheet name="Skip me" sheetId="2" r:id="rId2"/></sheets></workbook>'),
        'xl/_rels/workbook.xml.rels':enc.encode('<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Target="worksheets/sheet2.xml"/></Relationships>'),
        'xl/worksheets/sheet1.xml':enc.encode('<?xml version="1.0"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData><row r="1"><c r="A1" t="inlineStr"><is><t>Korean</t></is></c><c r="B1" t="inlineStr"><is><t>Meaning</t></is></c></row><row r="2"><c r="A2" t="inlineStr"><is><t>학교</t></is></c><c r="B2" t="inlineStr"><is><t>Trường học</t></is></c></row><row r="3"><c r="A3" t="inlineStr"><is><t>친구</t></is></c><c r="B3" t="inlineStr"><is><t>Bạn bè</t></is></c></row></sheetData></worksheet>'),
        'xl/worksheets/sheet2.xml':enc.encode('<?xml version="1.0"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData><row r="1"><c r="A1" t="inlineStr"><is><t>Không chọn</t></is></c></row></sheetData></worksheet>')
      });
      const docx=fflate.zipSync({
        '[Content_Types].xml':enc.encode('<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"></Types>'),
        'word/document.xml':enc.encode('<?xml version="1.0"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body><w:tbl><w:tr><w:tc><w:p><w:r><w:t>Korean</w:t></w:r></w:p></w:tc><w:tc><w:p><w:r><w:t>Meaning</w:t></w:r></w:p></w:tc></w:tr><w:tr><w:tc><w:p><w:r><w:t>먹다</w:t></w:r></w:p></w:tc><w:tc><w:p><w:r><w:t>Ăn</w:t></w:r></w:p></w:tc></w:tr><w:tr><w:tc><w:p><w:r><w:t>도서관</w:t></w:r></w:p></w:tc><w:tc><w:p><w:r><w:t>Thư viện</w:t></w:r></w:p></w:tc></w:tr></w:tbl></w:body></w:document>')
      });
      function simplePdf(text=''){const nl=String.fromCharCode(10),parts=['%PDF-1.4'+nl],content=text?'BT /F1 12 Tf 40 240 Td ('+text+') Tj ET':'';const objects=[['1 0 obj','<< /Type /Catalog /Pages 2 0 R >>','endobj',''].join(nl),['2 0 obj','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','endobj',''].join(nl),['3 0 obj','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 300 300] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>','endobj',''].join(nl),['4 0 obj','<< /Length '+content.length+' >>','stream',content,'endstream','endobj',''].join(nl),['5 0 obj','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>','endobj',''].join(nl)];const offsets=[0];for(const obj of objects){offsets.push(parts.join('').length);parts.push(obj);}const xref=parts.join('').length;parts.push(['xref','0 6','0000000000 65535 f ',''].join(nl)+offsets.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n '+nl).join('')+['trailer','<< /Size 6 /Root 1 0 R >>','startxref',xref,'%%EOF'].join(nl));return enc.encode(parts.join(''));}
      const canvas=document.createElement('canvas');canvas.width=900;canvas.height=650;const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,900,650);ctx.fillStyle='#111';ctx.font='44px sans-serif';ctx.fillText('학교 - Trường học',50,100);const pngBlob=await new Promise(r=>canvas.toBlob(r,'image/png')),jpegBlob=await new Promise(r=>canvas.toBlob(r,'image/jpeg',.85)),webpBlob=await new Promise(r=>canvas.toBlob(r,'image/webp',.85));const photoFiles=[new File([pngBlob],'photo-1.png',{type:'image/png'}),new File([jpegBlob],'photo-2.jpg',{type:'image/jpeg'}),new File([jpegBlob],'photo-3.jpeg',{type:'image/jpeg'}),new File([webpBlob],'photo-4.webp',{type:'image/webp'}),new File([pngBlob],'photo-5.png',{type:'image/png'})];
      const files=[new File([xlsx],'lesson.xlsx',{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),new File([docx],'lesson.docx',{type:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'}),new File(['Korean,Meaning\\n회사,Công ty\\n경제,Kinh tế'],'lesson.csv',{type:'text/csv'}),new File([simplePdf()],'scan.pdf',{type:'application/pdf'}),new File([simplePdf('Korean vocabulary text layer')],'text.pdf',{type:'application/pdf'}),...photoFiles];
      const result=await P83ImportPipeline.process(files);const xlsxSource=KLEARN_APP.state.p83Import.sources.find(s=>s.type==='xlsx');const beforeSheet=KLEARN_APP.state.p83Import.rows.length;const sheetRows=P83ImportPipeline.extractSheet(xlsxSource.id,'Vocabulary');const edited=KLEARN_APP.state.p83Import.rows.find(r=>r.korean==='학교');edited.topic='Chỉnh sửa được giữ';const reprocessed=await P83ImportPipeline.reprocess(true);const preserved=KLEARN_APP.state.p83Import.rows.find(r=>r.korean==='학교')?.topic;const sourceSummary=KLEARN_APP.state.p83Import.sources.map(s=>({type:s.type,status:s.status,rows:s.rows,scannedPages:s.scannedPages||[]}));const committed=P83ImportPipeline.commit({title:'P83 Browser Deck',duplicateMode:'skip'});const words=P82DeckService.words(committed.deckId);return{result,beforeSheet,sheetRows,reprocessed,preserved,committed,sourceSummary,words:words.map(w=>({korean:w.korean,sourceType:w.sourceType,sourceFileName:w.sourceFileName,sourcePage:w.sourcePage,sourceSection:w.sourceSection,reviewStatus:w.reviewStatus})),imports:P82DeckService.get(committed.deckId).imports};
    })()`);
    assert.equal(audit.result.sources, 10); assert.equal(audit.sheetRows, 2); assert.equal(audit.preserved, 'Chỉnh sửa được giữ'); assert.ok(audit.reprocessed.preserved >= 6); assert.ok(audit.committed.added >= 6); assert.ok(audit.sourceSummary.some((item) => item.type === 'pdf' && item.scannedPages.includes(1)), 'blank PDF must be detected as scan'); assert.ok(audit.sourceSummary.some((item) => item.type === 'pdf' && item.status === 'extracted' && item.scannedPages.length === 0), 'text PDF must use its text layer'); assert.equal(audit.sourceSummary.filter((item) => item.type === 'image').length, 5, 'multi-image import missing'); assert.ok(audit.words.some((word) => word.korean === '학교' && word.sourceSection === 'Vocabulary')); assert.ok(audit.words.some((word) => word.korean === '먹다' && word.sourceFileName === 'lesson.docx')); assert.equal(audit.words.every((word) => word.reviewStatus === 'confirmed'), true); assert.equal(audit.imports[0].sourceFiles.length, 10);

    const deckId = audit.committed.deckId; const learning = await evaluate(cdp, `(()=>{const s=P82LearningSessionService.start(${JSON.stringify(deckId)},{scope:'random',count:3,random:()=>.2});let guard=0;while(P82LearningSessionService.current(${JSON.stringify(deckId)})&&guard<10){const w=P82LearningSessionService.currentWord(${JSON.stringify(deckId)});P82LearningSessionService.answer(${JSON.stringify(deckId)},w.korean);guard+=1;}return{selected:s.selectedWordIds.length,guard,history:P82DeckService.get(${JSON.stringify(deckId)}).sessionHistory.length};})()`); assert.equal(learning.selected, 3); assert.equal(learning.history, 1);

    await evaluate(cdp, `KLEARN_APP.setView('smart-vocabulary-import-p83')`); const widths = []; await cdp.send('Emulation.setTouchEmulationEnabled', { enabled:true, maxTouchPoints:5 });
    for (const width of [360,390,430,768,1024,1440,1920]) { await cdp.send('Emulation.setDeviceMetricsOverride', { width, height:1200, deviceScaleFactor:1, mobile:width<=430 }); await wait(60); const layout = await evaluate(cdp, `(()=>{const root=document.documentElement,viewport=Math.max(root.clientWidth,innerWidth),controls=[...document.querySelectorAll('.p83-shell button:not([disabled]),.p83-shell input:not([type=hidden]):not([type=checkbox]):not([type=radio]),.p83-shell select')].filter(n=>getComputedStyle(n).display!=='none'&&n.getBoundingClientRect().width>0);return{overflow:root.scrollWidth>viewport+1||document.body.scrollWidth>viewport+1,minTouch:controls.length?Math.min(...controls.map(n=>n.getBoundingClientRect().height)):44,review:Boolean(document.querySelector('.p83-review')),security:Boolean(document.querySelector('.p83-security'))};})()`); assert.equal(layout.overflow,false,`overflow at ${width}`); assert.ok(layout.minTouch>=44,`control ${layout.minTouch}px at ${width}`); assert.equal(layout.review,true); assert.equal(layout.security,true); widths.push(width); }
    const offline = await evaluate(cdp, `P83OfflineService.prepare()`); assert.equal(offline.cached, true); assert.equal(offline.assets, 6);
    assert.equal(await evaluate(cdp, `JSON.parse(localStorage.getItem('klearn_progress'))['p83-browser-user'].p83Marker==='keep-progress'`), true); assert.equal(await evaluate(cdp, `JSON.parse(localStorage.getItem('klearn_srs'))['p83-browser-user'].some(c=>c.wordId==='existing')`), true);
    await evaluate(cdp, `location.reload()`); assert.equal(await until(cdp, `Boolean(window.P82DeckService&&P82DeckService.get(${JSON.stringify(deckId)}))`), true, 'imported deck did not survive reload');
    console.log(JSON.stringify({ status:'passed', widths, sources:audit.sourceSummary, imported:audit.committed.added, xlsxSheetSelection:true, docxTablePriority:true, scannedPdfDetection:true, imageQuality:true, mandatoryReview:true, reprocessPreservesEdits:true, p82Learning:learning, provenance:true, offline:true, cloudBinary:false, functionImpact:0 }, null, 2));
  } finally { try { cdp?.close(); } catch (_) {} browser.kill(); await wait(300); try { fs.rmSync(profile,{recursive:true,force:true,maxRetries:5,retryDelay:120}); } catch (_) {} }
})().catch((error) => { console.error(error); process.exitCode = 1; });
