#!/usr/bin/env node
'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const root = path.join(__dirname, '..');
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8');

function boot(userId = 'p84-p1-user') {
  const values = new Map(); const errors = []; const state = { currentUser: { id:userId, fullName:'P84 P1' }, currentView:'my-vocabulary-p82', srsData:[], p82Vocabulary:null };
  const scoped = (key) => structuredClone(values.get(`${key}:${state.currentUser.id}`) || []);
  const saveScoped = (key, value) => { values.set(`${key}:${state.currentUser.id}`, structuredClone(value)); return value; };
  const document = { documentElement:{lang:'vi'}, querySelector:()=>null, querySelectorAll:()=>[], getElementById:()=>null, createElement:()=>({click(){}}) };
  const SRSStateService = { hasLearningEvidence:(card={})=>Boolean(card.activatedAt||card.lastReviewed||Number(card.reviewCount)||Number(card.mastery)||['learning','review','mastered'].includes(card.status)), isDue(card={},at=Date.now()){return this.hasLearningEvidence(card)&&card.nextReview&&new Date(card.nextReview).getTime()<=at;} };
  const MasteryService = { status:(score)=>Number(score)>=80?'mastered':Number(score)>=50?'understood':Number(score)>0?'learning':'not_started' };
  const saveSrs = (cards) => { state.srsData=structuredClone(cards); return state.srsData; };
  const VocabularyService = { recordRecall(card,correct,response,metadata={}) { const current=state.srsData.find((item)=>(item.wordId||item.id)===(card.wordId||card.id)); const stamp=new Date().toISOString(); Object.assign(current,{reviewCount:Number(current.reviewCount||0)+1,correctCount:Number(current.correctCount||0)+(correct?1:0),wrongCount:Number(current.wrongCount||0)+(correct?0:1),mastery:Math.max(0,Number(current.mastery||0)+(correct?10:-18)),status:correct?'review':'learning',lastReviewed:stamp,nextReview:new Date(Date.now()+(correct?86400000:600000)).toISOString(),personalVocabularyEvidence:metadata.personalVocabularyEvidence,updatedAt:stamp}); return current; } };
  const window = { document, speechSynthesis:{cancel(){},speak(){}}, KLEARN_EXTRA_VIEWS:{}, KLEARN_AFTER_RENDER:null, caches:{async open(){return{add:async()=>true};}}, confirm:()=>true, prompt:()=>null,
    ErrorNotebookService:{all:()=>errors,add:(item)=>{errors.push({...structuredClone(item),id:`error-${errors.length}`,count:1,resolved:false});}}, AdaptiveDifficultyService:{record(){}},
    KLEARN_APP:{ state, STORAGE_KEYS:{vocabularyCollections:'collections',vocabularyOrganization:'organization',offlinePacks:'offline'}, escapeHtml:String, render(){}, setView(view){state.currentView=view;}, toast(){}, userScoped:scoped, saveUserScoped:saveScoped, getUserSrs:()=>state.srsData, saveUserSrs:saveSrs, VocabularyService, SRSStateService, MasteryService, CloudSyncService:{schedule(){}}, PrivacyPreferenceService:{allows:()=>false}, emitLearningMutation(){}, speakKorean(){} }
  };
  window.window=window; const context={window,document,console,Date,Intl,Math,JSON,Object,Array,Number,String,Boolean,RegExp,Set,Map,Promise,Symbol,structuredClone,setTimeout,clearTimeout,Blob,FormData:class{},URL:{createObjectURL:()=>'',revokeObjectURL(){}}};
  vm.runInNewContext(read('data/personal-vocabulary-system.js'),context); vm.runInNewContext(read('data/personal-vocabulary-organization.js'),context);
  return {window,state,values,errors};
}
function makeDeck(rt,title,rows) { return rt.window.P82ImportService.createDeckFromFile({title,fileName:`${title}.csv`,text:['Korean,Meaning,Topic',...rows].join('\n')}).deck.id; }

(() => {
  const rt=boot(); const w=rt.window;
  const deckA=makeDeck(rt,'Bài 1',['학교,Trường học,School','회사,Công ty,Work','중요하다,Quan trọng,Work']);
  const deckB=makeDeck(rt,'Bài 2',['학교,Trường học,School','직업,Nghề nghiệp,Work','시험,Kỳ thi,TOPIK']);
  const deckC=makeDeck(rt,'Bài 3',['공부,Học tập,School']);
  const folder=w.P84FolderService.create('TOPIK II','Ôn thi'); assert.equal(w.P84FolderService.all().length,1); w.P84FolderService.rename(folder.id,'TOPIK'); assert.equal(w.P84FolderService.get(folder.id).name,'TOPIK');
  w.P84FolderService.moveDeck(deckA,folder.id); w.P84FolderService.moveDeck(deckB,folder.id); assert.equal(w.P84FolderService.count(folder.id),2); w.P84FolderService.remove(folder.id); assert.equal(w.P82DeckService.get(deckA).folderId,null); assert.ok(w.P82DeckService.get(deckA),'deleting a folder must not delete decks');

  const school=w.P82DeckService.words(deckA).find((word)=>word.korean==='학교'); w.P84MetadataService.updateWord(deckA,school.id,{tags:['TOPIK2','QuanTrọng'],personalNote:'Từ xuất hiện trong bài 5.'}); w.P84MetadataService.addExample(deckA,school.id,'저는 학교에 갑니다.'); let saved=w.P82DeckService.words(deckA).find((word)=>word.id===school.id); assert.deepEqual(Array.from(saved.tags),['topik2','quantrọng']); assert.equal(saved.personalNote,'Từ xuất hiện trong bài 5.'); assert.equal(saved.personalExamples[0].text,'저는 학교에 갑니다.'); w.P84MetadataService.updateWord(deckA,school.id,{noteConflicts:['Bản từ thiết bị B']}); assert.deepEqual(Array.from(w.P82DeckService.words(deckA).find((word)=>word.id===school.id).noteConflicts),['Bản từ thiết bị B']); w.P84MetadataService.setNote(deckA,school.id,'Bản đã xác nhận'); saved=w.P82DeckService.words(deckA).find((word)=>word.id===school.id); assert.equal(saved.personalNote,'Bản đã xác nhận'); assert.equal(saved.noteConflicts.length,0);
  assert.equal(w.P84VocabularySearchService.search({query:'trường'}).total,2); assert.equal(w.P84VocabularySearchService.search({tag:'#quantrọng'}).total,1); assert.equal(w.P84VocabularySearchService.search({topic:'Work'}).total,3);

  const duplicatePreview=w.P84DeckOperationService.duplicatePreview(deckA); const duplicate=w.P84DeckOperationService.duplicate(deckA,'Bài 1 — Practice'); assert.equal(duplicatePreview.copiesProgress,false); assert.equal(w.P82DeckService.words(duplicate.id).length,3); assert.notEqual(w.P82DeckService.words(duplicate.id)[0].id,w.P82DeckService.words(deckA)[0].id); assert.equal(rt.state.srsData.some((card)=>card.deckId===duplicate.id),false);

  const firstA=w.P82DeckService.words(deckA)[0],firstB=w.P82DeckService.words(deckB)[0]; const stamp=new Date().toISOString(); rt.state.srsData=[{id:firstA.id,wordId:firstA.id,status:'review',mastery:45,reviewCount:4,correctCount:2,wrongCount:2,nextReview:stamp,updatedAt:stamp},{id:firstB.id,wordId:firstB.id,status:'review',mastery:80,reviewCount:7,correctCount:6,wrongCount:1,nextReview:stamp,updatedAt:stamp}]; w.P84MetadataService.updateWord(deckB,firstB.id,{tags:['thi'],personalNote:'Ghi chú B'});
  const mergePreview=w.P84DeckOperationService.mergePreview([deckA,deckB,deckC],'merge'); assert.deepEqual({sources:mergePreview.sourceDecks,total:mergePreview.totalWords,duplicates:mergePreview.duplicates,output:mergePreview.outputWords},{sources:3,total:7,duplicates:1,output:6}); const merged=w.P84DeckOperationService.merge({deckIds:[deckA,deckB,deckC],title:'Review 1–3',duplicateMode:'merge'}); assert.equal(w.P82DeckService.words(merged.id).length,6); const mergedSchool=w.P82DeckService.words(merged.id).find((word)=>word.korean==='학교'); assert.ok(mergedSchool.tags.includes('thi')); assert.match([mergedSchool.personalNote,...mergedSchool.noteConflicts].join(' | '),/Bản đã xác nhận/); assert.match([mergedSchool.personalNote,...mergedSchool.noteConflicts].join(' | '),/Ghi chú B/); assert.equal(rt.state.srsData.find((card)=>card.wordId===mergedSchool.id).mastery,80); assert.ok(w.P82DeckService.get(deckA)&&w.P82DeckService.get(deckB),'merge must retain sources');

  const splitPreview=w.P84DeckOperationService.splitPreview(merged.id,{topic:'Work'}); assert.equal(splitPreview.selectedWords,3); const split=w.P84DeckOperationService.split({deckId:merged.id,title:'Review — Work',topic:'Work'}); assert.equal(w.P82DeckService.words(split.id).length,3); assert.equal(w.P82DeckService.words(merged.id).length,6); assert.deepEqual(Array.from(w.P82DeckService.words(split.id).map((word)=>word.id)),Array.from(splitPreview.wordIds));
  const target=w.P82DeckService.create({title:'Bulk'}); const added=w.P84DeckOperationService.addToDeck(deckA,w.P82DeckService.words(deckA).slice(0,2).map((word)=>word.id),target.id); assert.equal(added,2); w.P84MetadataService.addTags(deckA,w.P82DeckService.words(deckA).slice(0,2).map((word)=>word.id),'bulk'); assert.equal(w.P84VocabularySearchService.search({deckId:deckA,tag:'bulk'}).total,2); const moveTarget=w.P82DeckService.create({title:'Move target'}); const moveId=w.P82DeckService.words(deckA)[2].id; assert.equal(w.P84DeckOperationService.moveToDeck(deckA,[moveId],moveTarget.id),1); assert.equal(w.P82DeckService.words(deckA).some((word)=>word.id===moveId),false); assert.equal(w.P82DeckService.words(moveTarget.id).some((word)=>word.id===moveId),true);

  const recall=boot('recall-user'); const recallDeck=makeDeck(recall,'Recall',['학교,Trường học,School','회사,Công ty,Work','시험,Kỳ thi,TOPIK','공부,Học tập,School']); const rw=recall.window; let session=rw.P82LearningSessionService.start(recallDeck,{count:1,mode:'ko-vi',wordIds:[rw.P82DeckService.words(recallDeck)[0].id]}); assert.equal(session.mode,'ko-vi'); let answer=rw.P82LearningSessionService.answer(recallDeck,'  TRƯỜNG   HỌC '); assert.equal(answer.correct,true,'Vietnamese validation should normalize case and whitespace'); assert.equal(answer.summary.modeStats['ko-vi'].correct,1);
  session=rw.P82LearningSessionService.start(recallDeck,{count:1,mode:'listening-ko',wordIds:[rw.P82DeckService.words(recallDeck)[1].id]}); const modeBefore=session.modeByWord[session.queue[0]]; answer=rw.P82LearningSessionService.answer(recallDeck,'sai'); assert.equal(answer.correct,false); assert.equal(rw.P82LearningSessionService.current(recallDeck).modeByWord[answer.word.id],modeBefore,'retry must retain recall mode'); rw.P82LearningSessionService.answer(recallDeck,answer.word.korean);
  session=rw.P82LearningSessionService.start(recallDeck,{count:4,mode:'mixed',random:()=>0.25}); const assigned=Object.values(session.modeByWord); assert.ok(new Set(assigned).size>=2); assert.ok(assigned.every((mode)=>['vi-ko','ko-vi','listening-ko'].includes(mode)));
  assert.ok(recall.state.srsData.find((card)=>card.wordId===answer.word.id).personalVocabularyEvidence.modeStats['listening-ko']); assert.equal(recall.errors[0].recallMode,'listening-ko');

  const perf=boot('performance-user'); const started=Date.now(); for(let index=0;index<100;index+=1) perf.window.P82DeckService.create({title:`Perf ${index}`}); const rows=[]; for(let index=0;index<5000;index+=1) rows.push(`성능${index},Hiệu năng ${index},Scale`); const largeDeck=makeDeck(perf,'5000 words',rows); const largeIds=perf.window.P82DeckService.words(largeDeck).map((word)=>word.id); perf.window.P84MetadataService.addTags(largeDeck,largeIds,['scale','important']); const searchStarted=Date.now(); const largeResult=perf.window.P84VocabularySearchService.search({deckId:largeDeck,tag:'important'}); const searchMs=Date.now()-searchStarted; assert.equal(perf.window.P82DeckService.all().length,101); assert.equal(largeResult.total,5000); assert.ok(searchMs<1500,`5000-word search took ${searchMs}ms`); const performanceMs=Date.now()-started;

  const appSource=read('app.js'); const combined=[read('data/personal-vocabulary-organization.js'),read('personal-vocabulary-organization.css'),read('data/route-loader.js'),read('sw.js')].join('\n'); assert.match(appSource,/vocabularyOrganization/); assert.match(appSource,/noteConflicts/); assert.match(appSource,/mergeVocabularyOrganization/); assert.match(combined,/P84FolderService/); assert.match(combined,/vocabulary-session-setup-p84/); assert.match(combined,/@media\(max-width:430px\)/); assert.doesNotMatch(read('data/personal-vocabulary-organization.js'),/AICoach|fetch\(/); assert.match(read('scripts/vercel-function-audit.js'),/api\//);
  console.log(`P84-P1 unit: folders, tags, notes, examples, search/filter, duplicate, merge/split previews and integrity, bulk actions, four recall modes, retry, SRS/error reuse, offline/privacy/CloudSync contracts passed (101 decks, 5000 words, 10000 tag assignments: ${performanceMs}ms; search: ${searchMs}ms)`);
})();
