/* Real-browser P84-P3 QA: node tests/p84-p3-personal-learning-intelligence.browser.js [url] */
'use strict';
const assert=require('node:assert/strict');const childProcess=require('node:child_process');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');
const edge=[path.join(process.env['ProgramFiles(x86)']||'','Microsoft','Edge','Application','msedge.exe'),path.join(process.env.ProgramFiles||'','Microsoft','Edge','Application','msedge.exe'),path.join(process.env.LOCALAPPDATA||'','Microsoft','Edge','Application','msedge.exe')].find((candidate)=>candidate&&fs.existsSync(candidate));if(!edge)throw new Error('Microsoft Edge is required for P84-P3 browser QA.');
const baseUrl=process.argv[2]||'http://127.0.0.1:4173/';const port=12200+Math.floor(Math.random()*70);const profile=path.join(os.tmpdir(),`klearn-p84-p3-${process.pid}`);const browser=childProcess.spawn(edge,['--headless=new',`--remote-debugging-port=${port}`,`--user-data-dir=${profile}`,'--disable-gpu','--no-first-run','--no-default-browser-check','about:blank'],{stdio:'ignore',windowsHide:true});const wait=(ms)=>new Promise((resolve)=>setTimeout(resolve,ms));
async function json(url,options){const response=await fetch(url,options);if(!response.ok)throw new Error(`${response.status} ${url}`);return response.json();}async function connect(url){const socket=new WebSocket(url);let id=0;const pending=new Map();await new Promise((resolve,reject)=>{socket.onopen=resolve;socket.onerror=reject;});socket.onmessage=(event)=>{const message=JSON.parse(event.data),request=pending.get(message.id);if(!request)return;pending.delete(message.id);message.error?request.reject(new Error(message.error.message)):request.resolve(message.result);};return{send(method,params={}){return new Promise((resolve,reject)=>{const next=++id;pending.set(next,{resolve,reject});socket.send(JSON.stringify({id:next,method,params}));});},close(){socket.close();}};}async function evaluate(cdp,expression){const output=await cdp.send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(output.exceptionDetails)throw new Error(output.exceptionDetails.exception?.description||output.exceptionDetails.text);return output.result.value;}async function until(cdp,expression,attempts=300){for(let index=0;index<attempts;index+=1){if(await evaluate(cdp,expression))return true;await wait(100);}return false;}
(async()=>{let cdp;try{let version;for(let attempt=0;attempt<60&&!version;attempt+=1){try{version=await json(`http://127.0.0.1:${port}/json/version`);}catch(_){await wait(100);}}if(!version)throw new Error('Could not start Edge.');const target=await json(`http://127.0.0.1:${port}/json/new?${encodeURIComponent(`${baseUrl}?p84p3=1`)}`,{method:'PUT'});cdp=await connect(target.webSocketDebuggerUrl);await cdp.send('Page.enable');await cdp.send('Runtime.enable');assert.equal(await until(cdp,`document.readyState==='complete'&&Boolean(window.KLEARN_APP)`),true,'app did not load');
  const stamp=new Date().toISOString(),user={id:'p84-p3-browser',fullName:'P84 P3 Browser',email:'p84p3@local.test',onboardingCompleted:true,currentTopikLevel:2,targetTopikLevel:4,studyMinutesPerDay:15,goals:['topik'],createdAt:stamp};
  await evaluate(cdp,`(()=>{const u=${JSON.stringify(user)},n=${JSON.stringify(stamp)};localStorage.clear();localStorage.setItem('klearn_users',JSON.stringify([u]));localStorage.setItem('klearn_session',JSON.stringify({userId:u.id,createdAt:n}));localStorage.setItem('klearn_progress',JSON.stringify({[u.id]:{lessonProgress:{},skills:{},stats:{streak:7},daily:{date:n.slice(0,10),tasks:{}}}}));localStorage.setItem('klearn_privacy_preferences',JSON.stringify({[u.id]:{aiUsage:false,cloudSync:false,telemetry:false}}));location.hash='vocabulary-intelligence-p84';location.reload();})()`);
  assert.equal(await until(cdp,`Boolean(window.P84PersonalLearningIntelligence&&window.P82DeckService&&KLEARN_APP.state.currentView==='vocabulary-intelligence-p84')`),true,'P84-P3 did not load');
  const empty=await evaluate(cdp,`(()=>({enough:P84LearningSignalService.snapshot().enough,text:document.querySelector('#app')?.innerText||'',private:P84PrivateLearningProfileService.get().private}))()`);assert.equal(empty.enough,false);assert.match(empty.text,/Chưa đủ dữ liệu/);assert.equal(empty.private,true);
  const seeded=await evaluate(cdp,`(()=>{const deck=P82DeckService.create({title:'TOPIK II Intelligence'}),cards=[],now=Date.now();for(let i=0;i<40;i+=1){const word=P82DeckService.addWord(deck.id,{korean:'지능'+i,meaning:'Intelligence '+i,topic:i<20?'Education':'Work',example:'지능'+i+'을 공부합니다.'}),reviewed=new Date(now-(i%7)*86400000).toISOString();cards.push({id:word.id,wordId:word.id,deckId:deck.id,korean:word.korean,topic:word.topic,status:i<30?'mastered':'learning',mastery:i<30?88:30,reviewCount:12,correctCount:8,wrongCount:i<30?1:5,activatedAt:reviewed,lastReviewed:reviewed,updatedAt:reviewed,nextReview:new Date(now-86400000).toISOString(),personalVocabularyEvidence:{modeStats:{'ko-vi':{attempts:5,correct:5,wrong:0},'vi-ko':{attempts:5,correct:4,wrong:1},'context-fill':{attempts:4,correct:3,wrong:1},'listening-ko':{attempts:4,correct:2,wrong:2}}}});}const saved=P82DeckService.get(deck.id);saved.sessionHistory=[{id:'browser-session',selectedWordIds:saved.customWords.slice(0,20).map(w=>w.id),selectedWords:20,attempts:28,correctAttempts:20,wrongAttempts:8,completedAt:new Date().toISOString(),updatedAt:new Date().toISOString()}];P82DeckService.save(saved,'p84-p3-browser');KLEARN_APP.saveUserSrs(cards);KLEARN_APP.state.p82Vocabulary.deckId=deck.id;KLEARN_APP.render();return{deckId:deck.id,count:cards.length};})()`);
  assert.equal(await until(cdp,`P84LearningSignalService.snapshot().activeCards===40&&Boolean(document.querySelector('.p84-p3-today'))`),true,'learning profile did not render');
  const scenarioA=await evaluate(cdp,`(()=>{const p=P84PrivateLearningProfileService.get(),s=P84LearningSignalService.snapshot(),h=P84LearningHealthService.dashboard(),r=P84PersonalReportService.weekly(),plan=P84AdaptivePlanService.plan(30),goal=P84GoalTrackingService.get();return{strong:p.strengths.map(x=>x.skill),weak:p.weaknesses.map(x=>x.skill),due:s.dueCount,health:h.unlocked,days:r.learningDays,words:r.wordsStudied,types:plan.tasks.map(x=>x.type),goal:[goal.currentTopikLevel,goal.targetTopikLevel,goal.currentProgressOnly],actions:document.querySelectorAll('[data-p84-p3-weak]').length,ai:KLEARN_APP.PrivacyPreferenceService.allows('aiUsage')};})()`);
  assert.ok(scenarioA.strong.includes('vocabulary'),JSON.stringify(scenarioA));assert.ok(scenarioA.weak.includes('listening'),JSON.stringify(scenarioA));assert.equal(scenarioA.health,true);assert.equal(scenarioA.days,7);assert.equal(scenarioA.words,40);assert.ok(scenarioA.types.includes('srs')&&scenarioA.types.includes('context')&&scenarioA.types.includes('new'));assert.deepEqual(scenarioA.goal,[2,4,true]);assert.ok(scenarioA.actions>=1);assert.equal(scenarioA.ai,false);
  const short=await evaluate(cdp,`(()=>{const p=P84AdaptivePlanService.plan(5);return{minutes:p.minutes,tasks:p.tasks.length,count:p.tasks[0].count,offline:p.offline};})()`);assert.deepEqual(short,{minutes:5,tasks:1,count:5,offline:true});
  const cached=await evaluate(cdp,`(async()=>{const result=await P82OfflineService.prepare();const css=await caches.match('./personal-learning-intelligence.css?v=1');const js=await caches.match('./data/personal-learning-intelligence.js?v=1');return{result,css:Boolean(css),js:Boolean(js)};})()`);assert.equal(cached.result.cached,true);assert.equal(cached.css,true);assert.equal(cached.js,true);
  await cdp.send('Network.enable');await cdp.send('Network.emulateNetworkConditions',{offline:true,latency:0,downloadThroughput:0,uploadThroughput:0});const offline=await evaluate(cdp,`(()=>({plan:P84AdaptivePlanService.plan(10).tasks.length,report:P84PersonalReportService.weekly().enough}))()`);assert.ok(offline.plan>=2);assert.equal(offline.report,true);await cdp.send('Network.emulateNetworkConditions',{offline:false,latency:0,downloadThroughput:-1,uploadThroughput:-1});
  const widths=[];await cdp.send('Emulation.setTouchEmulationEnabled',{enabled:true,maxTouchPoints:5});for(const width of [360,390,430,768,1024,1440,1920]){await cdp.send('Emulation.setDeviceMetricsOverride',{width,height:1100,deviceScaleFactor:1,mobile:width<=430});await wait(60);const layout=await evaluate(cdp,`(()=>{const root=document.documentElement,viewport=Math.max(root.clientWidth,innerWidth),controls=[...document.querySelectorAll('.p84-p3-shell button')].filter(n=>getComputedStyle(n).display!=='none'&&n.getBoundingClientRect().width>0);return{overflow:root.scrollWidth>viewport+1||document.body.scrollWidth>viewport+1,minTouch:controls.length?Math.min(...controls.map(n=>n.getBoundingClientRect().height)):44,health:Boolean(document.querySelector('.p84-p3-health'))};})()`);assert.equal(layout.overflow,false,`overflow at ${width}`);assert.ok(layout.minTouch>=40,`touch target ${layout.minTouch}px at ${width}`);assert.equal(layout.health,true);widths.push(width);}
  const recovery=await evaluate(cdp,`(()=>{const id=${JSON.stringify(seeded.deckId)},old=new Date(Date.now()-30*86400000).toISOString(),cards=KLEARN_APP.getUserSrs().map(c=>({...c,lastReviewed:c.activatedAt||c.lastReviewed?old:c.lastReviewed,activatedAt:c.activatedAt?old:c.activatedAt,updatedAt:c.activatedAt||c.lastReviewed?old:c.updatedAt,nextReview:c.nextReview?old:c.nextReview})),deck=P82DeckService.get(id);deck.sessionHistory=deck.sessionHistory.map(s=>({...s,completedAt:old,updatedAt:old}));P82DeckService.save(deck,'p84-p3-return');KLEARN_APP.saveUserSrs(cards);KLEARN_APP.setView('vocabulary-recovery-p84');const r=P84RecoveryPlanService.status();return{active:r.active,away:r.awayDays,days:r.days.length,reset:r.resetsProgress,text:document.querySelector('#app')?.innerText||'',activeCards:P84LearningSignalService.snapshot().activeCards};})()`);assert.equal(recovery.active,true);assert.ok(recovery.away>=30);assert.equal(recovery.days,3);assert.equal(recovery.reset,false);assert.match(recovery.text,/Chào mừng quay lại/);assert.equal(recovery.activeCards,40);
  console.log(JSON.stringify({status:'passed',widths,scenarios:{threeMonthsProfile:true,thirtyDayRecovery:true,topikGoal:true,fiveMinutePlan:true},privacy:true,aiDisabled:true,offline:true,derivedReportSync:false,functionImpact:0},null,2));
}finally{try{cdp?.close();}catch(_){}browser.kill();await wait(250);try{fs.rmSync(profile,{recursive:true,force:true,maxRetries:5,retryDelay:100});}catch(_){}}})().catch((error)=>{console.error(error);process.exitCode=1;});
