/* Real-browser P84-P2 QA: node tests/p84-p2-vocabulary-mastery-real-usage.browser.js [url] */
'use strict';
const assert=require('node:assert/strict');const childProcess=require('node:child_process');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');
const edge=[path.join(process.env['ProgramFiles(x86)']||'','Microsoft','Edge','Application','msedge.exe'),path.join(process.env.ProgramFiles||'','Microsoft','Edge','Application','msedge.exe'),path.join(process.env.LOCALAPPDATA||'','Microsoft','Edge','Application','msedge.exe')].find((candidate)=>candidate&&fs.existsSync(candidate));if(!edge)throw new Error('Microsoft Edge is required for P84-P2 browser QA.');
const baseUrl=process.argv[2]||'http://127.0.0.1:4173/';const port=12100+Math.floor(Math.random()*70);const profile=path.join(os.tmpdir(),`klearn-p84-p2-${process.pid}`);const browser=childProcess.spawn(edge,['--headless=new',`--remote-debugging-port=${port}`,`--user-data-dir=${profile}`,'--disable-gpu','--no-first-run','--no-default-browser-check','about:blank'],{stdio:'ignore',windowsHide:true});const wait=(ms)=>new Promise((resolve)=>setTimeout(resolve,ms));
async function json(url,options){const response=await fetch(url,options);if(!response.ok)throw new Error(`${response.status} ${url}`);return response.json();}async function connect(url){const socket=new WebSocket(url);let id=0;const pending=new Map();await new Promise((resolve,reject)=>{socket.onopen=resolve;socket.onerror=reject;});socket.onmessage=(event)=>{const message=JSON.parse(event.data),request=pending.get(message.id);if(!request)return;pending.delete(message.id);message.error?request.reject(new Error(message.error.message)):request.resolve(message.result);};return{send(method,params={}){return new Promise((resolve,reject)=>{const next=++id;pending.set(next,{resolve,reject});socket.send(JSON.stringify({id:next,method,params}));});},close(){socket.close();}};}async function evaluate(cdp,expression){const output=await cdp.send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(output.exceptionDetails)throw new Error(output.exceptionDetails.exception?.description||output.exceptionDetails.text);return output.result.value;}async function until(cdp,expression,attempts=300){for(let index=0;index<attempts;index+=1){if(await evaluate(cdp,expression))return true;await wait(100);}return false;}
(async()=>{let cdp;try{let version;for(let attempt=0;attempt<60&&!version;attempt+=1){try{version=await json(`http://127.0.0.1:${port}/json/version`);}catch(_){await wait(100);}}if(!version)throw new Error('Could not start Edge.');const target=await json(`http://127.0.0.1:${port}/json/new?${encodeURIComponent(`${baseUrl}?p84p2=1`)}`,{method:'PUT'});cdp=await connect(target.webSocketDebuggerUrl);await cdp.send('Page.enable');await cdp.send('Runtime.enable');assert.equal(await until(cdp,`document.readyState==='complete'&&Boolean(window.KLEARN_APP)`),true,'app did not load');
  const stamp=new Date().toISOString(),user={id:'p84-p2-browser',fullName:'P84 P2 Browser',email:'p84p2@local.test',onboardingCompleted:true,currentTopikLevel:2,targetTopikLevel:4,goals:['topik'],createdAt:stamp};
  await evaluate(cdp,`(()=>{const u=${JSON.stringify(user)},n=${JSON.stringify(stamp)};localStorage.clear();localStorage.setItem('klearn_users',JSON.stringify([u]));localStorage.setItem('klearn_session',JSON.stringify({userId:u.id,createdAt:n}));localStorage.setItem('klearn_progress',JSON.stringify({[u.id]:{lessonProgress:{},skills:{vocabulary:30},stats:{streak:2},daily:{date:n.slice(0,10),tasks:{}}}}));localStorage.setItem('klearn_privacy_preferences',JSON.stringify({[u.id]:{aiUsage:false,cloudSync:false,telemetry:false}}));location.hash='my-vocabulary-p82';location.reload();})()`);
  assert.equal(await until(cdp,`Boolean(window.P84VocabularyMastery&&window.P84ContextService&&KLEARN_APP.state.currentView==='my-vocabulary-p82')`),true,'P84-P2 did not load');
  const seeded=await evaluate(cdp,`(()=>{const deck=P82DeckService.create({title:'Real Usage'});const school=P82DeckService.addWord(deck.id,{korean:'학교',meaning:'Trường học',topic:'School',example:'저는 학교에 갑니다.'});const borrow=P82DeckService.addWord(deck.id,{korean:'빌리다',meaning:'Mượn',topic:'Daily',example:'책을 빌리다.'});const lend=P82DeckService.addWord(deck.id,{korean:'빌려주다',meaning:'Cho mượn',topic:'Daily',example:'책을 빌려주다.'});const know=P82DeckService.addWord(deck.id,{korean:'알다',meaning:'Biết',topic:'Daily',example:'답을 알다.'});P84MetadataService.addExample(deck.id,school.id,'저는 학교에서 공부합니다.');P84WordRelationService.add({deckId:deck.id,sourceWordId:borrow.id,relatedWordId:lend.id,relationType:'similar',source:'verified'});for(let i=0;i<3;i+=1)P82LearningSessionService.recordRecall(deck.id,borrow.id,false,'빌려주다',{mode:'confusion-choice',errorType:'vocabulary-confusion'});KLEARN_APP.state.p82Vocabulary.deckId=deck.id;KLEARN_APP.setView('vocabulary-deck-p82');return{deckId:deck.id,schoolId:school.id,borrowId:borrow.id};})()`);
  assert.equal(await until(cdp,`Boolean(document.querySelector('[data-p84-p2-open]'))`),true,'P84-P2 deck entry missing');
  const scenario=await evaluate(cdp,`(()=>{const context=P84ContextService.question(${JSON.stringify(seeded.deckId)},${JSON.stringify(seeded.schoolId)},'system');const health=P84VocabularyHealthService.deck(${JSON.stringify(seeded.deckId)});const borrow=P84VocabularyHealthService.word(${JSON.stringify(seeded.deckId)},${JSON.stringify(seeded.borrowId)});return{prompt:context.prompt,examples:P84ContextService.examples(context.word).length,total:health.total,weak:health.weak,confusion:borrow.confusion.active,recommendation:borrow.recommendation,audio:P84VocabularyMastery.audioAvailable(),privacy:KLEARN_APP.PrivacyPreferenceService.allows('aiUsage')};})()`);
  assert.equal(scenario.prompt,'저는 ______에 갑니다.');assert.equal(scenario.examples,2);assert.equal(scenario.total,4);assert.equal(scenario.confusion,true);assert.equal(scenario.recommendation,'Luyện lại ngữ cảnh của từ này');assert.equal(scenario.privacy,false);
  await evaluate(cdp,`(()=>{KLEARN_APP.state.p84Mastery.deckId=${JSON.stringify(seeded.deckId)};KLEARN_APP.state.p84Mastery.detailWordId=${JSON.stringify(seeded.borrowId)};KLEARN_APP.setView('vocabulary-mastery-p84');})()`);assert.equal(await until(cdp,`Boolean(document.querySelector('.p84-p2-health')&&document.querySelector('.p84-warning'))`),true,'health/confusion UI missing');
  const contextRun=await evaluate(cdp,`(()=>{const s=P84ReviewIntelligenceService.start(${JSON.stringify(seeded.deckId)},{type:'context',count:1});const c=P84ReviewIntelligenceService.current();const wrong=P84ReviewIntelligenceService.answer('sai');const retry=P84ReviewIntelligenceService.current();const right=P84ReviewIntelligenceService.answer(retry.word.korean);return{mode:s.queue[0].mode,prompt:c.question.prompt,wrong:wrong.correct,retryMode:retry.item.mode,completed:right.completed,evidence:KLEARN_APP.getUserSrs().find(x=>(x.wordId||x.id)===retry.word.id).personalVocabularyEvidence.modeStats['context-fill']};})()`);assert.equal(contextRun.mode,'context');assert.equal(contextRun.wrong,false);assert.equal(contextRun.retryMode,'context');assert.equal(contextRun.completed,true);assert.ok(contextRun.evidence.correct>=1);
  const review=await evaluate(cdp,`(()=>{const confusion=P84ReviewIntelligenceService.start(${JSON.stringify(seeded.deckId)},{type:'confusion',count:1});const cq=P84ReviewIntelligenceService.current();P84ReviewIntelligenceService.answer(cq.word.korean);const mixed=P84ReviewIntelligenceService.start(${JSON.stringify(seeded.deckId)},{type:'mixed',count:4});return{confusionOptions:cq.question.options.length,modes:mixed.queue.map(x=>x.mode),relations:P84WordRelationService.all(${JSON.stringify(seeded.deckId)}).length,errorAttempts:KLEARN_APP.userScoped(KLEARN_APP.STORAGE_KEYS.errors).reduce((n,e)=>n+Number(e.count||1),0)};})()`);assert.equal(review.confusionOptions,2);assert.ok(new Set(review.modes).size>=3,JSON.stringify(review));assert.equal(review.relations,1);assert.ok(review.errorAttempts>=4,JSON.stringify(review));
  await evaluate(cdp,`(()=>{KLEARN_APP.state.p84Mastery.session=null;KLEARN_APP.state.p84Mastery.result=null;KLEARN_APP.setView('vocabulary-mastery-p84');})()`);const widths=[];await cdp.send('Emulation.setTouchEmulationEnabled',{enabled:true,maxTouchPoints:5});for(const width of [360,390,430,768,1024,1440,1920]){await cdp.send('Emulation.setDeviceMetricsOverride',{width,height:1100,deviceScaleFactor:1,mobile:width<=430});await wait(60);const layout=await evaluate(cdp,`(()=>{const root=document.documentElement,viewport=Math.max(root.clientWidth,innerWidth),controls=[...document.querySelectorAll('.p84-p2-shell button,.p84-p2-shell input')].filter(n=>getComputedStyle(n).display!=='none'&&n.getBoundingClientRect().width>0);return{overflow:root.scrollWidth>viewport+1||document.body.scrollWidth>viewport+1,minTouch:controls.length?Math.min(...controls.map(n=>n.getBoundingClientRect().height)):44,health:Boolean(document.querySelector('.p84-p2-health'))};})()`);assert.equal(layout.overflow,false,`overflow at ${width}`);assert.ok(layout.minTouch>=40,`touch target ${layout.minTouch}px at ${width}`);assert.equal(layout.health,true);widths.push(width);}
  await evaluate(cdp,'location.reload()');assert.equal(await until(cdp,`Boolean(window.P84WordRelationService&&P82DeckService.get(${JSON.stringify(seeded.deckId)}))`),true,'reload failed');const persisted=await evaluate(cdp,`(()=>({relations:P84WordRelationService.all(${JSON.stringify(seeded.deckId)}).length,history:KLEARN_APP.userScoped(KLEARN_APP.STORAGE_KEYS.vocabularyOrganization)[0].reviewHistory.length,personal:P82DeckService.words(${JSON.stringify(seeded.deckId)}).find(w=>w.id===${JSON.stringify(seeded.schoolId)}).personalExamples.length,ai:KLEARN_APP.PrivacyPreferenceService.allows('aiUsage')}))()`);assert.equal(persisted.relations,1);assert.ok(persisted.history>=1);assert.equal(persisted.personal,1);assert.equal(persisted.ai,false);
  console.log(JSON.stringify({status:'passed',widths,context:{fillBlank:true,personalExample:true,offline:true},relations:{verified:true,confusion:true},health:{words:4,weak:scenario.weak},review:{contextRetry:true,confusion:true,mixedModes:new Set(review.modes).size},audioSupported:scenario.audio,pronunciationReuse:true,privacy:true,cloudSyncDomain:true,functionImpact:0},null,2));
}finally{try{cdp?.close();}catch(_){}browser.kill();await wait(250);try{fs.rmSync(profile,{recursive:true,force:true,maxRetries:5,retryDelay:100});}catch(_){}}})().catch((error)=>{console.error(error);process.exitCode=1;});
