/* Real-browser P57 QA: node tests/realtime-voice-coach-responsive.browser.js [url] */
'use strict';
const assert = require('node:assert/strict');
const childProcess = require('node:child_process');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

const edge = [path.join(process.env['ProgramFiles(x86)'] || '', 'Microsoft', 'Edge', 'Application', 'msedge.exe'), path.join(process.env.ProgramFiles || '', 'Microsoft', 'Edge', 'Application', 'msedge.exe'), path.join(process.env.LOCALAPPDATA || '', 'Microsoft', 'Edge', 'Application', 'msedge.exe')].find((candidate) => candidate && fs.existsSync(candidate));
if (!edge) throw new Error('Microsoft Edge is required for responsive browser QA.');
const baseUrl = process.argv[2] || 'http://127.0.0.1:4173/'; const port = 10600 + Math.floor(Math.random() * 70); const profile = path.join(os.tmpdir(), `klearn-p57-browser-${process.pid}`);
const browser = childProcess.spawn(edge, ['--headless=new', `--remote-debugging-port=${port}`, `--user-data-dir=${profile}`, '--disable-gpu', '--no-first-run', '--no-default-browser-check', 'about:blank'], { stdio: 'ignore', windowsHide: true });
const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
async function json(url, options) { const response = await fetch(url, options); if (!response.ok) throw new Error(`${response.status} ${url}`); return response.json(); }
async function connect(url) { const socket = new WebSocket(url); let id = 0; const pending = new Map(); await new Promise((resolve, reject) => { socket.onopen = resolve; socket.onerror = reject; }); socket.onmessage = (event) => { const message = JSON.parse(event.data); const request = pending.get(message.id); if (!request) return; pending.delete(message.id); message.error ? request.reject(new Error(message.error.message)) : request.resolve(message.result); }; return { send(method, params = {}) { return new Promise((resolve, reject) => { const next = ++id; pending.set(next, { resolve, reject }); socket.send(JSON.stringify({ id: next, method, params })); }); }, close() { socket.close(); } }; }
async function evaluate(cdp, expression) { const output = await cdp.send('Runtime.evaluate', { expression, returnByValue: true, awaitPromise: true }); if (output.exceptionDetails) throw new Error(output.exceptionDetails.exception?.description || output.exceptionDetails.text); return output.result.value; }
async function until(cdp, expression, attempts = 120) { for (let attempt = 0; attempt < attempts; attempt += 1) { if (await evaluate(cdp, expression)) return true; await wait(100); } return false; }

(async () => {
  try {
    let version; for (let attempt = 0; attempt < 50 && !version; attempt += 1) { try { version = await json(`http://127.0.0.1:${port}/json/version`); } catch (_) { await wait(100); } } if (!version) throw new Error('Could not start Edge.');
    const target = await json(`http://127.0.0.1:${port}/json/new?${encodeURIComponent(baseUrl)}`, { method: 'PUT' }); const cdp = await connect(target.webSocketDebuggerUrl); await cdp.send('Page.enable'); await cdp.send('Runtime.enable'); assert.equal(await until(cdp, `document.readyState==='complete' && Boolean(window.KLEARN_ROUTE_LOADER)`), true);
    const timestamp = new Date().toISOString(); const user = { id: 'p57-qa', fullName: 'Voice Coach QA', email: 'p57@local.test', level: 'TOPIK I', goals: ['conversation'], currentTopikLevel: 2, onboardingCompleted: true, createdAt: timestamp };
    await evaluate(cdp, `(() => { localStorage.setItem('klearn_users', ${JSON.stringify(JSON.stringify([user]))}); localStorage.setItem('klearn_session', ${JSON.stringify(JSON.stringify({ userId: user.id, createdAt: timestamp }))}); localStorage.setItem('klearn_progress', ${JSON.stringify(JSON.stringify({ [user.id]: { skills: { speaking: 20 }, stats: { streak: 1 }, daily: { date: timestamp.slice(0,10), tasks: {} }, pronunciationAttempts: [] } }))}); localStorage.setItem('klearn_settings', ${JSON.stringify(JSON.stringify({ users: { [user.id]: { theme: 'dark', language: 'vi' } } }))}); location.hash='realtime-voice-coach'; location.reload(); })()`);
    assert.equal(await until(cdp, `document.querySelectorAll('.coach-scenario-grid>button').length===4`), true, 'coach scenarios did not render');
    for (const width of [360, 768, 1024, 1440, 1920]) { await cdp.send('Emulation.setDeviceMetricsOverride', { width, height: 1100, deviceScaleFactor: 1, mobile: width < 768 }); await wait(80); const metrics = await evaluate(cdp, `(() => { const grid=document.querySelector('.coach-scenario-grid'); const buttons=[...grid.querySelectorAll('button')]; return { overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth || document.body.scrollWidth>document.body.clientWidth, dark:document.documentElement.dataset.theme==='dark', columns:getComputedStyle(grid).gridTemplateColumns.split(' ').length, touch:Math.min(...buttons.map((item)=>item.getBoundingClientRect().height)) }; })()`); assert.equal(metrics.overflow, false, `overflow at ${width}`); assert.equal(metrics.dark, true); assert.equal(metrics.columns, width <= 760 ? 1 : 2); assert.ok(metrics.touch >= 48); }
    await cdp.send('Emulation.setDeviceMetricsOverride', { width: 360, height: 1100, deviceScaleFactor: 1, mobile: true }); await evaluate(cdp, `(() => { Object.defineProperty(navigator,'onLine',{value:false,configurable:true}); document.querySelector('[data-coach-scenario="role-restaurant"]').click(); })()`); assert.equal(await until(cdp, `Boolean(document.getElementById('coachFallbackForm'))`), true);
    await evaluate(cdp, `(() => { const input=document.querySelector('#coachFallbackForm input'); input.value='비빔밥 하나 주세요'; document.getElementById('coachFallbackForm').dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})); })()`); assert.equal(await until(cdp, `Boolean(document.querySelector('.coach-feedback'))`), true, 'fallback feedback did not render');
    const result = await evaluate(cdp, `(() => { const records=JSON.parse(localStorage.getItem('klearn_voice_learning')||'{}')['p57-qa']||[]; const attempt=records.find((item)=>item.recordType==='attempt'); const coach=records.find((item)=>item.recordType==='coach-turn'); return { source:coach?.feedbackSource, audioStored:attempt?.audioStored, hasAudio:attempt && 'audioBlob' in attempt, componentCount:document.querySelectorAll('.coach-component-scores>div').length, disclosure:document.body.textContent.includes('không phải đánh giá người bản xứ chính thức') }; })()`);
    assert.equal(result.source, 'deterministic-fallback'); assert.equal(result.audioStored, false); assert.equal(result.hasAudio, false); assert.equal(result.componentCount, 3); assert.equal(result.disclosure, true);
    await evaluate(cdp, `window.KLEARN_APP.setView('voice-coach-journey')`); assert.equal(await until(cdp, `document.querySelectorAll('.coach-journey-grid article').length===2`), true); assert.equal(await evaluate(cdp, `document.body.textContent.includes('30 NGÀY') && document.body.textContent.includes('90 NGÀY')`), true);
    console.log('P57 browser: 360/768/1024/1440/1920, dark mode, no overflow, role-play, offline fallback, component scores, private persistence and 30/90 journey passed'); cdp.close();
  } finally { browser.kill(); await wait(200); fs.rmSync(profile, { recursive: true, force: true, maxRetries: 8, retryDelay: 100 }); }
})().catch((error) => { console.error(error); process.exitCode = 1; });
