/* Real-browser P1 UX QA: node tests/ux-p1-fixes-responsive.browser.js */
const assert = require('node:assert/strict');
const cp = require('node:child_process');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

const root = path.join(__dirname, '..');
const edge = [path.join(process.env['ProgramFiles(x86)'] || '', 'Microsoft', 'Edge', 'Application', 'msedge.exe'), path.join(process.env.ProgramFiles || '', 'Microsoft', 'Edge', 'Application', 'msedge.exe'), path.join(process.env.LOCALAPPDATA || '', 'Microsoft', 'Edge', 'Application', 'msedge.exe')].find((candidate) => candidate && fs.existsSync(candidate));
if (!edge) throw new Error('Microsoft Edge is required for UX P1 browser QA.');
const webPort = 17400 + Math.floor(Math.random() * 80); const debugPort = 17500 + Math.floor(Math.random() * 80); const baseUrl = `http://127.0.0.1:${webPort}/`; const profile = path.join(os.tmpdir(), `klearn-ux-p1-${process.pid}`);
const server = cp.spawn('python', ['-m', 'http.server', String(webPort), '--bind', '127.0.0.1'], { cwd: root, stdio: 'ignore', windowsHide: true });
const browser = cp.spawn(edge, ['--headless=new', `--remote-debugging-port=${debugPort}`, `--user-data-dir=${profile}`, '--disable-gpu', '--no-first-run', '--no-default-browser-check', 'about:blank'], { stdio: 'ignore', windowsHide: true });
const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
async function json(url, options) { const response = await fetch(url, options); if (!response.ok) throw new Error(`${response.status} ${url}`); return response.json(); }
async function connect(url) { const socket = new WebSocket(url); let id = 0; const pending = new Map(); await new Promise((resolve, reject) => { socket.onopen = resolve; socket.onerror = reject; }); socket.onmessage = (event) => { const message = JSON.parse(event.data); const request = pending.get(message.id); if (!request) return; pending.delete(message.id); message.error ? request.reject(new Error(message.error.message)) : request.resolve(message.result); }; return { send(method, params = {}) { return new Promise((resolve, reject) => { const next = ++id; pending.set(next, { resolve, reject }); socket.send(JSON.stringify({ id: next, method, params })); }); }, close() { socket.close(); } }; }
async function evaluate(cdp, expression) { const output = await cdp.send('Runtime.evaluate', { expression, returnByValue: true, awaitPromise: true }); if (output.exceptionDetails) throw new Error(output.exceptionDetails.exception?.description || output.exceptionDetails.text); return output.result.value; }
async function until(cdp, expression, attempts = 100) { for (let index = 0; index < attempts; index += 1) { if (await evaluate(cdp, expression)) return true; await wait(80); } return false; }

(async () => {
  let cdp;
  try {
    let version; for (let attempt = 0; attempt < 80 && !version; attempt += 1) { try { version = await json(`http://127.0.0.1:${debugPort}/json/version`); } catch (_) { await wait(100); } }
    if (!version) throw new Error('Could not start Edge.');
    const target = await json(`http://127.0.0.1:${debugPort}/json/new?${encodeURIComponent(`${baseUrl}#welcome`)}`, { method: 'PUT' }); cdp = await connect(target.webSocketDebuggerUrl); await cdp.send('Page.enable'); await cdp.send('Runtime.enable');
    assert.equal(await until(cdp, `document.readyState==='complete'&&Boolean(window.KLEARN_APP)`), true, 'app did not load');
    await evaluate(cdp, `localStorage.clear(); location.hash='#welcome'; location.reload()`); assert.equal(await until(cdp, `Boolean(document.querySelector('[data-view="sample-lesson"]'))`), true, 'welcome lacks sample lesson CTA');
    await evaluate(cdp, `document.querySelector('[data-view="sample-lesson"]').click()`); assert.equal(await until(cdp, `location.hash==='#sample-lesson'&&Boolean(document.querySelector('[data-sample-lesson]'))`), true, 'sample lesson did not open unauthenticated');
    const before = await evaluate(cdp, `localStorage.length`); await evaluate(cdp, `document.querySelector('[data-sample-next]').click()`); await wait(50); await evaluate(cdp, `document.querySelector('[data-sample-answer="right"]').click()`); assert.equal(await until(cdp, `document.body.textContent.includes('Đăng ký để lưu tiến độ')`), true, 'sample lesson did not offer registration'); assert.equal(await evaluate(cdp, `localStorage.length`), before, 'sample lesson changed local data');

    const user = { id: 'ux-p1-user', fullName: 'UX P1', email: 'ux-p1@local.test', level: 'Beginner', goals: ['topik'], currentTopikLevel: 1, targetTopikLevel: 3, onboardingCompleted: true, studyMinutesPerDay: 15, createdAt: new Date().toISOString() };
    await evaluate(cdp, `localStorage.setItem('klearn_users',${JSON.stringify(JSON.stringify([user]))});localStorage.setItem('klearn_session',${JSON.stringify(JSON.stringify({userId:user.id,createdAt:new Date().toISOString()}))});localStorage.setItem('klearn_progress',${JSON.stringify(JSON.stringify({[user.id]:{stats:{streak:2,lessonsCompleted:0,learningDays:0,wordsLearned:0},skills:{},lessonProgress:{},daily:{}}}))});location.hash='#home';location.reload()`);
    assert.equal(await until(cdp, `Boolean(window.KLEARN_APP?.state?.currentUser&&document.querySelector('.bla-shell'))`), true, 'authenticated home did not restore');
    await evaluate(cdp, `window.StudyCalendarService.activityByDay=()=>({'bad-date':{date:'not-a-date',minutes:4}});window.KLEARN_APP.setView('learning-progress')`); assert.equal(await until(cdp, `window.KLEARN_APP?.state?.currentView==='learning-progress'&&Boolean(document.querySelector('.bla-week-chart'))`), true, 'progress route did not render with invalid date'); assert.equal(await evaluate(cdp, `document.body.textContent.includes('Tiến bộ của bạn')`), true, 'progress fallback missing');
    await evaluate(cdp, `window.KLEARN_APP.setView('home');`); await cdp.send('Emulation.setDeviceMetricsOverride', { width: 360, height: 900, deviceScaleFactor: 1, mobile: true }); await wait(80); const cta = await evaluate(cdp, `(()=>{const button=document.querySelector('.bla-today-start-primary');const plan=document.querySelector('.bla-adaptive-today');return{visible:Boolean(button&&button.getBoundingClientRect().width),top:button?.getBoundingClientRect().top||0,planTop:plan?.getBoundingClientRect().top||0,overflow:document.documentElement.scrollWidth>innerWidth}})()`); assert.equal(cta.visible, true); assert.equal(cta.overflow, false); assert.ok(cta.top <= cta.planTop + 130, 'Today Plan CTA is not near the plan heading');
    await evaluate(cdp, `window.KLEARN_APP.setView('profile')`); assert.equal(await until(cdp, `Boolean(document.querySelector('.learner-profile-summary')&&document.querySelector('.profile-advanced'))`), true, 'profile progressive disclosure missing'); await evaluate(cdp, `window.KLEARN_APP.setView('ai-coach')`); assert.equal(await until(cdp, `Boolean(document.querySelector('.learner-assistant-summary')&&document.querySelector('.assistant-advanced'))`), true, 'assistant progressive disclosure missing');
    await evaluate(cdp, `const originalSet=localStorage.setItem.bind(localStorage);localStorage.setItem=(key,value)=>{if(key==='klearn_srs'){const e=new Error('quota');e.name='QuotaExceededError';throw e;}return originalSet(key,value)};const payload={};payload[window.KLEARN_APP.state.currentUser.id]=[{wordId:'keep-me',korean:'유지',status:'learning'}];window.KLEARN_APP.storage.set('klearn_srs',payload);`); assert.equal(await until(cdp, `Boolean(document.querySelector('.storage-recovery-banner'))`), true, 'quota recovery banner missing'); assert.equal(await evaluate(cdp, `window.KLEARN_APP.storage.lastFailedWrite.value[ window.KLEARN_APP.state.currentUser.id ][0].wordId`), 'keep-me', 'failed SRS data was not retained for retry');
    console.log(JSON.stringify({ status: 'passed', scenarios: ['sample-lesson', 'progress-invalid-date', 'today-plan-360', 'profile-collapse', 'assistant-collapse', 'srs-quota-recovery'] }));
  } finally { cdp?.close(); browser.kill(); server.kill(); try { fs.rmSync(profile, { recursive: true, force: true, maxRetries: 12, retryDelay: 200 }); } catch (_) {} }
})().catch((error) => { console.error(error); process.exitCode = 1; });
