window.KLEARN_LOCALES = window.KLEARN_LOCALES || {};
window.KLEARN_LOCALES.en = {
  label: 'English', short: 'EN', htmlLang: 'en',
  keys: {
    'nav.home': 'Home', 'nav.learn': 'Learn', 'nav.review': 'Review', 'nav.practice': 'Practice', 'nav.profile': 'Profile',
    'auth.login': 'Sign in', 'auth.register': 'Create account', 'auth.welcome': 'Welcome back', 'auth.email': 'Email', 'auth.password': 'Password', 'auth.forgot': 'Forgot password?',
    'auth.start': 'Start learning', 'auth.hasAccount': 'Already have an account?', 'auth.noAccount': "Don't have an account?",
    'theme.title': 'Appearance', 'theme.description': 'Choose the display that feels most comfortable.', 'theme.system': 'System', 'theme.light': 'Light', 'theme.dark': 'Dark', 'theme.systemDesc': 'Follow device appearance', 'theme.lightDesc': 'Bright and easy to read', 'theme.darkDesc': 'Gentle on the eyes at night',
    'language.title': 'Language', 'language.vi': 'Vietnamese', 'language.en': 'English', 'language.zhCN': 'Chinese (Simplified)',
    'common.back': 'Back', 'common.result': 'Results', 'common.start': 'Start', 'common.save': 'Save', 'common.cancel': 'Cancel', 'common.retry': 'Try again',
    'home.greeting': 'Hello, {name} 👋', 'home.prompt': 'What would you like to learn today?', 'home.todayGoal': "Today's goal",
    'home.path': 'Personal learning path', 'home.today': 'today', 'home.srsReview': 'SRS review', 'home.practiceTest': 'Practice test', 'home.notRequired': "You don't have to complete everything.", 'home.continueLearning': 'Continue learning', 'home.todayReview': "Today's review", 'home.reviewTip': 'Review at the right time to remember longer.', 'home.reviewNow': 'Review now', 'home.todayPractice': "Today's practice", 'home.koreanPractice': 'Korean practice', 'home.notCompleted': "You haven't completed any practice tests yet.", 'home.reviewDue': 'Review {count} due {unit}', 'home.reviewDueReason': 'Start with due words to keep your SRS on track.', 'home.recommended': 'Recommended for you', 'home.learningPath': 'Learning path', 'home.pathSubtitle': 'From the foundations to exam preparation', 'home.locked': 'Locked',
    'welcome.title': 'Korean learning designed for Vietnamese learners.', 'welcome.point.level': 'Learn by level.', 'welcome.point.goal': 'Learn by goal.', 'welcome.point.progress': 'Improve every day.',
    'auth.registerSubtitle': 'It only takes a few minutes for TH-Tiếng Hàn to understand your goals.', 'auth.loginSubtitle': 'Continue your personalized Korean learning journey.',
    'onboarding.goalsTitle': 'Why are you learning Korean?', 'onboarding.goalsSubtitle': 'You can choose more than one goal.', 'onboarding.levelTitle': 'What is your current Korean level?', 'onboarding.levelSubtitle': 'Choose the closest option. You can take a placement test.', 'onboarding.placementTitle': 'Placement test', 'onboarding.placementSubtitle': 'Choose one answer. Results are used only to suggest an MVP learning path.',
    'speaking.title': 'Speaking Practice', 'writing.title': 'Writing Practice', 'profile.settings': 'Settings', 'profile.language': 'Language', 'profile.appearance': 'Appearance'
  },
  phrases: {
    'Trang chủ':'Home','Học':'Learn','Ôn tập':'Review','Luyện tập':'Practice','Cá nhân':'Profile','Đăng nhập':'Sign in','Đăng ký':'Create account','Email':'Email','Mật khẩu':'Password','Quên mật khẩu?':'Forgot password?','Bắt đầu học':'Start learning','Đã có tài khoản?':'Already have an account?','Chưa có tài khoản?':'Don\'t have an account?','Giao diện':'Appearance','Ngôn ngữ':'Language','Theo thiết bị':'System','Hệ thống':'System','Sáng':'Light','Tối':'Dark','Tiếng Việt':'Vietnamese','English':'English','中文（简体）':'Chinese (Simplified)','Chào mừng trở lại 👋':'Welcome back 👋','Bắt đầu lộ trình của bạn':'Start your learning journey','Kết quả':'Results','Luyện nói':'Speaking Practice','Luyện viết':'Writing Practice','Quay lại':'Back','Lưu':'Save','Hủy':'Cancel','Thử lại':'Try again','Bắt đầu':'Start','Hỗ trợ đọc Hangul':'Hangul reading support','Tiến bộ mỗi ngày.':'Improve every day.','Học theo trình độ.':'Learn by level.','Học theo mục tiêu.':'Learn by goal.'
  }
};
Object.assign(window.KLEARN_LOCALES.en.phrases, {
  'Tiếng Hàn được thiết kế dành riêng cho người Việt.':'Korean learning designed for Vietnamese learners.', 'Học theo trình độ.':'Learn by level.', 'Học theo mục tiêu.':'Learn by goal.', 'Tiến bộ mỗi ngày.':'Improve every day.',
  'Từ vựng TOPIK 1–6':'TOPIK 1–6 Vocabulary', 'Ôn tập từ vựng':'Vocabulary Review', 'Flashcard SRS':'SRS Flashcards', 'Quên':'Forgot', 'Khó':'Hard', 'Nhớ':'Remembered', 'Rất dễ':'Easy',
  'Đúng rồi!':'Correct!', 'Chưa đúng':'Not quite', 'Chính xác':'Correct', 'Chưa chính xác.':'Not quite.', 'Đáp án đúng:':'Correct answer:', 'Giải thích':'Explanation', 'Mẹo phát âm':'Pronunciation tip', 'Gợi ý trả lời':'Suggested response', 'Yêu cầu:':'Requirements:', 'Từ gợi ý':'Suggested words', 'Nộp bài':'Submit', 'Bài viết đã lưu':'Writing saved', 'Bài mẫu':'Sample answer', 'Lịch sử luyện tập':'Practice history', 'Không có bộ đề phù hợp. Hãy thử thay đổi bộ lọc.':'No matching practice sets. Try changing the filters.', 'Không có từ phù hợp':'No matching words', 'Mở kho từ vựng':'Open vocabulary', 'Kiểm tra vốn từ đã học':'Test learned vocabulary', 'Luyện nhanh':'Quick practice', 'Bắt đầu luyện nhanh':'Start quick practice', 'Chọn đề':'Choose a test', 'Làm đề':'Start test', 'Làm lại':'Try again', 'Nghe':'Listening', 'Nói':'Speaking', 'Đọc':'Reading', 'Viết':'Writing', 'Ngữ pháp':'Grammar', 'Từ vựng':'Vocabulary', 'Mục tiêu':'Goal', 'Cấp độ':'Level', 'Trạng thái':'Status', 'Tất cả':'All', 'Dễ':'Easy', 'Trung bình':'Medium', 'Khó':'Hard', 'Bỏ qua':'Skip', 'Hoàn thành':'Finish', 'Tiếp tục':'Continue', 'Tiếp theo':'Next', 'Xem kết quả':'View results', 'Đăng xuất':'Sign out'
});
Object.assign(window.KLEARN_LOCALES.en.keys, {
  'common.continue': 'Continue', 'romanization.label': 'Romanization', 'romanization.on': 'On', 'romanization.off': 'Off', 'romanization.actual': 'Natural reading', 'exercise.tapHint': 'Tap the words below', 'lesson.grammarEyebrow': 'Beginner grammar', 'lesson.title': 'Topic particles', 'home.streak': 'streak', 'home.toReview': 'to review', 'home.toCheck': 'to check', 'home.continueGrammar': ' 은/는 and 이/가',
  'home.listening': 'Listening', 'home.speaking': 'Speaking', 'home.shortWriting': 'Short writing', 'home.latestScore': 'Latest score', 'home.reviewNowAction': 'Practice now', 'home.quickPractice': 'Quick practice', 'home.start': 'Start',
  'lesson.courseEyebrow': 'MVP lesson', 'lesson.objective': 'Goal: recognize the structure, study examples, and move straight into a matching practice.', 'lesson.studyGuide': 'Suggested study steps', 'lesson.listenSample': 'Read or listen to the Korean example.', 'lesson.compareMeaning': 'Compare the meaning and usage in English.', 'lesson.practiceSkill': 'Practice by skill to check your understanding.', 'lesson.compareTitle': '🧠 Compare the pattern', 'lesson.compareBody': 'In Korean, 은/는 follows a noun to mark the topic of a sentence. It is roughly similar to “as for” or “is” in English.', 'lesson.rule': 'Rule', 'lesson.withBatchim': 'With a final consonant (batchim) + 은', 'lesson.withoutBatchim': 'Without a final consonant + 는', 'lesson.examples': 'Examples', 'lesson.arrange': '🧩 Arrange the sentence', 'lesson.createSentence': 'Create: “I am Vietnamese.”', 'lesson.reset': 'Reset', 'lesson.check': 'Check', 'lesson.close': 'Close lesson', 'lesson.back': 'Back', 'lesson.complete': 'Complete lesson', 'lesson.completed': 'Completed ✓', 'lesson.startPractice': 'Start {lesson} practice', 'lesson.audio': 'Listen to Korean pronunciation'
});
Object.assign(window.KLEARN_LOCALES.en.phrases, { 'Độ khó': 'Difficulty', 'Chạm vào các từ bên dưới': 'Tap the words below', 'Phiên âm: Bật': 'Romanization: On', 'Phiên âm: Tắt': 'Romanization: Off' });
