window.KLEARN_LOCALES = window.KLEARN_LOCALES || {};
window.KLEARN_LOCALES.en = {
  label: 'English', short: 'EN', htmlLang: 'en',
  keys: {
    'nav.home': 'Home', 'nav.learn': 'Learn', 'nav.topik': 'TOPIK', 'nav.review': 'Review', 'nav.assistant': 'Tutor', 'nav.practice': 'Practice', 'nav.profile': 'Profile',
    'auth.login': 'Sign in', 'auth.register': 'Create account', 'auth.welcome': 'Welcome back', 'auth.email': 'Email', 'auth.password': 'Password', 'auth.forgot': 'Forgot password?',
    'auth.start': 'Start learning', 'auth.hasAccount': 'Already have an account?', 'auth.noAccount': "Don't have an account?",
    'theme.title': 'Appearance', 'theme.description': 'Choose the display that feels most comfortable.', 'theme.system': 'System', 'theme.light': 'Light', 'theme.dark': 'Dark', 'theme.systemDesc': 'Follow device appearance', 'theme.lightDesc': 'Bright and easy to read', 'theme.darkDesc': 'Gentle on the eyes at night',
    'language.title': 'Language', 'language.vi': 'Vietnamese', 'language.en': 'English', 'language.zhCN': 'Chinese (Simplified)',
    'common.back': 'Back', 'common.result': 'Results', 'common.start': 'Start', 'common.save': 'Save', 'common.cancel': 'Cancel', 'common.retry': 'Try again',
    'home.greeting': 'Hello, {name} 👋', 'home.prompt': 'What would you like to learn today?', 'home.todayGoal': "Today's goal",
    'home.path': 'Personal learning path', 'home.today': 'today', 'home.srsReview': 'SRS review', 'home.practiceTest': 'Practice test', 'home.notRequired': "You don't have to complete everything.", 'home.continueLearning': 'Continue learning', 'home.todayReview': "Today's review", 'home.reviewTip': 'Review at the right time to remember longer.', 'home.reviewNow': 'Review now', 'home.todayPractice': "Today's practice", 'home.koreanPractice': 'Korean practice', 'home.notCompleted': "You haven't completed any practice tests yet.", 'home.reviewDue': 'Review {count} due {unit}', 'home.reviewDueReason': 'Start with due words to keep your SRS on track.', 'home.recommended': 'Recommended for you', 'home.learningPath': 'Learning path', 'home.pathSubtitle': 'From the foundations to exam preparation', 'home.locked': 'Locked',
    'welcome.title': 'Korean learning designed for Vietnamese learners.', 'welcome.point.level': 'Learn by level.', 'welcome.point.goal': 'Learn by goal.', 'welcome.point.progress': 'Improve every day.',
    'auth.registerSubtitle': 'It only takes a few minutes for TH-Tiếng Hàn to understand your goals.', 'auth.loginSubtitle': 'Continue your personalized Korean learning journey.',
    'onboarding.goalsTitle': 'Why are you learning Korean?', 'onboarding.goalsSubtitle': 'You can choose more than one goal.', 'onboarding.levelTitle': 'What is your current Korean level?', 'onboarding.levelSubtitle': 'Choose the closest option. You can take a placement test.', 'onboarding.placementTitle': 'Placement test', 'onboarding.placementSubtitle': 'Choose one answer. Results are used only to suggest an MVP learning path.',
    'speaking.title': 'Speaking Practice', 'writing.title': 'Writing Practice', 'profile.settings': 'Settings', 'profile.language': 'Language', 'profile.appearance': 'Appearance'
  },
  phrases: {
    'Trang chủ':'Home','Học':'Learn','Ôn tập':'Review','Luyện tập':'Practice','Cá nhân':'Profile','Đăng nhập':'Sign in','Đăng ký':'Create account','Email':'Email','Mật khẩu':'Password','Quên mật khẩu?':'Forgot password?','Bắt đầu học':'Start learning','Đã có tài khoản?':'Already have an account?','Chưa có tài khoản?':'Don\'t have an account?','Giao diện':'Appearance','Ngôn ngữ':'Language','Theo thiết bị':'System','Hệ thống':'System','Sáng':'Light','Tối':'Dark','Tiếng Việt':'Vietnamese','English':'English','中文（简体）':'Chinese (Simplified)','Chào mừng trở lại 👋':'Welcome back 👋','Bắt đầu lộ trình của bạn':'Start your learning journey','Kết quả':'Results','Luyện nói':'Speaking Practice','Luyện viết':'Writing Practice','Quay lại':'Back','Lưu':'Save','Hủy':'Cancel','Thử lại':'Try again','Bắt đầu':'Start','Hỗ trợ đọc Hangul':'Hangul reading support','Tiến bộ mỗi ngày.':'Improve every day.','Học theo trình độ.':'Learn by level.','Học theo mục tiêu.':'Learn by goal.'
  }
};
Object.assign(window.KLEARN_LOCALES.en.phrases, {
  'Tiếng Hàn được thiết kế dành riêng cho người Việt.':'Korean learning designed for Vietnamese learners.', 'Học theo trình độ.':'Learn by level.', 'Học theo mục tiêu.':'Learn by goal.', 'Tiến bộ mỗi ngày.':'Improve every day.',
  'Từ vựng TOPIK 1–6':'TOPIK 1–6 Vocabulary', 'Ôn tập từ vựng':'Vocabulary Review', 'Flashcard SRS':'SRS Flashcards', 'Quên':'Forgot', 'Khó':'Hard', 'Nhớ':'Remembered', 'Rất dễ':'Easy',
  'Đúng rồi!':'Correct!', 'Chưa đúng':'Not quite', 'Chính xác':'Correct', 'Chưa chính xác.':'Not quite.', 'Đáp án đúng:':'Correct answer:', 'Giải thích':'Explanation', 'Mẹo phát âm':'Pronunciation tip', 'Gợi ý trả lời':'Suggested response', 'Yêu cầu:':'Requirements:', 'Từ gợi ý':'Suggested words', 'Nộp bài':'Submit', 'Bài viết đã lưu':'Writing saved', 'Bài mẫu':'Sample answer', 'Lịch sử luyện tập':'Practice history', 'Không có bộ đề phù hợp. Hãy thử thay đổi bộ lọc.':'No matching practice sets. Try changing the filters.', 'Không có từ phù hợp':'No matching words', 'Mở kho từ vựng':'Open vocabulary', 'Kiểm tra vốn từ đã học':'Test learned vocabulary', 'Luyện nhanh':'Quick practice', 'Bắt đầu luyện nhanh':'Start quick practice', 'Chọn đề':'Choose a test', 'Làm đề':'Start test', 'Làm lại':'Try again', 'Nghe':'Listening', 'Nói':'Speaking', 'Đọc':'Reading', 'Viết':'Writing', 'Ngữ pháp':'Grammar', 'Từ vựng':'Vocabulary', 'Mục tiêu':'Goal', 'Cấp độ':'Level', 'Trạng thái':'Status', 'Tất cả':'All', 'Dễ':'Easy', 'Trung bình':'Medium', 'Khó':'Hard', 'Bỏ qua':'Skip', 'Hoàn thành':'Finish', 'Tiếp tục':'Continue', 'Tiếp theo':'Next', 'Xem kết quả':'View results', 'Đăng xuất':'Sign out'
});
Object.assign(window.KLEARN_LOCALES.en.phrases, {
  'Khóa học':'Courses','Khóa học theo lộ trình':'Structured courses','Chọn đúng chặng học; tiến độ được lấy trực tiếp từ các bài đã hoàn thành.':'Choose the right stage; progress comes directly from completed lessons.','Nền tảng tiếng Hàn':'Korean foundations','Tiếng Hàn sơ cấp':'Beginner Korean','Tiếng Hàn trung cấp':'Intermediate Korean','Tiếng Hàn nâng cao':'Advanced Korean','Chuẩn bị thi TOPIK':'TOPIK preparation','Foundation':'Foundation','Beginner':'Beginner','Intermediate':'Intermediate','Advanced':'Advanced','Exam preparation':'Exam preparation','Đã hoàn thành':'Completed','Đang học':'In progress','Chưa bắt đầu':'Not started','Chiến thuật và mock exam':'Strategies and mock exams','Tiếp tục khóa học':'Continue course','Xem khóa học':'View course','Mở chiến thuật TOPIK':'Open TOPIK strategies','Bài học':'Lessons','Bài tiếp theo':'Next lesson','Mở Chiến thuật TOPIK':'Open TOPIK Strategy Lab','TOPIK Strategy Lab':'TOPIK Strategy Lab','Chiến thuật TOPIK':'TOPIK strategies','Học cách nhận diện và xử lý từng dạng câu trước khi bấm giờ làm đề.':'Learn to recognize and solve each question type before starting timed tests.','Đã luyện':'Practiced','Chưa luyện':'Not practiced','Nhận biết dạng câu':'Recognize the question type','Mục tiêu câu hỏi':'Question objective','4 bước xử lý':'4-step method','Lỗi thường gặp':'Common mistakes','Luyện 5 câu':'Practice 5 questions','Luyện 10 câu':'Practice 10 questions','Nói không phải là phần thi TOPIK chuẩn hóa.':'Speaking is not a standardized TOPIK section.','Bấm vào từ tiếng Hàn để xem nhanh nghĩa.':'Tap a Korean word for a quick meaning.','Chưa có dữ liệu từ này.':'No dictionary entry for this word.','Hỏi trợ lý':'Ask tutor','Thêm vào SRS':'Add to SRS','Mở từ điển đầy đủ':'Open full dictionary','Từ liên quan':'Related word','Tóm tắt':'Summary','Giải thích ngắn':'Short explanation','Câu ví dụ':'Example sentence','Bước':'Step','Quick Check':'Quick Check','Practice':'Practice','Tổng kết':'Summary','Kiểm tra đáp án':'Check answer','Đáp án của bạn':'Your answer','Chọn đáp án để tiếp tục.':'Choose an answer to continue.','Chính xác — tiếp tục nhé!':'Correct — keep going!','Hãy xem lại gợi ý rồi thử lại.':'Review the hint and try again.','Lưu tiến độ bài học':'Save lesson progress','Bài học đã hoàn thành.':'Lesson completed.','Tiến độ khóa học':'Course progress','Không có bài học trong khóa này.':'There are no lessons in this course.'
});
Object.assign(window.KLEARN_LOCALES.en.phrases, { 'Mở AI Gia sư TamHoanq': 'Open AI Korean Tutor', 'AI Gia sư TamHoanq': 'AI Korean Tutor', 'Hỗ trợ học tiếng Hàn': 'Korean learning support', 'Cuộc trò chuyện mới': 'New conversation', 'Đóng AI': 'Close AI', 'Bài này': 'This lesson', 'Sửa câu': 'Correct a sentence', 'Tạo bài tập': 'Create exercise', 'Bạn': 'You', 'AI đang suy nghĩ...': 'Tutor is thinking...', 'Gửi câu hỏi AI': 'Send AI question' });
Object.assign(window.KLEARN_LOCALES.en.phrases, { 'Tìm bằng Hangul, romanization hoặc nghĩa tiếng Việt.': 'Search by Hangul, romanization, or Vietnamese meaning.', 'Từ điển 1.000+ mục': 'Dictionary entries', 'Tất cả loại từ': 'All parts of speech' });
Object.assign(window.KLEARN_LOCALES.en.keys, {
  'common.continue': 'Continue', 'romanization.label': 'Romanization', 'romanization.on': 'On', 'romanization.off': 'Off', 'romanization.actual': 'Natural reading', 'exercise.tapHint': 'Tap the words below', 'lesson.grammarEyebrow': 'Beginner grammar', 'lesson.title': 'Topic particles', 'home.streak': 'streak', 'home.toReview': 'to review', 'home.toCheck': 'to check', 'home.continueGrammar': ' 은/는 and 이/가',
  'home.listening': 'Listening', 'home.speaking': 'Speaking', 'home.shortWriting': 'Short writing', 'home.latestScore': 'Latest score', 'home.reviewNowAction': 'Practice now', 'home.quickPractice': 'Quick practice', 'home.start': 'Start', 'ai.title': 'AI Korean Tutor', 'ai.subtitle': 'Korean learning support', 'ai.placeholder': 'Ask your Korean tutor...', 'ai.thinking': 'Tutor is thinking...', 'ai.privacy': 'AI may use this chat and learning progress to personalize suggestions. Passwords and tokens are never sent.', 'ai.empty': 'Ask about grammar, vocabulary, pronunciation, or the current lesson.', 'ai.notConfigured': 'AI is not configured yet.', 'ai.offline': 'AI needs an Internet connection. You can still use the offline dictionary and phrasebook.',
  'lesson.courseEyebrow': 'MVP lesson', 'lesson.objective': 'Goal: recognize the structure, study examples, and move straight into a matching practice.', 'lesson.studyGuide': 'Suggested study steps', 'lesson.listenSample': 'Read or listen to the Korean example.', 'lesson.compareMeaning': 'Compare the meaning and usage in English.', 'lesson.practiceSkill': 'Practice by skill to check your understanding.', 'lesson.compareTitle': '🧠 Compare the pattern', 'lesson.compareBody': 'In Korean, 은/는 follows a noun to mark the topic of a sentence. It is roughly similar to “as for” or “is” in English.', 'lesson.rule': 'Rule', 'lesson.withBatchim': 'With a final consonant (batchim) + 은', 'lesson.withoutBatchim': 'Without a final consonant + 는', 'lesson.examples': 'Examples', 'lesson.arrange': '🧩 Arrange the sentence', 'lesson.createSentence': 'Create: “I am Vietnamese.”', 'lesson.reset': 'Reset', 'lesson.check': 'Check', 'lesson.close': 'Close lesson', 'lesson.back': 'Back', 'lesson.complete': 'Complete lesson', 'lesson.completed': 'Completed ✓', 'lesson.startPractice': 'Start {lesson} practice', 'lesson.audio': 'Listen to Korean pronunciation', 'ai.fab': 'Open AI Korean Tutor', 'ai.newChat': 'New conversation', 'ai.close': 'Close AI', 'ai.lesson': 'This lesson', 'ai.correct': 'Correct a sentence', 'ai.translate': 'Translate', 'ai.exercise': 'Create exercise', 'ai.you': 'You', 'ai.send': 'Send', 'ai.error': 'Unable to connect to AI. Please try again.'
});
Object.assign(window.KLEARN_LOCALES.en.phrases, { 'Độ khó': 'Difficulty', 'Chạm vào các từ bên dưới': 'Tap the words below', 'Phiên âm: Bật': 'Romanization: On', 'Phiên âm: Tắt': 'Romanization: Off' });
Object.assign(window.KLEARN_LOCALES.en.phrases, { 'Từ điển': 'Dictionary', 'Tra từ tiếng Hàn': 'Korean dictionary', 'Dịch & Đặt câu': 'Translate & make sentences', 'Sổ tay câu': 'Phrasebook', 'Tra gần đây': 'Recent searches', 'Tất cả loại từ': 'All parts of speech', 'Không tìm thấy mục phù hợp.': 'No matching entries.', 'Lưu từ': 'Save word', 'Đã lưu': 'Saved', 'Thêm vào ôn tập': 'Add to review', 'Ví dụ': 'Examples', 'Chưa có ví dụ cho mục này.': 'No examples yet.', 'Câu thông dụng': 'Common phrases', 'Các mẫu câu có thể dùng offline.': 'Useful phrases available offline.', 'Công cụ ngôn ngữ': 'Language tools', 'Tra từ, dịch cụm từ và câu với dữ liệu offline.': 'Look up words and translate phrases and sentences offline.', 'Dịch từ': 'Translate from', 'Sang': 'To', 'Ngữ cảnh': 'Context', 'Chung': 'General', 'Cách nói': 'Register', 'Lịch sự': 'Polite', 'Thân mật': 'Casual', 'Trang trọng': 'Formal', 'Nhập từ, cụm từ hoặc câu...': 'Enter a word, phrase, or sentence...', 'Dịch': 'Translate', 'Sao chép': 'Copy', 'Sao chép tiếng Hàn': 'Copy Korean', 'Lưu câu': 'Save sentence', 'Luyện nói': 'Practice speaking', 'Đã thêm vào bộ ôn tập.': 'Added to review.', 'Đã lưu câu.': 'Sentence saved.' });
Object.assign(window.KLEARN_LOCALES.en.phrases, { 'Lý thuyết': 'Theory', 'Lộ trình': 'Roadmap', 'Luyện TOPIK': 'TOPIK practice' });
Object.assign(window.KLEARN_LOCALES.en.phrases, { 'Ôn tập thông minh':'Smart Review','Tìm kiếm toàn app':'Search the app','Phân tích tiến độ':'Progress analytics','Tuần này của bạn':'Your week','Đang đồng bộ...':'Syncing...','✓ Đã đồng bộ':'✓ Synced','Ngoại tuyến':'Offline','Chỉ lưu trên thiết bị':'Device only','Tạo phiên ôn thông minh':'Create Smart Review','Báo cáo tuần':'Weekly report','Phân tích theo kỹ năng':'Skill breakdown','Phân tích theo dạng câu hỏi':'Question-type analysis','Điểm mạnh':'Strength','Cần cải thiện':'Needs improvement','Nhắc học':'Learning reminders','Nhắc từ SRS đến hạn':'Remind me about due SRS','Nhắc kế hoạch hôm nay':'Remind me about today’s plan','Nhắc duy trì streak':'Remind me to keep my streak','Bài có hoạt động':'Lessons with activity','Từ thành thạo':'Mastered words','Đề đã làm':'Tests completed','Phút học':'Study minutes','Global Search':'Global Search','TOPIK Analytics':'TOPIK Analytics','Weekly Insights':'Weekly Insights','Tạo phiên ôn':'Create review session','Câu đã chạm':'Lessons touched','Cần củng cố':'Needs practice'});
Object.assign(window.KLEARN_LOCALES.en.phrases, { 'Đăng ký local':'Create local account','Đăng nhập local':'Local sign in','Đăng ký cloud':'Cloud sign up','Đăng nhập cloud':'Cloud sign in','☁ Đăng ký cloud':'☁ Cloud sign up','☁ Đăng nhập cloud':'☁ Cloud sign in','Đồng bộ đa thiết bị':'Multi-device sync','Kết nối tài khoản cloud':'Connect cloud account','Cloud chưa được cấu hình hoặc đang ngoại tuyến':'Cloud is not configured or is offline','Dữ liệu hiện chỉ được lưu trên thiết bị này. Hãy chủ động đăng nhập hoặc đăng ký Supabase để liên kết đúng tài khoản local hiện tại.':'Your data is currently stored only on this device. Sign in or sign up to Supabase to explicitly link this local account.','Email cloud':'Cloud email','Mật khẩu cloud':'Cloud password','Đăng nhập & liên kết':'Sign in and link','Đăng ký & liên kết':'Sign up and link','Đã kết nối':'Connected','Đồng bộ ngay':'Sync now','Ngắt cloud':'Disconnect cloud','dữ liệu local vẫn là nguồn hoạt động chính.':'local data remains the active source.','Đã ngắt cloud. Dữ liệu local vẫn được giữ nguyên.':'Cloud disconnected. Local data was preserved.','☁ Cloud Account':'☁ Cloud Account','↻ Đang đồng bộ':'↻ Syncing','☁ Đã đồng bộ':'☁ Synced','💾 Ngoại tuyến':'💾 Offline','⚠ Chưa đồng bộ':'⚠ Not synced','Lỗi đồng bộ':'Sync error','Đã kết nối cloud và đồng bộ dữ liệu.':'Cloud connected and data synced.','Đã kết nối cloud. Đồng bộ chưa hoàn tất; dữ liệu local vẫn an toàn.':'Cloud connected. Sync is not complete; local data remains safe.','Hãy mở email xác nhận Supabase rồi quay lại đăng nhập cloud.':'Open the Supabase confirmation email, then return to cloud sign-in.','Tài khoản cloud đã được tạo, liên kết và đồng bộ.':'Cloud account created, linked, and synced.','Tài khoản cloud đã được liên kết. Đồng bộ chưa hoàn tất; dữ liệu local vẫn an toàn.':'Cloud account linked. Sync is not complete; local data remains safe.'});
Object.assign(window.KLEARN_LOCALES.en.phrases, {
  'Học tập':'Learn','TOPIK':'TOPIK','Trợ lý':'Tutor','Hồ sơ':'Profile','Hôm nay học gì?':'What should I learn today?','Giữ nhịp đều, mỗi ngày một bước.':'Build consistency, one step each day.','Tiến độ mục tiêu':'Goal progress','Xem lộ trình →':'View roadmap →','Kế hoạch cá nhân':'Personal plan','Nhiệm vụ hôm nay':"Today's mission",'Xem lộ trình':'View roadmap','Tiếp tục học':'Continue learning','Từ cần ôn':'Words to review','Kỹ năng cần cải thiện':'Skill to improve','Luyện ngay':'Practice now','Ôn ngay':'Review now','Ôn nhanh':'Quick review','Phiên học ngắn':'Short study session','Chọn thời lượng':'Choose duration','Sổ từ':'Word notebook','Mẫu câu thực tế':'Practical phrases',
  'Bài học TOPIK':'TOPIK lessons','Từ vựng':'Vocabulary','Luyện nghe':'Listening practice','Luyện nói':'Speaking practice','Luyện viết':'Writing practice','Đọc hiểu':'Reading practice','Luyện viết chữ':'Handwriting practice','Tiếng Hàn thực tế':'Practical Korean','Tiến độ cấp hiện tại':'Current level progress','Xem bài học':'View lessons','Mỗi ngày một phiên ngắn':'One short session a day','Ôn 5–20 phút':'Review for 5–20 minutes','Sổ từ vựng cá nhân':'Personal vocabulary notebook','Từ đã lưu':'Saved words','Test nhanh':'Quick test',
  'Tiếng Hàn trong đời sống':'Korean for daily life','Học để sử dụng':'Learn for real situations','Chọn bối cảnh phù hợp với mục tiêu của bạn.':'Choose a context that matches your goal.','XKLĐ':'Overseas work','Du học':'Study abroad','Công sở':'Workplace','Mẫu câu dùng ngay':'Ready-to-use phrases','Xem tất cả':'View all',
  'Báo cáo tiến bộ':'Progress reports','Kết quả học tập':'Learning results','Điểm trung bình':'Average score','Điểm cần tập trung':'Focus area','Báo cáo tuần / tháng':'Weekly / monthly report','Trợ lý học tập':'Learning assistant','Tóm tắt tiến độ':'Progress summary','Sổ lỗi của tôi':'My error notebook','Hồ sơ học tập':'Learning profile','Xu hướng học tập':'Learning patterns','Gợi ý ôn tập':'Review suggestions',
  'Kho đề TOPIK':'TOPIK test bank','Thi thử full đề':'Full mock exam','Đề ngẫu nhiên':'Random test','Đề nâng cao':'Advanced tests','Theo chủ đề':'By topic','Luyện lỗi sai':'Review mistakes','Đề đã lưu':'Saved tests','Lịch sử':'History','Phân tích TOPIK':'TOPIK analytics','Kế hoạch luyện thi':'Exam preparation plan','Điều chỉnh':'Adjust'
  ,'Phiên rút gọn để lấy lại nhịp học.':'A shorter session to rebuild your study rhythm.','Ba hoạt động quan trọng nhất cho hôm nay.':'The three most important activities for today.','Theo tiến độ hiện tại':'Based on your current progress','Xem lại kế hoạch':'Review plan','Bắt đầu học':'Start learning','Mục tiêu cá nhân':'Personal goal','Mục tiêu & deadline':'Goal & deadline','Tạo lộ trình phù hợp':'Create a suitable path','Tổng hợp tuần':'Weekly overview','Chủ đề liên quan:':'Related topics:','Liên kết chủ đề yếu: +2':'Weak topic links: +2','Chưa phát hiện điểm yếu rõ':'No clear weak areas yet'
});
