// Local, extensible locale resource. Korean learning source text is never translated.
window.KLEARN_LOCALES = window.KLEARN_LOCALES || {};
window.KLEARN_LOCALES.vi = {
  label: 'Tiếng Việt', short: 'VI', htmlLang: 'vi',
  keys: {
    'nav.home': 'Trang chủ', 'nav.learn': 'Học', 'nav.review': 'Ôn tập', 'nav.practice': 'Luyện tập', 'nav.profile': 'Cá nhân',
    'auth.login': 'Đăng nhập', 'auth.register': 'Đăng ký', 'auth.welcome': 'Chào mừng trở lại', 'auth.email': 'Email', 'auth.password': 'Mật khẩu', 'auth.forgot': 'Quên mật khẩu?',
    'auth.start': 'Bắt đầu học', 'auth.hasAccount': 'Đã có tài khoản?', 'auth.noAccount': 'Chưa có tài khoản?',
    'theme.title': 'Giao diện', 'theme.description': 'Chọn cách hiển thị bạn thấy thoải mái nhất.', 'theme.system': 'Theo thiết bị', 'theme.light': 'Sáng', 'theme.dark': 'Tối', 'theme.systemDesc': 'Tự theo giao diện thiết bị', 'theme.lightDesc': 'Nền sáng, dễ đọc', 'theme.darkDesc': 'Dịu mắt khi học ban đêm',
    'language.title': 'Ngôn ngữ', 'language.vi': 'Tiếng Việt', 'language.en': 'English', 'language.zhCN': '中文（简体）',
    'common.back': 'Quay lại', 'common.result': 'Kết quả', 'common.start': 'Bắt đầu', 'common.save': 'Lưu', 'common.cancel': 'Hủy', 'common.retry': 'Thử lại',
    'home.greeting': 'Xin chào, {name} 👋', 'home.prompt': 'Hôm nay bạn muốn học gì?', 'home.todayGoal': 'Mục tiêu hôm nay',
    'home.path': 'Lộ trình cá nhân', 'home.today': 'hôm nay', 'home.srsReview': 'Ôn SRS', 'home.practiceTest': 'Luyện đề', 'home.notRequired': 'Không bắt buộc hoàn thành tất cả.', 'home.continueLearning': 'Tiếp tục học', 'home.todayReview': 'Ôn tập hôm nay', 'home.reviewTip': 'Ôn đúng lúc để nhớ lâu hơn.', 'home.reviewNow': 'Ôn ngay', 'home.todayPractice': 'Luyện tập hôm nay', 'home.koreanPractice': 'Luyện đề tiếng Hàn', 'home.notCompleted': 'Bạn chưa làm đề nào', 'home.reviewDue': 'Ôn {count} từ đến hạn', 'home.reviewDueReason': 'Bắt đầu bằng từ đến hạn để bảo vệ nhịp SRS.', 'home.recommended': 'Đề xuất cho bạn', 'home.learningPath': 'Lộ trình', 'home.pathSubtitle': 'Từ nền tảng đến kỳ thi', 'home.locked': 'Khóa',
    'welcome.title': 'Tiếng Hàn được thiết kế dành riêng cho người Việt.', 'welcome.point.level': 'Học theo trình độ.', 'welcome.point.goal': 'Học theo mục tiêu.', 'welcome.point.progress': 'Tiến bộ mỗi ngày.',
    'auth.registerSubtitle': 'Chỉ mất vài phút để TH-Tiếng Hàn hiểu mục tiêu của bạn.', 'auth.loginSubtitle': 'Tiếp tục lộ trình tiếng Hàn dành riêng cho bạn.',
    'onboarding.goalsTitle': 'Bạn học tiếng Hàn để làm gì?', 'onboarding.goalsSubtitle': 'Bạn có thể chọn nhiều mục tiêu.', 'onboarding.levelTitle': 'Trình độ tiếng Hàn hiện tại của bạn?', 'onboarding.levelSubtitle': 'Chọn phương án gần đúng nhất. Bạn có thể làm bài kiểm tra đầu vào.', 'onboarding.placementTitle': 'Kiểm tra trình độ đầu vào', 'onboarding.placementSubtitle': 'Chọn một đáp án. Kết quả chỉ dùng để gợi ý lộ trình MVP.',
    'speaking.title': 'Luyện nói', 'writing.title': 'Luyện viết', 'profile.settings': 'Cài đặt', 'profile.language': 'Ngôn ngữ', 'profile.appearance': 'Giao diện'
  },
  phrases: {
    'Trang chủ':'Trang chủ','Học':'Học','Ôn tập':'Ôn tập','Luyện tập':'Luyện tập','Cá nhân':'Cá nhân','Đăng nhập':'Đăng nhập','Đăng ký':'Đăng ký','Email':'Email','Mật khẩu':'Mật khẩu','Quên mật khẩu?':'Quên mật khẩu?','Bắt đầu học':'Bắt đầu học','Đã có tài khoản?':'Đã có tài khoản?','Chưa có tài khoản?':'Chưa có tài khoản?','Giao diện':'Giao diện','Ngôn ngữ':'Ngôn ngữ','Theo thiết bị':'Theo thiết bị','Hệ thống':'Theo thiết bị','Sáng':'Sáng','Tối':'Tối','Tiếng Việt':'Tiếng Việt','English':'English','中文（简体）':'中文（简体）','Chào mừng trở lại 👋':'Chào mừng trở lại 👋','Bắt đầu lộ trình của bạn':'Bắt đầu lộ trình của bạn','Kết quả':'Kết quả','Luyện nói':'Luyện nói','Luyện viết':'Luyện viết','Quay lại':'Quay lại','Lưu':'Lưu','Hủy':'Hủy','Thử lại':'Thử lại','Bắt đầu':'Bắt đầu'
  }
};
Object.assign(window.KLEARN_LOCALES.vi.keys, {
  'common.continue': 'Tiếp tục', 'romanization.label': 'Phiên âm', 'romanization.on': 'Bật', 'romanization.off': 'Tắt', 'romanization.actual': 'Đọc thực tế', 'exercise.tapHint': 'Chạm vào các từ bên dưới', 'lesson.grammarEyebrow': 'Ngữ pháp sơ cấp', 'lesson.title': 'Trợ từ chủ đề', 'home.streak': 'liên tiếp', 'home.toReview': 'cần ôn', 'home.toCheck': 'cần kiểm tra', 'home.continueGrammar': ' 은/는 và 이/가',
  'home.listening': 'Nghe', 'home.speaking': 'Nói', 'home.shortWriting': 'Viết ngắn', 'home.latestScore': 'Điểm gần nhất', 'home.reviewNowAction': 'Luyện ngay', 'home.quickPractice': 'Luyện nhanh', 'home.start': 'Bắt đầu',
  'lesson.courseEyebrow': 'Bài học MVP', 'lesson.objective': 'Mục tiêu: nhận biết cấu trúc, xem ví dụ và chuyển ngay sang bài luyện phù hợp.', 'lesson.studyGuide': 'Cách học gợi ý', 'lesson.listenSample': 'Đọc hoặc nghe mẫu tiếng Hàn.', 'lesson.compareMeaning': 'Đối chiếu nghĩa và cách dùng bằng tiếng Việt.', 'lesson.practiceSkill': 'Làm bài luyện theo kỹ năng để kiểm tra.', 'lesson.compareTitle': '🧠 So sánh với Tiếng Việt', 'lesson.compareBody': 'Trong tiếng Hàn, 은/는 được gắn sau danh từ để đánh dấu chủ đề của câu. Có thể hiểu gần với “thì” hoặc “là” trong tiếng Việt.', 'lesson.rule': 'Quy tắc', 'lesson.withBatchim': 'Có patchim (phụ âm cuối) + 은', 'lesson.withoutBatchim': 'Không có patchim + 는', 'lesson.examples': 'Ví dụ', 'lesson.arrange': '🧩 Sắp xếp câu', 'lesson.createSentence': 'Tạo câu: “Tôi là người Việt Nam.”', 'lesson.reset': 'Làm lại', 'lesson.check': 'Kiểm tra', 'lesson.close': 'Đóng bài học', 'lesson.back': 'Quay lại', 'lesson.complete': 'Hoàn thành bài', 'lesson.completed': 'Đã hoàn thành ✓', 'lesson.startPractice': 'Bắt đầu luyện {lesson}', 'lesson.audio': 'Nghe phát âm tiếng Hàn'
});
