window.KLEARN_LOCALES = window.KLEARN_LOCALES || {};
window.KLEARN_LOCALES['zh-CN'] = {
  label: '中文（简体）', short: '中文', htmlLang: 'zh-CN',
  keys: {
    'nav.home': '首页', 'nav.learn': '学习', 'nav.topik': 'TOPIK', 'nav.review': '复习', 'nav.assistant': '学习助手', 'nav.practice': '练习', 'nav.profile': '个人中心',
    'auth.login': '登录', 'auth.register': '注册', 'auth.welcome': '欢迎回来', 'auth.email': '邮箱', 'auth.password': '密码', 'auth.forgot': '忘记密码？',
    'auth.start': '开始学习', 'auth.hasAccount': '已有账号？', 'auth.noAccount': '还没有账号？',
    'theme.title': '显示模式', 'theme.description': '选择让你感到舒适的显示方式。', 'theme.system': '跟随系统', 'theme.light': '浅色', 'theme.dark': '深色', 'theme.systemDesc': '跟随设备显示', 'theme.lightDesc': '明亮易读', 'theme.darkDesc': '夜间更护眼',
    'language.title': '语言', 'language.vi': 'Tiếng Việt', 'language.en': 'English', 'language.zhCN': '中文（简体）',
    'common.back': '返回', 'common.result': '结果', 'common.start': '开始', 'common.save': '保存', 'common.cancel': '取消', 'common.retry': '再试一次',
    'home.greeting': '你好，{name} 👋', 'home.prompt': '今天想学习什么？', 'home.todayGoal': '今日目标',
    'home.path': '个性化学习路径', 'home.today': '今日', 'home.srsReview': 'SRS 复习', 'home.practiceTest': '模拟练习', 'home.notRequired': '无需完成全部任务。', 'home.continueLearning': '继续学习', 'home.todayReview': '今日复习', 'home.reviewTip': '及时复习，记忆更牢固。', 'home.reviewNow': '立即复习', 'home.todayPractice': '今日练习', 'home.koreanPractice': '韩语练习', 'home.notCompleted': '你还没有完成任何练习题。', 'home.reviewDue': '复习 {count} 个到期单词', 'home.reviewDueReason': '优先复习到期单词，保持 SRS 学习节奏。', 'home.recommended': '为你推荐', 'home.learningPath': '学习路径', 'home.pathSubtitle': '从基础学习到考试准备', 'home.locked': '未解锁',
    'welcome.title': '为越南学习者量身定制的韩语学习。', 'welcome.value': '从适合的水平开始，明确今天学什么，并通过真实结果看到进步。', 'welcome.point.level': '韩文字母 → TOPIK', 'welcome.point.goal': '每日学习计划', 'welcome.point.progress': '有证据的进步',
    'auth.registerSubtitle': '只需几分钟，TH-Tiếng Hàn 就能了解你的学习目标。', 'auth.loginSubtitle': '继续你的个性化韩语学习计划。',
    'onboarding.goalsTitle': '你为什么学习韩语？', 'onboarding.goalsSubtitle': '可以选择多个目标。', 'onboarding.levelTitle': '你目前的韩语水平？', 'onboarding.levelSubtitle': '选择最接近的选项，也可以参加入门测试。', 'onboarding.placementTitle': '入门水平测试', 'onboarding.placementSubtitle': '请选择一个答案，结果仅用于推荐学习路径。',
    'speaking.title': '口语练习', 'writing.title': '写作练习', 'profile.settings': '设置', 'profile.language': '语言', 'profile.appearance': '显示模式'
  },
  phrases: {
    'Trang chủ':'首页','Học':'学习','Ôn tập':'复习','Luyện tập':'练习','Cá nhân':'我的','Đăng nhập':'登录','Đăng ký':'注册','Email':'邮箱','Mật khẩu':'密码','Quên mật khẩu?':'忘记密码？','Bắt đầu học':'开始学习','Đã có tài khoản?':'已有账号？','Chưa có tài khoản?':'还没有账号？','Giao diện':'显示模式','Ngôn ngữ':'语言','Theo thiết bị':'跟随系统','Hệ thống':'跟随系统','Sáng':'浅色','Tối':'深色','Tiếng Việt':'Tiếng Việt','English':'English','中文（简体）':'中文（简体）','Chào mừng trở lại 👋':'欢迎回来 👋','Bắt đầu lộ trình của bạn':'开始你的学习之旅','Kết quả':'结果','Luyện nói':'口语练习','Luyện viết':'写作练习','Quay lại':'返回','Lưu':'保存','Hủy':'取消','Thử lại':'再试一次','Bắt đầu':'开始','Hỗ trợ đọc Hangul':'韩文阅读辅助','Tiến bộ mỗi ngày.':'每天进步。','Học theo trình độ.':'按水平学习。','Học theo mục tiêu.':'按目标学习。'
  }
};
Object.assign(window.KLEARN_LOCALES['zh-CN'].phrases, {
  'Tiếng Hàn được thiết kế dành riêng cho người Việt.':'为越南学习者量身定制的韩语学习。', 'Học theo trình độ.':'按水平学习。', 'Học theo mục tiêu.':'按目标学习。', 'Tiến bộ mỗi ngày.':'每天进步。',
  'Từ vựng TOPIK 1–6':'TOPIK 1–6 词汇', 'Ôn tập từ vựng':'词汇复习', 'Flashcard SRS':'SRS 单词卡', 'Quên':'忘记', 'Khó':'困难', 'Nhớ':'记得', 'Rất dễ':'很简单',
  'Đúng rồi!':'回答正确！', 'Chưa đúng':'还不正确', 'Chính xác':'正确', 'Chưa chính xác.':'还不正确。', 'Đáp án đúng:':'正确答案：', 'Giải thích':'解析', 'Mẹo phát âm':'发音提示', 'Gợi ý trả lời':'回答提示', 'Yêu cầu:':'要求：', 'Từ gợi ý':'提示词', 'Nộp bài':'提交', 'Bài viết đã lưu':'写作已保存', 'Bài mẫu':'示例答案', 'Lịch sử luyện tập':'练习历史', 'Không có bộ đề phù hợp. Hãy thử thay đổi bộ lọc.':'没有匹配的练习题，请尝试更改筛选条件。', 'Không có từ phù hợp':'没有匹配的词汇', 'Mở kho từ vựng':'打开词汇库', 'Kiểm tra vốn từ đã học':'测试已学词汇', 'Luyện nhanh':'快速练习', 'Bắt đầu luyện nhanh':'开始快速练习', 'Chọn đề':'选择练习', 'Làm đề':'开始练习', 'Làm lại':'再试一次', 'Nghe':'听力', 'Nói':'口语', 'Đọc':'阅读', 'Viết':'写作', 'Ngữ pháp':'语法', 'Từ vựng':'词汇', 'Mục tiêu':'目标', 'Cấp độ':'水平', 'Trạng thái':'状态', 'Tất cả':'全部', 'Dễ':'简单', 'Trung bình':'中等', 'Khó':'困难', 'Bỏ qua':'跳过', 'Hoàn thành':'完成', 'Tiếp tục':'继续', 'Tiếp theo':'下一题', 'Xem kết quả':'查看结果', 'Đăng xuất':'退出登录'
});

Object.assign(window.KLEARN_LOCALES['zh-CN'].keys, {
  'lesson.courseEyebrow': '练习课程',
  'ai.title': '学习帮助', 'ai.subtitle': '需要时提供额外讲解',
  'ai.placeholder': '询问当前韩语课程...', 'ai.thinking': '正在准备回答……',
  'ai.privacy': '启用后，本功能可使用交流内容和学习进度提供更合适的建议。不会发送密码或登录码。',
  'ai.empty': '可以询问语法、词汇、发音或当前课程。',
  'ai.notConfigured': '在线学习帮助尚未配置。',
  'ai.offline': '在线学习帮助需要互联网连接。你仍可使用离线词典和短语手册。',
  'ai.fab': '打开学习帮助', 'ai.fabLabel': '提问', 'ai.newChat': '新交流',
  'ai.close': '关闭学习帮助', 'ai.disabledTitle': '学习帮助已关闭',
  'ai.disabledBody': '智能辅助已根据你的设置关闭。', 'ai.settings': '打开设置'
});
Object.assign(window.KLEARN_LOCALES['zh-CN'].phrases, { 'Học liệu':'学习资料','Ghi chú của tôi':'我的笔记','Đã lưu':'已收藏','Bài giảng Video':'视频课程','Kho đề TOPIK':'TOPIK 题库','Xem học liệu':'打开资料','Mở lại':'再次打开','Đánh dấu đã xem':'标记为已查看','Đã xem':'已查看','Đánh dấu đoạn':'标记段落','Bỏ đánh dấu':'取消标记','Lưu học liệu':'收藏资料','Lưu ghi chú':'保存笔记','Cập nhật ghi chú':'更新笔记','Hủy sửa':'取消编辑','Chưa có ghi chú':'暂无笔记','Chưa có mục đã lưu':'暂无收藏','Draft · chưa phát hành':'草稿 · 尚未发布','Xem thông tin':'查看详情','Chưa có video được cấp quyền cho bài này.':'此课程暂无获得授权的视频。','Video chưa được phát hành':'视频尚未发布','Mở bài giảng':'打开课程','Chapters':'章节','Quick Check':'快速检查','Biên soạn bởi':'编写者','Nguồn':'来源','License':'许可' });
Object.assign(window.KLEARN_LOCALES['zh-CN'].phrases, {
  'Khóa học':'课程','Khóa học theo lộ trình':'结构化课程','Chọn đúng chặng học; tiến độ được lấy trực tiếp từ các bài đã hoàn thành.':'选择合适阶段；进度直接来自已完成的课程。','Nền tảng tiếng Hàn':'韩语基础','Tiếng Hàn sơ cấp':'初级韩语','Tiếng Hàn trung cấp':'中级韩语','Tiếng Hàn nâng cao':'高级韩语','Chuẩn bị thi TOPIK':'TOPIK备考','Đã hoàn thành':'已完成','Đang học':'学习中','Chưa bắt đầu':'未开始','Chiến thuật và mock exam':'策略与模拟考试','Tiếp tục khóa học':'继续课程','Xem khóa học':'查看课程','Mở chiến thuật TOPIK':'打开TOPIK策略','Bài học':'课程','Bài tiếp theo':'下一课','Mở Chiến thuật TOPIK':'打开TOPIK策略实验室','TOPIK Strategy Lab':'TOPIK策略实验室','Chiến thuật TOPIK':'TOPIK策略','Học cách nhận diện và xử lý từng dạng câu trước khi bấm giờ làm đề.':'在计时练习前学习识别并解决各类题型。','Đã luyện':'已练习','Chưa luyện':'未练习','Nhận biết dạng câu':'识别题型','Mục tiêu câu hỏi':'题目目标','4 bước xử lý':'四步方法','Lỗi thường gặp':'常见错误','Luyện 5 câu':'练习5题','Luyện 10 câu':'练习10题','Nói không phải là phần thi TOPIK chuẩn hóa.':'口语不是标准化TOPIK考试部分。','Bấm vào từ tiếng Hàn để xem nhanh nghĩa.':'点击韩语单词快速查看释义。','Chưa có dữ liệu từ này.':'暂无该词条。','Hỏi trợ lý':'询问助教','Thêm vào SRS':'加入SRS','Mở từ điển đầy đủ':'打开完整词典','Từ liên quan':'相关词','Tóm tắt':'总结','Giải thích ngắn':'简要说明','Câu ví dụ':'例句','Bước':'步骤','Quick Check':'快速检查','Practice':'练习','Tổng kết':'总结','Kiểm tra đáp án':'检查答案','Đáp án của bạn':'你的答案','Chọn đáp án để tiếp tục.':'选择答案继续。','Chính xác — tiếp tục nhé!':'正确，继续吧！','Hãy xem lại gợi ý rồi thử lại.':'查看提示后重试。','Lưu tiến độ bài học':'保存课程进度','Bài học đã hoàn thành.':'课程已完成。','Tiến độ khóa học':'课程进度','Không có bài học trong khóa này.':'此课程暂无课程。'
});
Object.assign(window.KLEARN_LOCALES['zh-CN'].phrases, { 'Mở AI Gia sư TamHoanq': '打开 AI 韩语导师', 'AI Gia sư TamHoanq': 'AI 韩语导师', 'Hỗ trợ học tiếng Hàn': '韩语学习支持', 'Cuộc trò chuyện mới': '新对话', 'Đóng AI': '关闭 AI', 'Bài này': '本课', 'Sửa câu': '修改句子', 'Tạo bài tập': '创建练习', 'Bạn': '你', 'AI đang suy nghĩ...': 'AI 正在思考……', 'Gửi câu hỏi AI': '发送 AI 问题' });
Object.assign(window.KLEARN_LOCALES['zh-CN'].phrases, { 'Tìm bằng Hangul, romanization hoặc nghĩa tiếng Việt.': '可按韩文、罗马音或越南语释义搜索。', 'Từ điển 1.000+ mục': '词典词条', 'Tất cả loại từ': '所有词性' });
Object.assign(window.KLEARN_LOCALES['zh-CN'].keys, {
  'common.continue': '继续', 'romanization.label': '罗马音', 'romanization.on': '开', 'romanization.off': '关', 'romanization.actual': '实际读法', 'exercise.tapHint': '点击下面的词语', 'lesson.grammarEyebrow': '初级语法', 'lesson.title': '主题助词', 'home.streak': '连续学习', 'home.toReview': '待复习', 'home.toCheck': '待检测', 'home.continueGrammar': ' 은/는 与 이/가',
  'home.listening': '听力', 'home.speaking': '口语', 'home.shortWriting': '短写作', 'home.latestScore': '最近得分', 'home.reviewNowAction': '立即练习', 'home.quickPractice': '快速练习', 'home.start': '开始', 'ai.title': 'AI 韩语导师', 'ai.subtitle': '韩语学习支持', 'ai.placeholder': '向韩语 AI 老师提问...', 'ai.thinking': 'AI 正在思考……', 'ai.privacy': 'AI 可能使用聊天内容和学习进度来提供个性化建议。不会发送密码或令牌。', 'ai.empty': '可以询问语法、词汇、发音或当前课程。', 'ai.notConfigured': 'AI 尚未配置。', 'ai.offline': 'AI 需要互联网连接。你仍可使用离线词典和短语手册。',
  'lesson.courseEyebrow': 'MVP 课程', 'lesson.objective': '目标：认识结构、查看例句，并立即进入匹配练习。', 'lesson.studyGuide': '建议学习步骤', 'lesson.listenSample': '阅读或听取韩语示例。', 'lesson.compareMeaning': '对照中文含义和用法。', 'lesson.practiceSkill': '按技能练习来检查理解。', 'lesson.compareTitle': '🧠 结构对比', 'lesson.compareBody': '在韩语中，은/는 接在名词后，用来标记句子的主题。它大致相当于“至于……”或“是”。', 'lesson.rule': '规则', 'lesson.withBatchim': '有收音（词尾辅音）+ 은', 'lesson.withoutBatchim': '没有收音 + 는', 'lesson.examples': '例句', 'lesson.arrange': '🧩 排列句子', 'lesson.createSentence': '造句：“我是越南人。”', 'lesson.reset': '重来', 'lesson.check': '检查', 'lesson.close': '关闭课程', 'lesson.back': '返回', 'lesson.complete': '完成课程', 'lesson.completed': '已完成 ✓', 'lesson.startPractice': '开始练习 {lesson}', 'lesson.audio': '听韩语发音', 'ai.fab': '打开 AI 韩语导师', 'ai.newChat': '新对话', 'ai.close': '关闭 AI', 'ai.lesson': '本课', 'ai.correct': '修改句子', 'ai.translate': '翻译', 'ai.exercise': '创建练习', 'ai.you': '你', 'ai.send': '发送', 'ai.error': '无法连接 AI，请稍后再试。'
});
Object.assign(window.KLEARN_LOCALES['zh-CN'].phrases, { 'Độ khó': '难度', 'Chạm vào các từ bên dưới': '点击下面的词语', 'Phiên âm: Bật': '罗马音：开', 'Phiên âm: Tắt': '罗马音：关' });
Object.assign(window.KLEARN_LOCALES['zh-CN'].phrases, {
  'Hệ sinh thái học tập nâng cao':'高级学习生态','Khám phá':'探索','Hệ sinh thái phát triển của bạn':'你的学习成长生态','Từ hành vi học thật đến tiếng Hàn đời sống, nghề nghiệp và năng lực dài hạn.':'从真实学习行为到生活、职业与长期韩语能力。','Hành trình học của tôi':'我的学习旅程','Ngày bắt đầu học':'开始学习','Hangul đầu tiên':'第一个韩文字母','100 từ đã thành thạo':'掌握100个单词','Bài học đầu tiên':'第一课','Tổng thời gian học':'总学习时间','Kế hoạch phù hợp trạng thái hiện tại':'符合当前状态的计划','Sống tại Hàn Quốc':'在韩国生活','Luyện nhiệm vụ, mục tiêu và kết quả thay vì chỉ đọc hội thoại.':'练习任务、目标和结果，而不只是阅读对话。','Đánh giá kết quả':'评估结果','Đạt mục tiêu giao tiếp':'已达到交流目标','Cần đủ ý chính':'需要补充核心意思','Đọc tài liệu, biển hiệu và menu':'阅读文件、招牌和菜单','Ảnh chỉ được xử lý trong trình duyệt; không upload và không lưu file.':'图片仅在浏览器中处理，不上传、不保存。','Chọn ảnh':'选择图片','Phân tích':'分析','Địa chỉ và hệ thống số':'地址与数字系统','Kiểm tra':'检查','Bản đồ phát triển ngôn ngữ':'语言成长图','Xu hướng lỗi':'错误趋势','Chưa đủ lỗi thật để tạo bản đồ.':'真实错误数据不足，暂不能生成图谱。','Chưa có câu được lưu':'尚未保存句子','Lưu câu đầu tiên để bắt đầu theo dõi theo thời gian.':'保存第一个句子，开始追踪长期变化。','Chấm Naturalness':'自然度评分','Cây kỹ năng và Mastery Map':'技能树与掌握地图','Mọi nhánh dùng mastery và hoạt động thật; không cấp level ảo.':'所有分支均使用真实掌握度和活动，不设置虚拟等级。','Đã hoàn thành':'已完成','Đang tiến tới mục tiêu thật':'正在迈向真实目标','Tiếng Hàn cho mục tiêu nghề nghiệp':'职业目标韩语','Chọn một lộ trình thực tế; tiến độ chỉ tăng khi hoàn thành bài luyện.':'选择实际路径；只有完成练习才会增加进度。','Lưu và đánh giá':'保存并评估','Kiến trúc học tập thông minh':'智能学习架构','Không có chatbot mới; AI chỉ hỗ trợ trên dữ liệu học và nội dung đã kiểm duyệt.':'不新增聊天机器人；AI仅基于学习数据和已审核内容提供支持。','Chỉ dùng content đã duyệt':'仅使用已审核内容','Tạo bài phụ':'生成辅助练习','Học tiếp':'继续学习','Mở Voice World':'打开语音世界','Tự bật chế độ':'启用模式','Quay lại':'返回'
});
Object.assign(window.KLEARN_LOCALES['zh-CN'].phrases, { 'Từ điển': '词典', 'Tra từ tiếng Hàn': '韩语词典', 'Dịch & Đặt câu': '翻译与造句', 'Sổ tay câu': '短语手册', 'Tra gần đây': '最近搜索', 'Tất cả loại từ': '所有词性', 'Không tìm thấy mục phù hợp.': '没有匹配的词条。', 'Lưu từ': '收藏单词', 'Đã lưu': '已收藏', 'Thêm vào ôn tập': '加入复习', 'Ví dụ': '例句', 'Chưa có ví dụ cho mục này.': '暂无例句。', 'Câu thông dụng': '常用句', 'Các mẫu câu có thể dùng offline.': '可离线使用的实用句型。', 'Công cụ ngôn ngữ': '语言工具', 'Tra từ, dịch cụm từ và câu với dữ liệu offline.': '使用离线数据查词并翻译短语和句子。', 'Dịch từ': '翻译来源', 'Sang': '目标语言', 'Ngữ cảnh': '场景', 'Chung': '通用', 'Cách nói': '语气', 'Lịch sự': '礼貌', 'Thân mật': '随意', 'Trang trọng': '正式', 'Nhập từ, cụm từ hoặc câu...': '输入单词、短语或句子……', 'Dịch': '翻译', 'Sao chép': '复制', 'Sao chép tiếng Hàn': '复制韩语', 'Lưu câu': '收藏句子', 'Luyện nói': '练习口语', 'Đã thêm vào bộ ôn tập.': '已加入复习。', 'Đã lưu câu.': '句子已保存。' });
Object.assign(window.KLEARN_LOCALES['zh-CN'].phrases, { 'Lý thuyết': '理论', 'Lộ trình': '学习路径', 'Luyện TOPIK': 'TOPIK 练习' });
Object.assign(window.KLEARN_LOCALES['zh-CN'].phrases, { 'Ôn tập thông minh':'智能复习','Tìm kiếm toàn app':'全局搜索','Phân tích tiến độ':'学习进度分析','Tuần này của bạn':'本周学习报告','Đang đồng bộ...':'同步中……','✓ Đã đồng bộ':'✓ 已同步','Ngoại tuyến':'离线','Chỉ lưu trên thiết bị':'仅保存在设备','Tạo phiên ôn thông minh':'创建智能复习','Báo cáo tuần':'周报','Phân tích theo kỹ năng':'技能分析','Phân tích theo dạng câu hỏi':'题型分析','Điểm mạnh':'优势','Cần cải thiện':'需要改进','Nhắc học':'学习提醒','Nhắc từ SRS đến hạn':'提醒复习到期词汇','Nhắc kế hoạch hôm nay':'提醒今日计划','Nhắc duy trì streak':'提醒保持连续学习','Bài có hoạt động':'有活动的课程','Từ thành thạo':'已掌握词汇','Đề đã làm':'完成的练习','Phút học':'学习分钟','Global Search':'全局搜索','TOPIK Analytics':'TOPIK 分析','Weekly Insights':'周学习报告','Tạo phiên ôn':'创建复习','Câu đã chạm':'接触课程数','Cần củng cố':'需要巩固'});
Object.assign(window.KLEARN_LOCALES['zh-CN'].phrases, { 'Đăng ký local':'创建本地账号','Đăng nhập local':'本地登录','Đăng ký cloud':'注册云账号','Đăng nhập cloud':'登录云账号','☁ Đăng ký cloud':'☁ 注册云账号','☁ Đăng nhập cloud':'☁ 登录云账号','Đồng bộ đa thiết bị':'多设备同步','Kết nối tài khoản cloud':'连接云账号','Cloud chưa được cấu hình hoặc đang ngoại tuyến':'云同步未配置或当前离线','Dữ liệu hiện chỉ được lưu trên thiết bị này. Hãy chủ động đăng nhập hoặc đăng ký Supabase để liên kết đúng tài khoản local hiện tại.':'数据目前仅保存在此设备。请主动登录或注册 Supabase，以明确关联当前本地账号。','Email cloud':'云账号邮箱','Mật khẩu cloud':'云账号密码','Đăng nhập & liên kết':'登录并关联','Đăng ký & liên kết':'注册并关联','Đã kết nối':'已连接','Đồng bộ ngay':'立即同步','Ngắt cloud':'断开云连接','dữ liệu local vẫn là nguồn hoạt động chính.':'本地数据仍是主要工作数据源。','Đã ngắt cloud. Dữ liệu local vẫn được giữ nguyên.':'云连接已断开，本地数据已保留。','☁ Cloud Account':'☁ 云账号','↻ Đang đồng bộ':'↻ 正在同步','☁ Đã đồng bộ':'☁ 已同步','💾 Ngoại tuyến':'💾 离线','⚠ Chưa đồng bộ':'⚠ 尚未同步','Lỗi đồng bộ':'同步错误','Đã kết nối cloud và đồng bộ dữ liệu.':'云账号已连接，数据已同步。','Đã kết nối cloud. Đồng bộ chưa hoàn tất; dữ liệu local vẫn an toàn.':'云账号已连接。同步尚未完成，本地数据仍然安全。','Hãy mở email xác nhận Supabase rồi quay lại đăng nhập cloud.':'请打开 Supabase 确认邮件，然后返回云账号登录。','Tài khoản cloud đã được tạo, liên kết và đồng bộ.':'云账号已创建、关联并同步。','Tài khoản cloud đã được liên kết. Đồng bộ chưa hoàn tất; dữ liệu local vẫn an toàn.':'云账号已关联。同步尚未完成，本地数据仍然安全。'});
Object.assign(window.KLEARN_LOCALES['zh-CN'].phrases, {
  'Học tập':'学习','TOPIK':'TOPIK','Trợ lý':'学习助手','Hồ sơ':'个人中心','Hôm nay học gì?':'今天学什么？','Giữ nhịp đều, mỗi ngày một bước.':'保持节奏，每天进步一点。','Tiến độ mục tiêu':'目标进度','Xem lộ trình →':'查看学习路径 →','Kế hoạch cá nhân':'个性化计划','Nhiệm vụ hôm nay':'今日任务','Xem lộ trình':'查看学习路径','Tiếp tục học':'继续学习','Từ cần ôn':'待复习单词','Kỹ năng cần cải thiện':'待提升技能','Luyện ngay':'立即练习','Ôn ngay':'立即复习','Ôn nhanh':'快速复习','Phiên học ngắn':'短时学习','Chọn thời lượng':'选择时长','Sổ từ':'单词本','Mẫu câu thực tế':'实用句型',
  'Bài học TOPIK':'TOPIK 课程','Từ vựng':'词汇','Luyện nghe':'听力练习','Luyện nói':'口语练习','Luyện viết':'写作练习','Đọc hiểu':'阅读理解','Luyện viết chữ':'韩文书写','Tiếng Hàn thực tế':'实用韩语','Tiến độ cấp hiện tại':'当前等级进度','Xem bài học':'查看课程','Mỗi ngày một phiên ngắn':'每天一次短练习','Ôn 5–20 phút':'复习 5–20 分钟','Sổ từ vựng cá nhân':'个人单词本','Từ đã lưu':'已收藏单词','Test nhanh':'快速测试',
  'Tiếng Hàn trong đời sống':'生活韩语','Học để sử dụng':'学以致用','Chọn bối cảnh phù hợp với mục tiêu của bạn.':'选择符合学习目标的场景。','XKLĐ':'海外就业','Du học':'留学','Công sở':'职场','Mẫu câu dùng ngay':'即学即用句型','Xem tất cả':'查看全部',
  'Báo cáo tiến bộ':'学习进度报告','Kết quả học tập':'学习成果','Điểm trung bình':'平均分','Điểm cần tập trung':'重点提升','Báo cáo tuần / tháng':'周报 / 月报','Trợ lý học tập':'学习助手','Tóm tắt tiến độ':'进度摘要','Sổ lỗi của tôi':'我的错题本','Hồ sơ học tập':'学习档案','Xu hướng học tập':'学习趋势','Gợi ý ôn tập':'复习建议',
  'Kho đề TOPIK':'TOPIK 题库','Thi thử full đề':'完整模拟考试','Đề ngẫu nhiên':'随机试题','Đề nâng cao':'高级试题','Theo chủ đề':'按主题','Luyện lỗi sai':'错题练习','Đề đã lưu':'已收藏试题','Lịch sử':'历史记录','Phân tích TOPIK':'TOPIK 分析','Kế hoạch luyện thi':'备考计划','Điều chỉnh':'调整'
  ,'Phiên rút gọn để lấy lại nhịp học.':'用较短的练习找回学习节奏。','Ba hoạt động quan trọng nhất cho hôm nay.':'今天最重要的三个活动。','Theo tiến độ hiện tại':'根据当前进度','Xem lại kế hoạch':'查看计划','Bắt đầu học':'开始学习','Mục tiêu cá nhân':'个人目标','Mục tiêu & deadline':'目标与截止日期','Tạo lộ trình phù hợp':'创建合适的路径','Tổng hợp tuần':'本周概览','Chủ đề liên quan:':'相关主题：','Liên kết chủ đề yếu: +2':'薄弱主题关联：+2','Chưa phát hiện điểm yếu rõ':'暂未发现明显弱项'
});
Object.assign(window.KLEARN_LOCALES['zh-CN'].phrases, {
  'Phòng luyện Nghe':'听力训练室','Nghe bình thường':'听力','Nghe và nhập Hangul':'听写','Nghe rồi nói lại':'跟读','Nghe và trả lời câu hỏi':'听力测验','Phòng luyện Nói':'口语练习室','Phòng luyện Viết':'写作考试室','Thi thử TOPIK':'TOPIK 模拟考试','Thi thử full đề':'完整模拟考试','Exam mode · timer · không gợi ý':'考试模式 · 计时 · 无提示','Repeat':'跟读重复','Situation':'情境','Role Play':'角色扮演','Free Speaking':'自由表达','Shadowing':'影子跟读','Dictation':'听写','Quiz':'测验','Text comparison':'文本对比','Transcript nhận được':'识别文本','Đánh giá luyện tập':'练习评估','Không phải điểm TOPIK chính thức':'不是官方 TOPIK 成绩','Đặt lại':'重置','Lưu lỗi':'保存错误','Ôn ngữ pháp liên quan':'复习相关语法','Câu tiếp theo':'下一题','Bắt đầu lại':'重新开始','Xóa A-B':'清除 A-B','Nghe từ':'从此处播放','Hết giờ. Hãy nộp bài viết.':'时间到，请提交写作。','Exam mode: không hiển thị transcript, translation, romanization, hint, explanation hoặc dictionary.':'考试模式：隐藏听写文本、翻译、罗马音、提示、解析和词典。','Kết quả thi thử':'模拟考试结果','Thời gian':'用时','Hoàn thành yêu cầu':'完成要求','Độ khớp câu':'句子匹配度','Grammar feedback':'语法反馈','Vocabulary feedback':'词汇反馈','Suggested expression':'推荐表达','Bật transcript':'显示文本','Bật bản dịch':'显示翻译','Bật romanization':'显示罗马音'
});
Object.assign(window.KLEARN_LOCALES['zh-CN'].keys, {
  'lesson.courseEyebrow': '学习路径课程', 'ai.title': '学习助手', 'ai.subtitle': '需要时提供额外讲解',
  'ai.placeholder': '询问当前韩语课程...', 'ai.thinking': '正在准备回答……',
  'ai.privacy': '启用 AI 辅助后，系统可使用交流内容和学习进度提供更合适的建议。不会发送密码或登录码。',
  'ai.empty': '可以询问语法、词汇、发音或当前课程。', 'ai.notConfigured': '在线学习帮助尚未配置。',
  'ai.offline': '学习助手需要互联网连接。你仍可使用离线词典和短语手册。',
  'ai.fab': '打开学习助手', 'ai.fabLabel': '提问', 'ai.newChat': '新交流', 'ai.close': '关闭学习助手',
  'ai.disabledTitle': '学习助手已关闭', 'ai.disabledBody': 'AI 辅助已根据你的设置关闭。', 'ai.settings': '打开设置', 'nav.assistant': '学习助手'
});
