import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const mobileRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const root = path.resolve(mobileRoot, '..');
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8');
const packageJson = JSON.parse(read('mobile/package.json'));
const capacitor = JSON.parse(read('mobile/capacitor.config.json'));
const contract = JSON.parse(read('mobile/mobile-app.config.json'));
const p78 = JSON.parse(read('content/mobile-native-platform.json'));

assert.equal(packageJson.dependencies['@capacitor/core'].split('.')[0], packageJson.devDependencies['@capacitor/cli'].split('.')[0]);
assert.equal(packageJson.dependencies['@capacitor/android'], packageJson.dependencies['@capacitor/ios']);
assert.equal(capacitor.appId, contract.appId);
assert.equal(capacitor.webDir, 'www');
assert.equal(capacitor.android.allowMixedContent, false);
assert.equal(contract.contractVersion, 3);
assert.equal(contract.security.authSessionStorage, 'native-keychain-or-keystore');
assert.equal(contract.bridge.biometric, 'NativeBiometricService');
assert.equal(contract.bridge.storage, 'MobileDownloadManagerService');
assert.equal(packageJson.dependencies['@aparajita/capacitor-biometric-auth'], '10.0.0');
assert.equal(packageJson.dependencies['@aparajita/capacitor-secure-storage'], '8.0.0');
assert.equal(p78.architecture.separateMobileLearningEngine, false);
assert.equal(p78.architecture.separateMobileProgressStore, false);
assert.deepEqual(p78.mobileWidths, [320, 360, 390, 430]);
assert.ok(fs.existsSync(path.join(mobileRoot, 'www/index.html')), 'run npm run build first');
const builtIndex = fs.readFileSync(path.join(mobileRoot, 'www/index.html'), 'utf8');
assert.match(builtIndex, /mobile-runtime-config\.js/);
assert.match(builtIndex, /mobile-native-plugins\.js/);
assert.match(builtIndex, /mobile-native-platform\.js\?v=2/);
assert.match(fs.readFileSync(path.join(mobileRoot, 'www', 'data', 'route-loader.js'), 'utf8'), /p78-mobile-native\.css\?v=2/);
const nativeBundle = path.join(mobileRoot, 'www', 'mobile-native-plugins.js');
assert.ok(fs.statSync(nativeBundle).size < p78.performance.nativePluginBundleMaxBytes, 'native plugin bundle exceeds P78 budget');
assert.match(read('data/platform-runtime.js'), /Only application API paths are allowed/);
assert.match(read('data/mobile-native.js'), /exchangeCodeForSession/);
assert.match(read('data/cloud-sync.js'), /SecureStorageAdapter/);
assert.match(read('supabase/migrations/20260909_mobile_native_ecosystem.sql'), /mobile_push_devices/);
for (const file of ['mobile/store/metadata.json', 'mobile/store/privacy.json', 'mobile/store/screenshots.json']) assert.ok(fs.existsSync(path.join(root, file)), `${file} missing`);
console.log(`P78 native doctor: shared Learning Core, secure auth, biometric/deep-link bridge, ${fs.statSync(nativeBundle).size}-byte plugin bundle and store contracts passed`);
