-- P62: content quality governance, version history and least-privilege publishing.
-- This migration changes content metadata only. It does not touch learner progress,
-- SRS, mastery, vocabulary history, authentication sessions or cloud-sync payloads.

alter table public.user_roles drop constraint if exists user_roles_role_check;
alter table public.user_roles
  add constraint user_roles_role_check
  check (role in ('student','teacher','reviewer','content_editor','admin'));

alter table public.learning_content drop constraint if exists learning_content_review_status_check;
alter table public.learning_content
  add constraint learning_content_review_status_check
  check (review_status in ('draft','review','approved','deprecated'));

alter table public.learning_content
  add column if not exists created_by uuid references auth.users(id) on delete set null,
  add column if not exists updated_by uuid references auth.users(id) on delete set null,
  add column if not exists reviewed_by uuid references auth.users(id) on delete set null,
  add column if not exists reviewed_at timestamptz,
  add column if not exists published_at timestamptz,
  add column if not exists change_summary text not null default '' check (char_length(change_summary) <= 1000);

-- Preserve visibility of content already approved before the separate publish marker existed.
update public.learning_content
set published_at = coalesce(published_at, updated_at, now())
where review_status = 'approved' and verified = true and published_at is null;

alter table public.content_quality_reviews
  add column if not exists completeness_score integer check (completeness_score between 0 and 100),
  add column if not exists difficulty_match_score integer check (difficulty_match_score between 0 and 100),
  add column if not exists naturalness_score integer check (naturalness_score between 0 and 100);

alter table public.content_quality_reports drop constraint if exists content_quality_reports_report_type_check;
alter table public.content_quality_reports
  add constraint content_quality_reports_report_type_check
  check (report_type in ('meaning','audio','example','answer','difficulty','duplicate'));

create table if not exists public.learning_content_versions (
  id bigint generated by default as identity primary key,
  content_id text not null,
  version integer not null check (version > 0),
  content_type text not null,
  title text not null,
  difficulty text not null,
  source text not null,
  review_status text not null,
  verified boolean not null,
  body jsonb not null,
  audio_url text,
  change_summary text not null default '',
  changed_by uuid references auth.users(id) on delete set null,
  changed_at timestamptz not null default now(),
  unique (content_id, version)
);

create index if not exists learning_content_versions_lookup_idx
  on public.learning_content_versions (content_id, version desc);

alter table public.learning_content_versions enable row level security;
drop policy if exists "content staff read version history" on public.learning_content_versions;
create policy "content staff read version history"
  on public.learning_content_versions for select to authenticated
  using (public.has_any_role(array['reviewer','content_editor','admin']));

create or replace function public.guard_learning_content_quality_workflow()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  actor uuid := auth.uid();
  is_editor boolean := public.has_any_role(array['content_editor','admin']);
  is_reviewer boolean := public.has_any_role(array['reviewer','admin']);
  is_admin boolean := public.has_any_role(array['admin']);
begin
  new.updated_at := now();
  new.updated_by := actor;

  if tg_op = 'INSERT' then
    new.created_by := coalesce(new.created_by, actor);
    if actor is not null and (new.review_status <> 'draft' or new.verified or new.published_at is not null) then
      raise exception 'New content must enter the workflow as an unpublished draft';
    end if;
    return new;
  end if;

  if actor is not null and not (is_editor or is_reviewer) then
    raise exception 'Content workflow role required';
  end if;

  if actor is not null and not (
    (old.review_status = 'draft' and new.review_status in ('draft','review','deprecated'))
    or (old.review_status = 'review' and new.review_status in ('draft','review','approved','deprecated'))
    or (old.review_status = 'approved' and new.review_status in ('approved','review','deprecated'))
    or (old.review_status = 'deprecated' and new.review_status in ('deprecated','draft'))
  ) then
    raise exception 'Invalid content review transition';
  end if;

  if actor is not null and not is_editor and (
    new.title is distinct from old.title
    or new.difficulty is distinct from old.difficulty
    or new.source is distinct from old.source
    or new.body is distinct from old.body
    or new.audio_url is distinct from old.audio_url
  ) then
    raise exception 'Only content editors can change learning content';
  end if;

  if actor is not null and new.review_status = 'approved' and old.review_status <> 'approved' and not is_reviewer then
    raise exception 'Reviewer approval is required';
  end if;

  if new.review_status = 'approved' then
    if new.verified is not true or new.reviewed_by is null or new.reviewed_at is null then
      raise exception 'Approved content requires verified human review evidence';
    end if;
  elsif new.published_at is not null then
    raise exception 'Only approved content can be published';
  end if;

  if actor is not null and new.published_at is distinct from old.published_at and not is_admin then
    raise exception 'Only admins can publish or unpublish content';
  end if;

  if (
    new.title is distinct from old.title
    or new.difficulty is distinct from old.difficulty
    or new.source is distinct from old.source
    or new.body is distinct from old.body
    or new.audio_url is distinct from old.audio_url
  ) and new.version <= old.version then
    raise exception 'Content changes require a higher version';
  end if;

  return new;
end;
$$;

create or replace function public.archive_learning_content_version()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if new.version > old.version then
    insert into public.learning_content_versions (
      content_id, version, content_type, title, difficulty, source,
      review_status, verified, body, audio_url, change_summary, changed_by, changed_at
    ) values (
      old.id, old.version, old.type, old.title, old.difficulty, old.source,
      old.review_status, old.verified, old.body, old.audio_url,
      new.change_summary, auth.uid(), now()
    ) on conflict (content_id, version) do nothing;
  end if;
  return new;
end;
$$;

drop trigger if exists guard_learning_content_quality_workflow on public.learning_content;
create trigger guard_learning_content_quality_workflow
  before insert or update on public.learning_content
  for each row execute function public.guard_learning_content_quality_workflow();

drop trigger if exists archive_learning_content_version on public.learning_content;
create trigger archive_learning_content_version
  after update on public.learning_content
  for each row execute function public.archive_learning_content_version();

drop policy if exists "learners read approved learning content" on public.learning_content;
create policy "learners read approved learning content"
  on public.learning_content for select to anon, authenticated
  using (review_status = 'approved' and verified = true and published_at is not null);

drop policy if exists "admins read all learning content" on public.learning_content;
drop policy if exists "content staff read all learning content" on public.learning_content;
create policy "content staff read all learning content"
  on public.learning_content for select to authenticated
  using (public.has_any_role(array['reviewer','content_editor','admin']));

drop policy if exists "admins create learning content" on public.learning_content;
drop policy if exists "content editors create drafts" on public.learning_content;
create policy "content editors create drafts"
  on public.learning_content for insert to authenticated
  with check (
    public.has_any_role(array['content_editor','admin'])
    and review_status = 'draft'
    and verified = false
    and published_at is null
  );

drop policy if exists "admins update learning content" on public.learning_content;
drop policy if exists "content staff update learning content" on public.learning_content;
create policy "content staff update learning content"
  on public.learning_content for update to authenticated
  using (public.has_any_role(array['reviewer','content_editor','admin']))
  with check (public.has_any_role(array['reviewer','content_editor','admin']));

drop policy if exists "admins read all content quality" on public.content_quality_reviews;
drop policy if exists "content staff read all content quality" on public.content_quality_reviews;
create policy "content staff read all content quality"
  on public.content_quality_reviews for select to authenticated
  using (public.has_any_role(array['reviewer','content_editor','admin']));

drop policy if exists "admins create content quality" on public.content_quality_reviews;
drop policy if exists "reviewers create content quality" on public.content_quality_reviews;
create policy "reviewers create content quality"
  on public.content_quality_reviews for insert to authenticated
  with check (public.has_any_role(array['reviewer','admin']));

drop policy if exists "admins update content quality" on public.content_quality_reviews;
drop policy if exists "reviewers update content quality" on public.content_quality_reviews;
create policy "reviewers update content quality"
  on public.content_quality_reviews for update to authenticated
  using (public.has_any_role(array['reviewer','admin']))
  with check (public.has_any_role(array['reviewer','admin']));

drop policy if exists "reviewers read quality reports" on public.content_quality_reports;
create policy "reviewers read quality reports"
  on public.content_quality_reports for select to authenticated
  using (public.has_any_role(array['reviewer','content_editor','admin']));

drop policy if exists "reviewers manage quality reports" on public.content_quality_reports;
create policy "reviewers manage quality reports"
  on public.content_quality_reports for update to authenticated
  using (public.has_any_role(array['reviewer','content_editor','admin']))
  with check (public.has_any_role(array['reviewer','content_editor','admin']));

comment on table public.learning_content_versions is
  'Immutable snapshots of prior learning-content versions; no learner data is stored here.';
comment on function public.guard_learning_content_quality_workflow() is
  'Enforces Draft -> Review -> Approved -> Admin publish with human review evidence.';
